;track ids.
.ENUM
	track_flashman
	track_woodman
	track_crashman
	track_heatman
	track_airman
	track_metalman
	track_quickman
	track_bubbleman
	track_wily1_2
	track_wily3_4_5
	track_boss_show
	track_boss_fighting
	track_stage_select
	track_title_screen
	track_opening
	track_game_over
	track_password
	track_wily_castle
	track_wily_ufo
	track_ending
	track_staff_roll
	track_boss_defeated
	track_wily_defeated
	track_get_weapon
	track_18
	track_19
	track_1a
	track_1b
	track_1c
	track_1d
	track_1e
	track_1f
	track_20
	track_time_stopper
	track_22
	track_metal_blade
	track_mega_buster
	track_enemy_bullet
	track_megaman_hit
	track_force_beam
	track_refill
	track_landing
	track_wily_control
	track_enemy_hit
	track_mecha_dragon
	track_enemy_immune
	track_crash_bomber_grab
	track_select
	track_teleport_in
	track_leaf_shield
	track_open_menu
	track_33
	track_door
	track_atomic_fire_charge_1
	track_atomic_fire_charge_2
	track_atomic_fire_charge_3
	track_atomic_fire_release
	track_fly_boy
	track_teleport_out
	track_jump_into_water
	track_appearing_block
	track_red_liquid_1
	track_red_liquid_2
	track_air_shooter
	track_40
	track_death
	track_1up
.ENDENUM
