;32x32 blocksets with 16x16 blocksets | block attribute.
;block_attribute 2 and 3 setting see home/blocksets.asm. 
	      ;top left,                  bottom left,                top right,                  bottom right
	.BYTE $00 | block_attribute_null, $00 | block_attribute_null, $00 | block_attribute_null, $00 | block_attribute_null ;00
	.BYTE $19 | block_attribute_null, $1A | block_attribute_null, $1A | block_attribute_null, $19 | block_attribute_null ;01
	.BYTE $18 | block_attribute_null, $1A | block_attribute_null, $18 | block_attribute_null, $19 | block_attribute_null ;02
	.BYTE $18 | block_attribute_null, $19 | block_attribute_null, $18 | block_attribute_null, $19 | block_attribute_null ;03
	.BYTE $19 | block_attribute_null, $1A | block_attribute_null, $18 | block_attribute_null, $19 | block_attribute_null ;04
	.BYTE $18 | block_attribute_null, $1A | block_attribute_null, $1A | block_attribute_null, $19 | block_attribute_null ;05
	.BYTE $19 | block_attribute_null, $19 | block_attribute_null, $18 | block_attribute_null, $19 | block_attribute_null ;06
	.BYTE $18 | block_attribute_null, $19 | block_attribute_null, $19 | block_attribute_null, $19 | block_attribute_null ;07
	.BYTE $19 | block_attribute_null, $1F | block_attribute_3,    $19 | block_attribute_null, $22 | block_attribute_3    ;08
	.BYTE $19 | block_attribute_null, $24 | block_attribute_3,    $19 | block_attribute_null, $1F | block_attribute_3    ;09
	.BYTE $19 | block_attribute_null, $22 | block_attribute_3,    $19 | block_attribute_null, $24 | block_attribute_3    ;0A
	.BYTE $19 | block_attribute_null, $22 | block_attribute_3,    $19 | block_attribute_null, $23 | block_attribute_3    ;0B
	.BYTE $19 | block_attribute_null, $23 | block_attribute_3,    $19 | block_attribute_null, $23 | block_attribute_3    ;0C
	.BYTE $19 | block_attribute_null, $23 | block_attribute_3,    $19 | block_attribute_null, $24 | block_attribute_3    ;0D
	.BYTE $19 | block_attribute_null, $1F | block_attribute_3,    $19 | block_attribute_null, $1F | block_attribute_3    ;0E
	.BYTE $19 | block_attribute_null, $19 | block_attribute_null, $19 | block_attribute_null, $19 | block_attribute_null ;0F
	.BYTE $19 | block_attribute_null, $1F | block_attribute_3,    $19 | block_attribute_null, $22 | block_attribute_3    ;10
	.BYTE $19 | block_attribute_null, $24 | block_attribute_3,    $19 | block_attribute_null, $1F | block_attribute_3    ;11
	.BYTE $19 | block_attribute_null, $22 | block_attribute_3,    $19 | block_attribute_null, $24 | block_attribute_3    ;12
	.BYTE $19 | block_attribute_null, $22 | block_attribute_3,    $19 | block_attribute_null, $23 | block_attribute_3    ;13
	.BYTE $19 | block_attribute_null, $23 | block_attribute_3,    $19 | block_attribute_null, $23 | block_attribute_3    ;14
	.BYTE $19 | block_attribute_null, $23 | block_attribute_3,    $19 | block_attribute_null, $24 | block_attribute_3    ;15
	.BYTE $19 | block_attribute_null, $1F | block_attribute_3,    $19 | block_attribute_null, $1F | block_attribute_3    ;16
	.BYTE $19 | block_attribute_null, $19 | block_attribute_null, $1F | block_attribute_3,    $18 | block_attribute_null ;17
	.BYTE $19 | block_attribute_null, $1F | block_attribute_3,    $19 | block_attribute_null, $22 | block_attribute_3    ;18
	.BYTE $19 | block_attribute_null, $24 | block_attribute_3,    $19 | block_attribute_null, $1F | block_attribute_3    ;19
	.BYTE $19 | block_attribute_null, $22 | block_attribute_3,    $19 | block_attribute_null, $24 | block_attribute_3    ;1A
	.BYTE $19 | block_attribute_null, $22 | block_attribute_3,    $19 | block_attribute_null, $23 | block_attribute_3    ;1B
	.BYTE $19 | block_attribute_null, $23 | block_attribute_3,    $19 | block_attribute_null, $23 | block_attribute_3    ;1C
	.BYTE $19 | block_attribute_null, $23 | block_attribute_3,    $19 | block_attribute_null, $24 | block_attribute_3    ;1D
	.BYTE $19 | block_attribute_null, $1F | block_attribute_3,    $19 | block_attribute_null, $1F | block_attribute_3    ;1E
	.BYTE $1F | block_attribute_3,    $18 | block_attribute_null, $19 | block_attribute_null, $19 | block_attribute_null ;1F
	.BYTE $1F | block_attribute_3,    $18 | block_attribute_null, $22 | block_attribute_3,    $18 | block_attribute_null ;20
	.BYTE $24 | block_attribute_3,    $18 | block_attribute_null, $1F | block_attribute_3,    $18 | block_attribute_null ;21
	.BYTE $22 | block_attribute_3,    $18 | block_attribute_null, $24 | block_attribute_3,    $18 | block_attribute_null ;22
	.BYTE $22 | block_attribute_3,    $18 | block_attribute_null, $23 | block_attribute_3,    $18 | block_attribute_null ;23
	.BYTE $23 | block_attribute_3,    $18 | block_attribute_null, $23 | block_attribute_3,    $18 | block_attribute_null ;24
	.BYTE $23 | block_attribute_3,    $18 | block_attribute_null, $24 | block_attribute_3,    $18 | block_attribute_null ;25
	.BYTE $1F | block_attribute_3,    $18 | block_attribute_null, $1F | block_attribute_3,    $18 | block_attribute_null ;26
	.BYTE $19 | block_attribute_null, $19 | block_attribute_null, $19 | block_attribute_null, $1F | block_attribute_3    ;27
	.BYTE $1F | block_attribute_3,    $18 | block_attribute_null, $22 | block_attribute_3,    $18 | block_attribute_null ;28
	.BYTE $24 | block_attribute_3,    $18 | block_attribute_null, $1F | block_attribute_3,    $18 | block_attribute_null ;29
	.BYTE $22 | block_attribute_3,    $18 | block_attribute_null, $24 | block_attribute_3,    $18 | block_attribute_null ;2A
	.BYTE $22 | block_attribute_3,    $18 | block_attribute_null, $23 | block_attribute_3,    $18 | block_attribute_null ;2B
	.BYTE $23 | block_attribute_3,    $18 | block_attribute_null, $23 | block_attribute_3,    $18 | block_attribute_null ;2C
	.BYTE $23 | block_attribute_3,    $18 | block_attribute_null, $24 | block_attribute_3,    $18 | block_attribute_null ;2D
	.BYTE $1F | block_attribute_3,    $18 | block_attribute_null, $1F | block_attribute_3,    $18 | block_attribute_null ;2E
	.BYTE $19 | block_attribute_null, $19 | block_attribute_null, $19 | block_attribute_null, $1F | block_attribute_3    ;2F
	.BYTE $1F | block_attribute_3,    $18 | block_attribute_null, $22 | block_attribute_3,    $18 | block_attribute_null ;30
	.BYTE $24 | block_attribute_3,    $18 | block_attribute_null, $1F | block_attribute_3,    $18 | block_attribute_null ;31
	.BYTE $22 | block_attribute_3,    $18 | block_attribute_null, $24 | block_attribute_3,    $18 | block_attribute_null ;32
	.BYTE $22 | block_attribute_3,    $18 | block_attribute_null, $23 | block_attribute_3,    $18 | block_attribute_null ;33
	.BYTE $23 | block_attribute_3,    $18 | block_attribute_null, $23 | block_attribute_3,    $18 | block_attribute_null ;34
	.BYTE $23 | block_attribute_3,    $18 | block_attribute_null, $24 | block_attribute_3,    $18 | block_attribute_null ;35
	.BYTE $1F | block_attribute_3,    $18 | block_attribute_null, $1F | block_attribute_3,    $18 | block_attribute_null ;36
	.BYTE $19 | block_attribute_null, $1F | block_attribute_3,    $19 | block_attribute_null, $19 | block_attribute_null ;37
	.BYTE $2A | block_attribute_3,    $2C | block_attribute_3,    $18 | block_attribute_null, $19 | block_attribute_null ;38
	.BYTE $18 | block_attribute_null, $19 | block_attribute_null, $2A | block_attribute_3,    $2C | block_attribute_3    ;39
	.BYTE $22 | block_attribute_3,    $18 | block_attribute_null, $24 | block_attribute_3,    $1F | block_attribute_3    ;3A
	.BYTE $1F | block_attribute_3,    $18 | block_attribute_null, $2A | block_attribute_3,    $2C | block_attribute_3    ;3B
	.BYTE $22 | block_attribute_3,    $1F | block_attribute_3,    $24 | block_attribute_3,    $18 | block_attribute_null ;3C
	.BYTE $2A | block_attribute_3,    $2C | block_attribute_3,    $1F | block_attribute_3,    $18 | block_attribute_null ;3D
	.BYTE $19 | block_attribute_null, $1F | block_attribute_3,    $19 | block_attribute_null, $19 | block_attribute_null ;3E
	.BYTE $19 | block_attribute_null, $19 | block_attribute_null, $1F | block_attribute_3,    $18 | block_attribute_null ;3F
	.BYTE $19 | block_attribute_null, $19 | block_attribute_null, $09 | block_attribute_wall, $0A | block_attribute_wall ;40
	.BYTE $18 | block_attribute_null, $19 | block_attribute_null, $08 | block_attribute_null, $08 | block_attribute_null ;41
	.BYTE $19 | block_attribute_null, $19 | block_attribute_null, $1F | block_attribute_3,    $2A | block_attribute_3    ;42
	.BYTE $19 | block_attribute_null, $19 | block_attribute_null, $1F | block_attribute_3,    $2A | block_attribute_3    ;43
	.BYTE $19 | block_attribute_null, $19 | block_attribute_null, $1F | block_attribute_3,    $2A | block_attribute_3    ;44
	.BYTE $1F | block_attribute_3,    $2A | block_attribute_3,    $19 | block_attribute_null, $19 | block_attribute_null ;45
	.BYTE $1F | block_attribute_3,    $2A | block_attribute_3,    $19 | block_attribute_null, $19 | block_attribute_null ;46
	.BYTE $1F | block_attribute_3,    $2A | block_attribute_3,    $19 | block_attribute_null, $19 | block_attribute_null ;47
	.BYTE $19 | block_attribute_null, $19 | block_attribute_null, $09 | block_attribute_wall, $09 | block_attribute_wall ;48
	.BYTE $07 | block_attribute_wall, $0C | block_attribute_wall, $07 | block_attribute_wall, $0D | block_attribute_wall ;49
	.BYTE $19 | block_attribute_null, $19 | block_attribute_null, $2C | block_attribute_3,    $1F | block_attribute_3    ;4A
	.BYTE $19 | block_attribute_null, $19 | block_attribute_null, $2C | block_attribute_3,    $1F | block_attribute_3    ;4B
	.BYTE $19 | block_attribute_null, $19 | block_attribute_null, $2C | block_attribute_3,    $1F | block_attribute_3    ;4C
	.BYTE $2C | block_attribute_3,    $1F | block_attribute_3,    $19 | block_attribute_null, $19 | block_attribute_null ;4D
	.BYTE $2C | block_attribute_3,    $1F | block_attribute_3,    $19 | block_attribute_null, $19 | block_attribute_null ;4E
	.BYTE $2C | block_attribute_3,    $1F | block_attribute_3,    $19 | block_attribute_null, $19 | block_attribute_null ;4F
	.BYTE $0E | block_attribute_wall, $0B | block_attribute_wall, $0F | block_attribute_wall, $0B | block_attribute_wall ;50
	.BYTE $19 | block_attribute_null, $19 | block_attribute_null, $08 | block_attribute_null, $08 | block_attribute_null ;51
	.BYTE $19 | block_attribute_null, $19 | block_attribute_null, $2A | block_attribute_3,    $2C | block_attribute_3    ;52
	.BYTE $19 | block_attribute_null, $19 | block_attribute_null, $2A | block_attribute_3,    $2C | block_attribute_3    ;53
	.BYTE $19 | block_attribute_null, $19 | block_attribute_null, $2A | block_attribute_3,    $2C | block_attribute_3    ;54
	.BYTE $2A | block_attribute_3,    $2C | block_attribute_3,    $19 | block_attribute_null, $19 | block_attribute_null ;55
	.BYTE $2A | block_attribute_3,    $2C | block_attribute_3,    $19 | block_attribute_null, $19 | block_attribute_null ;56
	.BYTE $2A | block_attribute_3,    $2C | block_attribute_3,    $19 | block_attribute_null, $19 | block_attribute_null ;57
	.BYTE $22 | block_attribute_3,    $18 | block_attribute_null, $24 | block_attribute_3,    $1B | block_attribute_null ;58
	.BYTE $19 | block_attribute_null, $19 | block_attribute_null, $1C | block_attribute_null, $1C | block_attribute_null ;59
	.BYTE $19 | block_attribute_null, $19 | block_attribute_null, $2A | block_attribute_3,    $2B | block_attribute_3    ;5A
	.BYTE $19 | block_attribute_null, $19 | block_attribute_null, $2A | block_attribute_3,    $2B | block_attribute_3    ;5B
	.BYTE $19 | block_attribute_null, $19 | block_attribute_null, $2A | block_attribute_3,    $2B | block_attribute_3    ;5C
	.BYTE $2A | block_attribute_3,    $2B | block_attribute_3,    $19 | block_attribute_null, $19 | block_attribute_null ;5D
	.BYTE $2A | block_attribute_3,    $2B | block_attribute_3,    $19 | block_attribute_null, $19 | block_attribute_null ;5E
	.BYTE $2A | block_attribute_3,    $2B | block_attribute_3,    $19 | block_attribute_null, $19 | block_attribute_null ;5F
	.BYTE $24 | block_attribute_3,    $1B | block_attribute_null, $1F | block_attribute_3,    $18 | block_attribute_null ;60
	.BYTE $1C | block_attribute_null, $1C | block_attribute_null, $19 | block_attribute_null, $19 | block_attribute_null ;61
	.BYTE $19 | block_attribute_null, $19 | block_attribute_null, $2B | block_attribute_3,    $2B | block_attribute_3    ;62
	.BYTE $19 | block_attribute_null, $19 | block_attribute_null, $2B | block_attribute_3,    $2B | block_attribute_3    ;63
	.BYTE $19 | block_attribute_null, $19 | block_attribute_null, $2B | block_attribute_3,    $2B | block_attribute_3    ;64
	.BYTE $2B | block_attribute_3,    $2B | block_attribute_3,    $19 | block_attribute_null, $19 | block_attribute_null ;65
	.BYTE $2B | block_attribute_3,    $2B | block_attribute_3,    $19 | block_attribute_null, $19 | block_attribute_null ;66
	.BYTE $2B | block_attribute_3,    $2B | block_attribute_3,    $19 | block_attribute_null, $19 | block_attribute_null ;67
	.BYTE $19 | block_attribute_null, $24 | block_attribute_3,    $1C | block_attribute_null, $1F | block_attribute_3    ;68
	.BYTE $18 | block_attribute_null, $19 | block_attribute_null, $1B | block_attribute_null, $1C | block_attribute_null ;69
	.BYTE $19 | block_attribute_null, $19 | block_attribute_null, $2B | block_attribute_3,    $2C | block_attribute_3    ;6A
	.BYTE $19 | block_attribute_null, $19 | block_attribute_null, $2B | block_attribute_3,    $2C | block_attribute_3    ;6B
	.BYTE $19 | block_attribute_null, $19 | block_attribute_null, $2B | block_attribute_3,    $2C | block_attribute_3    ;6C
	.BYTE $2B | block_attribute_3,    $2C | block_attribute_3,    $19 | block_attribute_null, $19 | block_attribute_null ;6D
	.BYTE $2B | block_attribute_3,    $2C | block_attribute_3,    $19 | block_attribute_null, $19 | block_attribute_null ;6E
	.BYTE $2B | block_attribute_3,    $2C | block_attribute_3,    $19 | block_attribute_null, $19 | block_attribute_null ;6F
	.BYTE $1C | block_attribute_null, $22 | block_attribute_3,    $1C | block_attribute_null, $24 | block_attribute_3    ;70
	.BYTE $1B | block_attribute_null, $1C | block_attribute_null, $18 | block_attribute_null, $19 | block_attribute_null ;71
	.BYTE $19 | block_attribute_null, $19 | block_attribute_null, $1F | block_attribute_3,    $1F | block_attribute_3    ;72
	.BYTE $19 | block_attribute_null, $19 | block_attribute_null, $1F | block_attribute_3,    $1F | block_attribute_3    ;73
	.BYTE $19 | block_attribute_null, $19 | block_attribute_null, $1F | block_attribute_3,    $1F | block_attribute_3    ;74
	.BYTE $1F | block_attribute_3,    $1F | block_attribute_3,    $19 | block_attribute_null, $19 | block_attribute_null ;75
	.BYTE $1F | block_attribute_3,    $1F | block_attribute_3,    $19 | block_attribute_null, $19 | block_attribute_null ;76
	.BYTE $1F | block_attribute_3,    $1F | block_attribute_3,    $19 | block_attribute_null, $19 | block_attribute_null ;77
	.BYTE $1F | block_attribute_3,    $22 | block_attribute_3,    $19 | block_attribute_null, $23 | block_attribute_3    ;78
	.BYTE $19 | block_attribute_null, $1F | block_attribute_3,    $2A | block_attribute_3,    $2C | block_attribute_3    ;79
	.BYTE $18 | block_attribute_null, $19 | block_attribute_null, $1F | block_attribute_3,    $19 | block_attribute_null ;7A
	.BYTE $1F | block_attribute_3,    $19 | block_attribute_null, $18 | block_attribute_null, $19 | block_attribute_null ;7B
	.BYTE $2A | block_attribute_3,    $2C | block_attribute_3,    $19 | block_attribute_null, $1F | block_attribute_3    ;7C
	.BYTE $18 | block_attribute_null, $1E | block_attribute_null, $18 | block_attribute_null, $1E | block_attribute_null ;7D
	.BYTE $2B | block_attribute_3,    $2C | block_attribute_3,    $19 | block_attribute_null, $1F | block_attribute_3    ;7E
	.BYTE $19 | block_attribute_null, $1F | block_attribute_3,    $2B | block_attribute_3,    $2C | block_attribute_3    ;7F
	.BYTE $00 | block_attribute_null, $00 | block_attribute_wall, $00 | block_attribute_null, $00 | block_attribute_wall ;80
	.BYTE $24 | block_attribute_wall, $26 | block_attribute_wall, $25 | block_attribute_wall, $27 | block_attribute_wall ;81
	.BYTE $24 | block_attribute_wall, $27 | block_attribute_wall, $25 | block_attribute_wall, $26 | block_attribute_wall ;82
	.BYTE $24 | block_attribute_wall, $27 | block_attribute_wall, $21 | block_attribute_wall, $23 | block_attribute_wall ;83
	.BYTE $20 | block_attribute_wall, $22 | block_attribute_wall, $25 | block_attribute_wall, $26 | block_attribute_wall ;84
	.BYTE $24 | block_attribute_wall, $26 | block_attribute_wall, $21 | block_attribute_wall, $23 | block_attribute_wall ;85
	.BYTE $20 | block_attribute_wall, $22 | block_attribute_wall, $25 | block_attribute_wall, $27 | block_attribute_wall ;86
	.BYTE $28 | block_attribute_null, $28 | block_attribute_null, $28 | block_attribute_null, $28 | block_attribute_null ;87
	.BYTE $2A | block_attribute_null, $2A | block_attribute_null, $2A | block_attribute_null, $2A | block_attribute_null ;88
	.BYTE $29 | block_attribute_null, $2A | block_attribute_null, $29 | block_attribute_null, $2A | block_attribute_null ;89
	.BYTE $2A | block_attribute_null, $2A | block_attribute_null, $2A | block_attribute_null, $25 | block_attribute_wall ;8A
	.BYTE $2A | block_attribute_null, $24 | block_attribute_wall, $2A | block_attribute_null, $25 | block_attribute_wall ;8B
	.BYTE $26 | block_attribute_wall, $29 | block_attribute_null, $27 | block_attribute_wall, $29 | block_attribute_null ;8C
	.BYTE $29 | block_attribute_null, $2A | block_attribute_null, $27 | block_attribute_wall, $29 | block_attribute_null ;8D
	.BYTE $29 | block_attribute_null, $2A | block_attribute_null, $08 | block_attribute_null, $08 | block_attribute_null ;8E
	.BYTE $2A | block_attribute_null, $2A | block_attribute_null, $08 | block_attribute_null, $08 | block_attribute_null ;8F
	.BYTE $2A | block_attribute_null, $26 | block_attribute_wall, $25 | block_attribute_wall, $27 | block_attribute_wall ;90
	.BYTE $24 | block_attribute_wall, $29 | block_attribute_null, $25 | block_attribute_wall, $29 | block_attribute_null ;91
	.BYTE $2B | block_attribute_wall, $00 | block_attribute_null, $2B | block_attribute_wall, $00 | block_attribute_null ;92
	.BYTE $21 | block_attribute_wall, $23 | block_attribute_wall, $24 | block_attribute_wall, $27 | block_attribute_wall ;93
	.BYTE $25 | block_attribute_wall, $26 | block_attribute_wall, $20 | block_attribute_wall, $22 | block_attribute_wall ;94
	.BYTE $00 | block_attribute_null, $00 | block_attribute_null, $2C | block_attribute_null, $00 | block_attribute_null ;95
	.BYTE $00 | block_attribute_null, $2C | block_attribute_wall, $00 | block_attribute_null, $00 | block_attribute_wall ;96
	.BYTE $2C | block_attribute_null, $00 | block_attribute_wall, $00 | block_attribute_null, $00 | block_attribute_wall ;97
	.BYTE $05 | block_attribute_3,    $0E | block_attribute_wall, $17 | block_attribute_null, $0E | block_attribute_wall ;98
	.BYTE $17 | block_attribute_null, $0E | block_attribute_wall, $17 | block_attribute_null, $0E | block_attribute_wall ;99
	.BYTE $17 | block_attribute_null, $0E | block_attribute_wall, $17 | block_attribute_null, $05 | block_attribute_3    ;9A
	.BYTE $16 | block_attribute_null, $17 | block_attribute_null, $05 | block_attribute_3,    $05 | block_attribute_3    ;9B
	.BYTE $17 | block_attribute_null, $0E | block_attribute_wall, $05 | block_attribute_3,    $0E | block_attribute_wall ;9C
	.BYTE $17 | block_attribute_null, $05 | block_attribute_3,    $17 | block_attribute_null, $0E | block_attribute_wall ;9D
	.BYTE $38 | block_attribute_null, $3A | block_attribute_null, $39 | block_attribute_null, $3B | block_attribute_null ;9E
	.BYTE $17 | block_attribute_null, $2E | block_attribute_2,    $17 | block_attribute_null, $2E | block_attribute_2    ;9F
	.BYTE $19 | block_attribute_null, $20 | block_attribute_3,    $19 | block_attribute_null, $23 | block_attribute_3    ;A0
	.BYTE $28 | block_attribute_3,    $19 | block_attribute_null, $24 | block_attribute_3,    $19 | block_attribute_null ;A1
	.BYTE $1F | block_attribute_3,    $1B | block_attribute_null, $22 | block_attribute_3,    $1B | block_attribute_null ;A2
	.BYTE $1C | block_attribute_null, $1C | block_attribute_null, $1C | block_attribute_null, $1C | block_attribute_null ;A3
	.BYTE $00 | block_attribute_null, $06 | block_attribute_null, $09 | block_attribute_null, $07 | block_attribute_null ;A4
	.BYTE $17 | block_attribute_null, $17 | block_attribute_null, $08 | block_attribute_wall, $10 | block_attribute_wall ;A5
	.BYTE $00 | block_attribute_null, $00 | block_attribute_null, $00 | block_attribute_null, $00 | block_attribute_null ;A6
	.BYTE $01 | block_attribute_null, $01 | block_attribute_null, $05 | block_attribute_null, $01 | block_attribute_null ;A7
	.BYTE $01 | block_attribute_null, $01 | block_attribute_null, $01 | block_attribute_null, $01 | block_attribute_null ;A8
	.BYTE $01 | block_attribute_null, $01 | block_attribute_null, $01 | block_attribute_null, $02 | block_attribute_null ;A9
	.BYTE $01 | block_attribute_null, $03 | block_attribute_null, $01 | block_attribute_null, $03 | block_attribute_null ;AA
	.BYTE $01 | block_attribute_null, $04 | block_attribute_null, $01 | block_attribute_null, $01 | block_attribute_null ;AB
	.BYTE $01 | block_attribute_null, $01 | block_attribute_null, $08 | block_attribute_null, $08 | block_attribute_null ;AC
	.BYTE $09 | block_attribute_null, $09 | block_attribute_null, $01 | block_attribute_null, $01 | block_attribute_null ;AD
	.BYTE $01 | block_attribute_null, $01 | block_attribute_null, $08 | block_attribute_null, $05 | block_attribute_null ;AE
	.BYTE $00 | block_attribute_null, $06 | block_attribute_null, $00 | block_attribute_null, $06 | block_attribute_null ;AF
	.BYTE $09 | block_attribute_null, $07 | block_attribute_null, $01 | block_attribute_null, $01 | block_attribute_null ;B0
	.BYTE $02 | block_attribute_null, $08 | block_attribute_null, $03 | block_attribute_null, $00 | block_attribute_null ;B1
	.BYTE $03 | block_attribute_null, $00 | block_attribute_null, $03 | block_attribute_null, $00 | block_attribute_null ;B2
	.BYTE $04 | block_attribute_null, $09 | block_attribute_null, $01 | block_attribute_null, $01 | block_attribute_null ;B3
	.BYTE $08 | block_attribute_null, $08 | block_attribute_null, $00 | block_attribute_null, $00 | block_attribute_null ;B4
	.BYTE $05 | block_attribute_null, $01 | block_attribute_null, $06 | block_attribute_null, $01 | block_attribute_null ;B5
	.BYTE $06 | block_attribute_null, $01 | block_attribute_null, $06 | block_attribute_null, $01 | block_attribute_null ;B6
	.BYTE $07 | block_attribute_null, $01 | block_attribute_null, $01 | block_attribute_null, $01 | block_attribute_null ;B7
	.BYTE $0A | block_attribute_null, $0A | block_attribute_null, $0A | block_attribute_null, $0A | block_attribute_null ;B8
	.BYTE $0A | block_attribute_null, $0A | block_attribute_null, $0C | block_attribute_null, $0C | block_attribute_null ;B9
	.BYTE $0A | block_attribute_null, $0B | block_attribute_null, $0A | block_attribute_null, $0B | block_attribute_null ;BA
	.BYTE $0A | block_attribute_null, $0B | block_attribute_null, $0C | block_attribute_null, $0D | block_attribute_null ;BB
	.BYTE $01 | block_attribute_null, $02 | block_attribute_null, $01 | block_attribute_null, $03 | block_attribute_null ;BC
	.BYTE $01 | block_attribute_null, $03 | block_attribute_null, $01 | block_attribute_null, $04 | block_attribute_null ;BD
	.BYTE $00 | block_attribute_null, $00 | block_attribute_null, $09 | block_attribute_null, $09 | block_attribute_null ;BE
	.BYTE $06 | block_attribute_null, $01 | block_attribute_null, $07 | block_attribute_null, $01 | block_attribute_null ;BF
	.BYTE $01 | block_attribute_null, $01 | block_attribute_null, $01 | block_attribute_null, $01 | block_attribute_null ;C0
	.BYTE $03 | block_attribute_null, $04 | block_attribute_null, $01 | block_attribute_null, $05 | block_attribute_null ;C1
	.BYTE $01 | block_attribute_null, $06 | block_attribute_null, $01 | block_attribute_null, $07 | block_attribute_null ;C2
	.BYTE $08 | block_attribute_null, $09 | block_attribute_null, $0A | block_attribute_null, $0B | block_attribute_null ;C3
	.BYTE $16 | block_attribute_null, $18 | block_attribute_null, $17 | block_attribute_null, $0F | block_attribute_null ;C4
	.BYTE $10 | block_attribute_null, $0C | block_attribute_null, $11 | block_attribute_null, $0D | block_attribute_null ;C5
	.BYTE $12 | block_attribute_null, $0E | block_attribute_null, $13 | block_attribute_null, $0F | block_attribute_null ;C6
	.BYTE $14 | block_attribute_null, $0D | block_attribute_null, $15 | block_attribute_null, $0D | block_attribute_null ;C7
	.BYTE $19 | block_attribute_null, $20 | block_attribute_null, $19 | block_attribute_null, $21 | block_attribute_null ;C8
	.BYTE $1A | block_attribute_null, $22 | block_attribute_null, $1B | block_attribute_null, $23 | block_attribute_null ;C9
	.BYTE $1C | block_attribute_null, $1F | block_attribute_null, $1D | block_attribute_null, $1F | block_attribute_null ;CA
	.BYTE $1F | block_attribute_null, $24 | block_attribute_null, $1F | block_attribute_null, $25 | block_attribute_null ;CB
	.BYTE $1F | block_attribute_null, $26 | block_attribute_null, $1F | block_attribute_null, $24 | block_attribute_null ;CC
	.BYTE $1F | block_attribute_null, $24 | block_attribute_null, $1F | block_attribute_null, $24 | block_attribute_null ;CD
	.BYTE $27 | block_attribute_null, $2E | block_attribute_null, $28 | block_attribute_null, $2F | block_attribute_null ;CE
	.BYTE $29 | block_attribute_null, $31 | block_attribute_null, $2A | block_attribute_null, $31 | block_attribute_null ;CF
	.BYTE $25 | block_attribute_null, $26 | block_attribute_null, $2D | block_attribute_null, $27 | block_attribute_null ;D0
	.BYTE $26 | block_attribute_null, $26 | block_attribute_null, $27 | block_attribute_null, $27 | block_attribute_null ;D1
	.BYTE $25 | block_attribute_null, $26 | block_attribute_null, $08 | block_attribute_null, $08 | block_attribute_null ;D2
	.BYTE $26 | block_attribute_null, $26 | block_attribute_null, $08 | block_attribute_null, $08 | block_attribute_null ;D3
	.BYTE $2A | block_attribute_3,    $2C | block_attribute_3,    $2D | block_attribute_null, $27 | block_attribute_null ;D4
	.BYTE $25 | block_attribute_null, $26 | block_attribute_null, $27 | block_attribute_null, $27 | block_attribute_null ;D5
	.BYTE $1F | block_attribute_3,    $2A | block_attribute_3,    $27 | block_attribute_null, $27 | block_attribute_null ;D6
	.BYTE $2C | block_attribute_3,    $1F | block_attribute_3,    $27 | block_attribute_null, $27 | block_attribute_null ;D7
	.BYTE $25 | block_attribute_null, $26 | block_attribute_null, $2A | block_attribute_3,    $2C | block_attribute_3    ;D8
	.BYTE $26 | block_attribute_null, $26 | block_attribute_null, $2A | block_attribute_3,    $2B | block_attribute_3    ;D9
	.BYTE $26 | block_attribute_null, $26 | block_attribute_null, $2C | block_attribute_3,    $1F | block_attribute_3    ;DA
	.BYTE $26 | block_attribute_null, $23 | block_attribute_3,    $1F | block_attribute_3,    $24 | block_attribute_3    ;DB
	.BYTE $26 | block_attribute_null, $26 | block_attribute_null, $2B | block_attribute_3,    $2C | block_attribute_3    ;DC
	.BYTE $26 | block_attribute_null, $26 | block_attribute_null, $27 | block_attribute_null, $22 | block_attribute_3    ;DD
	.BYTE $26 | block_attribute_null, $24 | block_attribute_3,    $27 | block_attribute_null, $27 | block_attribute_null ;DE
	.BYTE $26 | block_attribute_null, $26 | block_attribute_null, $27 | block_attribute_null, $22 | block_attribute_3    ;DF
	.BYTE $26 | block_attribute_null, $24 | block_attribute_3,    $22 | block_attribute_3,    $1F | block_attribute_3    ;E0
	.BYTE $24 | block_attribute_3,    $1B | block_attribute_null, $1F | block_attribute_3,    $1B | block_attribute_null ;E1
	.BYTE $2A | block_attribute_3,    $2B | block_attribute_3,    $27 | block_attribute_null, $22 | block_attribute_3    ;E2
	.BYTE $26 | block_attribute_null, $24 | block_attribute_3,    $22 | block_attribute_3,    $1F | block_attribute_3    ;E3
	.BYTE $24 | block_attribute_3,    $18 | block_attribute_null, $2A | block_attribute_3,    $2C | block_attribute_3    ;E4
	.BYTE $19 | block_attribute_null, $24 | block_attribute_3,    $2A | block_attribute_3,    $2B | block_attribute_3    ;E5
	.BYTE $18 | block_attribute_null, $1A | block_attribute_null, $2B | block_attribute_3,    $2C | block_attribute_3    ;E6
	.BYTE $2B | block_attribute_3,    $2C | block_attribute_3,    $18 | block_attribute_null, $22 | block_attribute_3    ;E7
	.BYTE $18 | block_attribute_null, $23 | block_attribute_3,    $18 | block_attribute_null, $23 | block_attribute_3    ;E8
	.BYTE $01 | block_attribute_null, $01 | block_attribute_null, $02 | block_attribute_null, $08 | block_attribute_null ;E9
	.BYTE $03 | block_attribute_null, $00 | block_attribute_null, $04 | block_attribute_null, $09 | block_attribute_null ;EA
	.BYTE $08 | block_attribute_null, $05 | block_attribute_null, $00 | block_attribute_null, $06 | block_attribute_null ;EB
	.BYTE $00 | block_attribute_null, $00 | block_attribute_null, $00 | block_attribute_null, $00 | block_attribute_null ;EC
	.BYTE $00 | block_attribute_null, $2C | block_attribute_null, $00 | block_attribute_null, $00 | block_attribute_null ;ED
	.BYTE $2C | block_attribute_null, $00 | block_attribute_null, $00 | block_attribute_null, $00 | block_attribute_null ;EE
	.BYTE $00 | block_attribute_null, $00 | block_attribute_null, $00 | block_attribute_null, $2C | block_attribute_null ;EF
	.BYTE $2B | block_attribute_null, $31 | block_attribute_null, $2C | block_attribute_null, $31 | block_attribute_null ;F0
	.BYTE $32 | block_attribute_null, $31 | block_attribute_null, $32 | block_attribute_null, $31 | block_attribute_null ;F1
	.BYTE $32 | block_attribute_null, $31 | block_attribute_null, $32 | block_attribute_null, $34 | block_attribute_null ;F2
	.BYTE $35 | block_attribute_null, $30 | block_attribute_null, $35 | block_attribute_null, $24 | block_attribute_null ;F3
	.BYTE $35 | block_attribute_null, $2E | block_attribute_null, $36 | block_attribute_null, $2F | block_attribute_null ;F4
	.BYTE $37 | block_attribute_null, $31 | block_attribute_null, $2F | block_attribute_null, $31 | block_attribute_null ;F5
	.BYTE $31 | block_attribute_null, $34 | block_attribute_null, $31 | block_attribute_null, $31 | block_attribute_null ;F6
	.BYTE $31 | block_attribute_null, $33 | block_attribute_null, $34 | block_attribute_null, $31 | block_attribute_null ;F7
	.BYTE $31 | block_attribute_null, $34 | block_attribute_null, $34 | block_attribute_null, $33 | block_attribute_null ;F8
	.BYTE $33 | block_attribute_null, $34 | block_attribute_null, $31 | block_attribute_null, $34 | block_attribute_null ;F9
	.BYTE $2E | block_attribute_null, $31 | block_attribute_null, $2F | block_attribute_null, $31 | block_attribute_null ;FA
	.BYTE $1E | block_attribute_null, $21 | block_attribute_null, $29 | block_attribute_null, $1F | block_attribute_null ;FB
	.BYTE $01 | block_attribute_null, $01 | block_attribute_null, $01 | block_attribute_null, $02 | block_attribute_null ;FC
	.BYTE $34 | block_attribute_null, $31 | block_attribute_null, $33 | block_attribute_null, $31 | block_attribute_null ;FD
	.BYTE $1E | block_attribute_null, $20 | block_attribute_null, $29 | block_attribute_null, $21 | block_attribute_null ;FE
	.BYTE $19 | block_attribute_null, $20 | block_attribute_null, $19 | block_attribute_null, $20 | block_attribute_null ;FF