.SEGMENT "BANK01"
.INCLUDE "constants/scrolling.asm"
.INCLUDE "constants/ppu_attributes.asm"
.INCLUDE "1/air_wily2_tsa.asm"
.INCLUDE "1/air_wily2_mapset.asm"
.INCBIN  "gfx/1/1.chr"
.INCLUDE "1/air_wily2_scrolling.asm"
.INCBIN  "1/1_p1.bin"
