.SEGMENT "BANK02"
.INCLUDE "constants/scrolling.asm"
.INCLUDE "constants/ppu_attributes.asm"
.INCLUDE "2/woodman_wily3_tsa.asm"
.INCLUDE "2/woodman_wily3_mapset.asm"
.INCBIN  "gfx/2/2.chr"
.INCLUDE "2/woodman_wily3_scrolling.asm"
.INCBIN  "2/2_p1.bin"
