.SEGMENT "BANK03"
.INCLUDE "constants/scrolling.asm"
.INCLUDE "constants/ppu_attributes.asm"
.INCLUDE "3/bubbleman_wily4_tsa.asm"
.INCLUDE "3/bubbleman_wily4_mapset.asm"
.INCBIN  "gfx/3/3.chr"
.INCLUDE "3/bubbleman_wily4_scrolling.asm"
.INCBIN  "3/3_p1.bin"
