.SEGMENT "BANK04"
.INCLUDE "constants/scrolling.asm"
.INCLUDE "constants/ppu_attributes.asm"
.INCLUDE "4/quickman_wily5_tsa.asm"
.INCLUDE "4/quickman_wily5_mapset.asm"
.INCBIN  "gfx/4/4.chr"
.INCLUDE "4/quickman_wily5_scrolling.asm"
.INCBIN  "4/4_p1.bin"
