.SEGMENT "BANK05"
.INCLUDE "constants/scrolling.asm"
.INCLUDE "constants/ppu_attributes.asm"
.INCLUDE "5/flashman_wily6_tsa.asm"
.INCLUDE "5/flashman_wily6_mapset.asm"
.INCBIN  "gfx/5/5.chr"
.INCLUDE "5/flashman_wily6_scrolling.asm"
.INCBIN  "5/5_p1.bin"
