.SEGMENT "BANK09"
.INCLUDE "constants/charmap.asm"
.INCBIN  "gfx/9/9_p0.chr"
.INCBIN  "9/9_0.bin"
.INCLUDE "screen/staff_roll_1.asm"
.INCBIN  "9/9_1.bin"
.INCLUDE "screen/staff_roll_2.asm"
.INCBIN  "gfx/9/9_p1.chr"
