.SEGMENT "BANK0C"
.INCLUDE "constants/audio.asm"
.INCLUDE "macros/audio.asm"
.INCBIN  "audio/engine.bin"
.INCBIN  "audio/pointers.bin"
.INCLUDE "audio/music/flashman.asm"
.INCLUDE "audio/music/woodman.asm"
.INCBIN  "audio/audio.bin"
