.SEGMENT "BANK0A"
.INCLUDE "constants/oam.asm"
.INCLUDE "sprites/pointers/oam_sprites_pointers.asm"
.INCBIN  "sprites/sprites_0.bin"
.INCLUDE "sprites/oam_sprites.asm"
.INCBIN  "sprites/sprites_1.bin"
