.SEGMENT "BANK0A"
.INCLUDE "constants/oam.asm"
.INCLUDE "sprites/pointers/oam_sprites_pointers.asm"
.INCLUDE "sprites/pointers/oamxcoord_index_pointers.asm"
.INCLUDE "sprites/oamxcoord_table.asm"
.INCLUDE "sprites/oam_sprites.asm"
.INCLUDE "sprites/oamxcoord_index.asm"
.INCLUDE "sprites/unused/unused.asm"
