enemies_hit_damage_table:
	.BYTE 2  ;objects_shrink
	.BYTE 2  ;objects_shrink_move
	.BYTE 2  ;objects_anko_release_shrink
	.BYTE 2  ;objects_m_445
	.BYTE 2  ;objects_m_445_move
	.BYTE 2  ;objects_m_445_remove
	.BYTE 4  ;objects_killed
	.BYTE 4  ;objects_claw
	.BYTE 4  ;objects_claw_move
	.BYTE 4  ;objects_claw_remove
	.BYTE 4  ;objects_tanishi
	.BYTE 4  ;objects_tanishi_no_shell_move
	.BYTE 4  ;objects_kerog
	.BYTE 1  ;objects_petit_kerog
	.BYTE 0  ;objects_bubble
	.BYTE 12 ;objects_anko_lamp
	.BYTE 12 ;objects_anko_eye_tail
	.BYTE 0  ;objects_anko_palette
	.BYTE 0  ;objects_lift
	.BYTE 0  ;objects_drop_platform
	.BYTE 0  ;objects_laser
	.BYTE 28 ;objects_laser_move
	.BYTE 4  ;objects_batton
	.BYTE 4  ;objects_robbit
	.BYTE 2  ;objects_carrot
	.BYTE 8  ;objects_friender_head
	.BYTE 8  ;objects_friender_tail
	.BYTE 4  ;objects_friender_fire_breath
	.BYTE 0  ;objects_friender
	.BYTE 4  ;objects_monking
	.BYTE 0  ;objects_kukku
	.BYTE 4  ;objects_kukku_move
	.BYTE 0  ;objects_kukku_remove
	.BYTE 0  ;objects_telly
	.BYTE 2  ;objects_telly_move
	.BYTE 8  ;objects_changkey_maker
	.BYTE 3  ;objects_changkey
	.BYTE 0  ;objects_light_to_dark
	.BYTE 0  ;objects_changkey_maker_light
	.BYTE 0  ;objects_dark_to_light
	.BYTE 0  ;objects_changkey_maker_killed_to_dark
	.BYTE 4  ;objects_pierrobot_jester
	.BYTE 4  ;objects_pierrobot
	.BYTE 0  ;objects_fly_boy
	.BYTE 4  ;objects_fly_boy_move
	.BYTE 0  ;objects_destroyed_block_2d
	.BYTE 0  ;objects_friender_block
	.BYTE 0  ;objects_shutter
	.BYTE 8  ;objects_press
	.BYTE 8  ;objects_blocky
	.BYTE 8  ;objects_blocky_move
	.BYTE 4  ;objects_blocky_apart
	.BYTE 4  ;objects_neo_metall
	.BYTE 2  ;objects_straight_bullet
	.BYTE 6  ;objects_matasaburo
	.BYTE 0  ;objects_pipi
	.BYTE 4  ;objects_pipi_move
	.BYTE 0  ;objects_pipi_remove
	.BYTE 4  ;objects_pipi_egg
	.BYTE 0  ;objects_pipi_egg_crack
	.BYTE 2  ;objects_copipi
	.BYTE 4  ;objects_kaminari_goro_move
	.BYTE 0  ;objects_kaminari_goro
	.BYTE 2  ;objects_lightning_bolt
	.BYTE 0  ;objects_goblin_1
	.BYTE 0  ;objects_goblin_2
	.BYTE 0  ;objects_goblin_1_palette
	.BYTE 0  ;objects_goblin_2_palette
	.BYTE 2  ;objects_goblin_horn
	.BYTE 2  ;objects_petit_goblin
	.BYTE 4  ;objects_springer
	.BYTE 0  ;objects_mole
	.BYTE 4  ;objects_mole_up
	.BYTE 4  ;objects_mole_down
	.BYTE 0  ;objects_mole_remove
	.BYTE 4  ;objects_shotman_left
	.BYTE 4  ;objects_shotman_right
	.BYTE 2  ;objects_shotman_shoot
	.BYTE 8  ;objects_sniper_armor
	.BYTE 4  ;objects_returning_sniper_joe
	.BYTE 2  ;objects_scworm_pipe
	.BYTE 2  ;objects_scworm
	.BYTE 8  ;objects_unknown_press
	.BYTE 0  ;objects_appearing_block_1
	.BYTE 0  ;objects_appearing_block_2
	.BYTE 0  ;objects_appearing_block_3
	.BYTE 10 ;objects_crashman_palette_swap
	.BYTE 0  ;objects_destroyed_block_57
	.BYTE 4  ;objects_heatman_atomic_fire
	.BYTE 4  ;objects_quickman_quick_boomerang
	.BYTE 2  ;objects_bubbleman_shoot
	.BYTE 4  ;objects_bubbleman_bubble_lead
	.BYTE 3  ;objects_metalman_metall_blade
	.BYTE 4  ;objects_airman_air_shooter
	.BYTE 4  ;objects_crashman_crash_bomber
	.BYTE 4  ;objects_crashman_crash_bomber_explosion
	.BYTE 0  ;objects_explosion
	.BYTE 8  ;objects_woodman_leaf_shield
	.BYTE 4  ;objects_woodman_leaf
	.BYTE 4  ;objects_mecha_dragon_block
	.BYTE 0  ;objects_mecha_dragon
	.BYTE 28 ;objects_mecha_dragon_wing
	.BYTE 28 ;objects_mecha_dragon_tail_head
	.BYTE 4  ;objects_mecha_dragon_beam
	.BYTE 6  ;objects_mecha_dragon_fireball
	.BYTE 4  ;objects_guts_tank_fist
	.BYTE 8  ;objects_picopico_kun_apart
	.BYTE 6  ;objects_large_bullet
	.BYTE 0  ;objects_wily_machine_2_cockpit_damage
	.BYTE 4  ;objects_boobeam_trap
	.BYTE 4  ;objects_boobeam_trap_shoot
	.BYTE 6  ;objects_alien_shot
	.BYTE 0  ;objects_alien_star
	.BYTE 10 ;objects_big_fish
	.BYTE 10 ;objects_red_liquid_1
	.BYTE 10 ;objects_red_liquid_2
	.BYTE 10 ;objects_red_liquid_drop
	.BYTE 0  ;objects_no_effect_large_life_capsule
	.BYTE 0  ;objects_large_life_capsule
	.BYTE 0  ;objects_small_life_capsule
	.BYTE 0  ;objects_large_weapon_capsule
	.BYTE 0  ;objects_small_weapon_capsule
	.BYTE 0  ;objects_e_tank
	.BYTE 0  ;objects_1up
