@mega_buster_damage_table:
	.BYTE $07 ;objects_shrink
	.BYTE $07 ;objects_shrink_move
	.BYTE $14 ;objects_anko_release_shrink
	.BYTE $14 ;objects_m_445
	.BYTE $14 ;objects_m_445_move
	.BYTE $14 ;objects_m_445_remove
	.BYTE $14 ;objects_killed
	.BYTE $14 ;objects_claw
	.BYTE $14 ;objects_claw_move
	.BYTE $14 ;objects_claw_remove
	.BYTE $0A ;objects_tanishi
	.BYTE $0A ;objects_tanishi_no_shell_move
	.BYTE $02 ;objects_kerog
	.BYTE $14 ;objects_petit_kerog
	.BYTE $14 ;objects_bubble
	.BYTE $02 ;objects_anko_lamp
	.BYTE $00 ;objects_anko_eye_tail
	.BYTE $00 ;objects_anko_palette
	.BYTE $00 ;objects_lift
	.BYTE $00 ;objects_drop_platform
	.BYTE $00 ;objects_laser
	.BYTE $00 ;objects_laser_move
	.BYTE $0A ;objects_batton
	.BYTE $02 ;objects_robbit
	.BYTE $00 ;objects_carrot
	.BYTE $01 ;objects_friender_head
	.BYTE $00 ;objects_friender_tail
	.BYTE $00 ;objects_friender_fire_breath
	.BYTE $00 ;objects_friender
	.BYTE $07 ;objects_monking
	.BYTE $00 ;objects_kukku
	.BYTE $02 ;objects_kukku_move
	.BYTE $00 ;objects_kukku_remove
	.BYTE $00 ;objects_telly
	.BYTE $14 ;objects_telly_move
	.BYTE $02 ;objects_changkey_maker
	.BYTE $00 ;objects_changkey
	.BYTE $00 ;objects_light_to_dark
	.BYTE $00 ;objects_changkey_maker_light
	.BYTE $00 ;objects_dark_to_light
	.BYTE $00 ;objects_changkey_maker_killed_to_dark
	.BYTE $06 ;objects_pierrobot_jester
	.BYTE $14 ;objects_pierrobot
	.BYTE $00 ;objects_fly_boy
	.BYTE $04 ;objects_fly_boy_move
	.BYTE $00 ;objects_destroyed_block_2d
	.BYTE $00 ;objects_friender_block
	.BYTE $00 ;objects_shutter
	.BYTE $00 ;objects_press
	.BYTE $0A ;objects_blocky
	.BYTE $00 ;objects_blocky_move
	.BYTE $00 ;objects_blocky_apart
	.BYTE $14 ;objects_neo_metall
	.BYTE $00 ;objects_straight_bullet
	.BYTE $04 ;objects_matasaburo
	.BYTE $00 ;objects_pipi
	.BYTE $14 ;objects_pipi_move
	.BYTE $00 ;objects_pipi_remove
	.BYTE $14 ;objects_pipi_egg
	.BYTE $00 ;objects_pipi_egg_crack
	.BYTE $14 ;objects_copipi
	.BYTE $07 ;objects_kaminari_goro_move
	.BYTE $00 ;objects_kaminari_goro
	.BYTE $00 ;objects_lightning_bolt
	.BYTE $00 ;objects_goblin_1
	.BYTE $00 ;objects_goblin_2
	.BYTE $00 ;objects_goblin_1_palette
	.BYTE $00 ;objects_goblin_2_palette
	.BYTE $00 ;objects_goblin_horn
	.BYTE $14 ;objects_petit_goblin
	.BYTE $00 ;objects_springer
	.BYTE $00 ;objects_mole
	.BYTE $04 ;objects_mole_up
	.BYTE $04 ;objects_mole_down
	.BYTE $00 ;objects_mole_remove
	.BYTE $04 ;objects_shotman_left
	.BYTE $04 ;objects_shotman_right
	.BYTE $00 ;objects_shotman_shoot
	.BYTE $01 ;objects_sniper_armor
	.BYTE $02 ;objects_returning_sniper_joe
	.BYTE $04 ;objects_scworm_pipe
	.BYTE $04 ;objects_scworm
	.BYTE $00 ;objects_unknown_press
	.BYTE $00 ;objects_appearing_block_1
	.BYTE $00 ;objects_appearing_block_2
	.BYTE $00 ;objects_appearing_block_3
	.BYTE $00 ;objects_crashman_palette_swap
	.BYTE $00 ;objects_destroyed_block_57
	.BYTE $00 ;objects_heatman_atomic_fire
	.BYTE $00 ;objects_quickman_quick_boomerang
	.BYTE $00 ;objects_bubbleman_shoot
	.BYTE $00 ;objects_bubbleman_bubble_lead
	.BYTE $00 ;objects_metalman_metall_blade
	.BYTE $00 ;objects_airman_air_shooter
	.BYTE $00 ;objects_crashman_crash_bomber
	.BYTE $00 ;objects_crashman_crash_bomber_explosion
	.BYTE $00 ;objects_explosion
	.BYTE $00 ;objects_woodman_leaf_shield
	.BYTE $00 ;objects_woodman_leaf
	.BYTE $00 ;objects_mecha_dragon_block
	.BYTE $00 ;objects_mecha_dragon
	.BYTE $00 ;objects_mecha_dragon_wing
	.BYTE $00 ;objects_mecha_dragon_tail_head
	.BYTE $00 ;objects_mecha_dragon_beam
	.BYTE $00 ;objects_mecha_dragon_fireball
	.BYTE $00 ;objects_guts_tank_fist
	.BYTE $07 ;objects_picopico_kun_apart
	.BYTE $00 ;objects_large_bullet
	.BYTE $00 ;objects_wily_machine_2_cockpit_damage
	.BYTE $00 ;objects_boobeam_trap
	.BYTE $00 ;objects_boobeam_trap_shoot
	.BYTE $00 ;objects_alien_shot
	.BYTE $00 ;objects_alien_star
	.BYTE $00 ;objects_big_fish
	.BYTE $00 ;objects_red_liquid_1
	.BYTE $00 ;objects_red_liquid_2
	.BYTE $00 ;objects_red_liquid_drop
	.BYTE $00 ;objects_no_effect_large_life_capsule
	.BYTE $00 ;objects_large_life_capsule
	.BYTE $00 ;objects_small_life_capsule
	.BYTE $00 ;objects_large_weapon_capsule
	.BYTE $00 ;objects_small_weapon_capsule
	.BYTE $00 ;objects_e_tank
	.BYTE $00 ;objects_1up

@atomic_fire_damage_table:
	.BYTE $14 ;objects_shrink
	.BYTE $14 ;objects_shrink_move
	.BYTE $00 ;objects_anko_release_shrink
	.BYTE $00 ;objects_m_445
	.BYTE $14 ;objects_m_445_move
	.BYTE $00 ;objects_m_445_remove
	.BYTE $14 ;objects_killed
	.BYTE $00 ;objects_claw
	.BYTE $14 ;objects_claw_move
	.BYTE $00 ;objects_claw_remove
	.BYTE $14 ;objects_tanishi
	.BYTE $14 ;objects_tanishi_no_shell_move
	.BYTE $14 ;objects_kerog
	.BYTE $14 ;objects_petit_kerog
	.BYTE $00 ;objects_bubble
	.BYTE $14 ;objects_anko_lamp
	.BYTE $00 ;objects_anko_eye_tail
	.BYTE $00 ;objects_anko_palette
	.BYTE $00 ;objects_lift
	.BYTE $00 ;objects_drop_platform
	.BYTE $00 ;objects_laser
	.BYTE $00 ;objects_laser_move
	.BYTE $14 ;objects_batton
	.BYTE $14 ;objects_robbit
	.BYTE $00 ;objects_carrot
	.BYTE $14 ;objects_friender_head
	.BYTE $00 ;objects_friender_tail
	.BYTE $00 ;objects_friender_fire_breath
	.BYTE $00 ;objects_friender
	.BYTE $14 ;objects_monking
	.BYTE $00 ;objects_kukku
	.BYTE $14 ;objects_kukku_move
	.BYTE $00 ;objects_kukku_remove
	.BYTE $00 ;objects_telly
	.BYTE $14 ;objects_telly_move
	.BYTE $00 ;objects_changkey_maker
	.BYTE $00 ;objects_changkey
	.BYTE $00 ;objects_light_to_dark
	.BYTE $00 ;objects_changkey_maker_light
	.BYTE $00 ;objects_dark_to_light
	.BYTE $00 ;objects_changkey_maker_killed_to_dark
	.BYTE $14 ;objects_pierrobot_jester
	.BYTE $14 ;objects_pierrobot
	.BYTE $00 ;objects_fly_boy
	.BYTE $14 ;objects_fly_boy_move
	.BYTE $00 ;objects_destroyed_block_2d
	.BYTE $00 ;objects_friender_block
	.BYTE $00 ;objects_shutter
	.BYTE $00 ;objects_press
	.BYTE $14 ;objects_blocky
	.BYTE $00 ;objects_blocky_move
	.BYTE $00 ;objects_blocky_apart
	.BYTE $14 ;objects_neo_metall
	.BYTE $14 ;objects_straight_bullet
	.BYTE $00 ;objects_matasaburo
	.BYTE $00 ;objects_pipi
	.BYTE $14 ;objects_pipi_move
	.BYTE $00 ;objects_pipi_remove
	.BYTE $14 ;objects_pipi_egg
	.BYTE $14 ;objects_pipi_egg_crack
	.BYTE $14 ;objects_copipi
	.BYTE $00 ;objects_kaminari_goro_move
	.BYTE $00 ;objects_kaminari_goro
	.BYTE $00 ;objects_lightning_bolt
	.BYTE $00 ;objects_goblin_1
	.BYTE $00 ;objects_goblin_2
	.BYTE $00 ;objects_goblin_1_palette
	.BYTE $00 ;objects_goblin_2_palette
	.BYTE $00 ;objects_goblin_horn
	.BYTE $14 ;objects_petit_goblin
	.BYTE $14 ;objects_springer
	.BYTE $00 ;objects_mole
	.BYTE $14 ;objects_mole_up
	.BYTE $14 ;objects_mole_down
	.BYTE $00 ;objects_mole_remove
	.BYTE $14 ;objects_shotman_left
	.BYTE $14 ;objects_shotman_right
	.BYTE $00 ;objects_shotman_shoot
	.BYTE $14 ;objects_sniper_armor
	.BYTE $14 ;objects_returning_sniper_joe
	.BYTE $14 ;objects_scworm_pipe
	.BYTE $14 ;objects_scworm
	.BYTE $00 ;objects_unknown_press
	.BYTE $00 ;objects_appearing_block_1
	.BYTE $00 ;objects_appearing_block_2
	.BYTE $00 ;objects_appearing_block_3
	.BYTE $00 ;objects_crashman_palette_swap
	.BYTE $00 ;objects_destroyed_block_57
	.BYTE $00 ;objects_heatman_atomic_fire
	.BYTE $00 ;objects_quickman_quick_boomerang
	.BYTE $00 ;objects_bubbleman_shoot
	.BYTE $00 ;objects_bubbleman_bubble_lead
	.BYTE $00 ;objects_metalman_metall_blade
	.BYTE $00 ;objects_airman_air_shooter
	.BYTE $00 ;objects_crashman_crash_bomber
	.BYTE $00 ;objects_crashman_crash_bomber_explosion
	.BYTE $00 ;objects_explosion
	.BYTE $00 ;objects_woodman_leaf_shield
	.BYTE $00 ;objects_woodman_leaf
	.BYTE $00 ;objects_mecha_dragon_block
	.BYTE $00 ;objects_mecha_dragon
	.BYTE $00 ;objects_mecha_dragon_wing
	.BYTE $00 ;objects_mecha_dragon_tail_head
	.BYTE $00 ;objects_mecha_dragon_beam
	.BYTE $00 ;objects_mecha_dragon_fireball
	.BYTE $00 ;objects_guts_tank_fist
	.BYTE $14 ;objects_picopico_kun_apart
	.BYTE $00 ;objects_large_bullet
	.BYTE $00 ;objects_wily_machine_2_cockpit_damage
	.BYTE $00 ;objects_boobeam_trap
	.BYTE $00 ;objects_boobeam_trap_shoot
	.BYTE $00 ;objects_alien_shot
	.BYTE $00 ;objects_alien_star
	.BYTE $00 ;objects_big_fish
	.BYTE $00 ;objects_red_liquid_1
	.BYTE $00 ;objects_red_liquid_2
	.BYTE $00 ;objects_red_liquid_drop
	.BYTE $00 ;objects_no_effect_large_life_capsule
	.BYTE $00 ;objects_large_life_capsule
	.BYTE $00 ;objects_small_life_capsule

@air_shooter_damage_table:
	.BYTE $00 ;objects_shrink
	.BYTE $00 ;objects_shrink_move
	.BYTE $00 ;objects_anko_release_shrink
	.BYTE $00 ;objects_m_445
	.BYTE $14 ;objects_m_445_move
	.BYTE $00 ;objects_m_445_remove
	.BYTE $14 ;objects_killed
	.BYTE $00 ;objects_claw
	.BYTE $14 ;objects_claw_move
	.BYTE $00 ;objects_claw_remove
	.BYTE $00 ;objects_tanishi
	.BYTE $14 ;objects_tanishi_no_shell_move
	.BYTE $00 ;objects_kerog
	.BYTE $14 ;objects_petit_kerog
	.BYTE $00 ;objects_bubble
	.BYTE $00 ;objects_anko_lamp
	.BYTE $00 ;objects_anko_eye_tail
	.BYTE $00 ;objects_anko_palette
	.BYTE $00 ;objects_lift
	.BYTE $00 ;objects_drop_platform
	.BYTE $00 ;objects_laser
	.BYTE $00 ;objects_laser_move
	.BYTE $14 ;objects_batton
	.BYTE $00 ;objects_robbit
	.BYTE $00 ;objects_carrot
	.BYTE $00 ;objects_friender_head
	.BYTE $00 ;objects_friender_tail
	.BYTE $00 ;objects_friender_fire_breath
	.BYTE $00 ;objects_friender
	.BYTE $00 ;objects_monking
	.BYTE $00 ;objects_kukku
	.BYTE $00 ;objects_kukku_move
	.BYTE $00 ;objects_kukku_remove
	.BYTE $00 ;objects_telly
	.BYTE $14 ;objects_telly_move
	.BYTE $14 ;objects_changkey_maker
	.BYTE $00 ;objects_changkey
	.BYTE $00 ;objects_light_to_dark
	.BYTE $00 ;objects_changkey_maker_light
	.BYTE $00 ;objects_dark_to_light
	.BYTE $00 ;objects_changkey_maker_killed_to_dark
	.BYTE $00 ;objects_pierrobot_jester
	.BYTE $14 ;objects_pierrobot
	.BYTE $00 ;objects_fly_boy
	.BYTE $14 ;objects_fly_boy_move
	.BYTE $00 ;objects_destroyed_block_2d
	.BYTE $00 ;objects_friender_block
	.BYTE $00 ;objects_shutter
	.BYTE $00 ;objects_press
	.BYTE $00 ;objects_blocky
	.BYTE $00 ;objects_blocky_move
	.BYTE $00 ;objects_blocky_apart
	.BYTE $00 ;objects_neo_metall
	.BYTE $00 ;objects_straight_bullet
	.BYTE $00 ;objects_matasaburo
	.BYTE $00 ;objects_pipi
	.BYTE $14 ;objects_pipi_move
	.BYTE $00 ;objects_pipi_remove
	.BYTE $07 ;objects_pipi_egg
	.BYTE $00 ;objects_pipi_egg_crack
	.BYTE $14 ;objects_copipi
	.BYTE $14 ;objects_kaminari_goro_move
	.BYTE $00 ;objects_kaminari_goro
	.BYTE $00 ;objects_lightning_bolt
	.BYTE $00 ;objects_goblin_1
	.BYTE $00 ;objects_goblin_2
	.BYTE $00 ;objects_goblin_1_palette
	.BYTE $00 ;objects_goblin_2_palette
	.BYTE $00 ;objects_goblin_horn
	.BYTE $14 ;objects_petit_goblin
	.BYTE $00 ;objects_springer
	.BYTE $00 ;objects_mole
	.BYTE $07 ;objects_mole_up
	.BYTE $07 ;objects_mole_down
	.BYTE $00 ;objects_mole_remove
	.BYTE $07 ;objects_shotman_left
	.BYTE $07 ;objects_shotman_right
	.BYTE $00 ;objects_shotman_shoot
	.BYTE $07 ;objects_sniper_armor
	.BYTE $04 ;objects_returning_sniper_joe
	.BYTE $14 ;objects_scworm_pipe
	.BYTE $14 ;objects_scworm
	.BYTE $00 ;objects_unknown_press
	.BYTE $00 ;objects_appearing_block_1
	.BYTE $00 ;objects_appearing_block_2
	.BYTE $00 ;objects_appearing_block_3
	.BYTE $00 ;objects_crashman_palette_swap
	.BYTE $00 ;objects_destroyed_block_57
	.BYTE $00 ;objects_heatman_atomic_fire
	.BYTE $00 ;objects_quickman_quick_boomerang
	.BYTE $00 ;objects_bubbleman_shoot
	.BYTE $00 ;objects_bubbleman_bubble_lead
	.BYTE $00 ;objects_metalman_metall_blade
	.BYTE $00 ;objects_airman_air_shooter
	.BYTE $00 ;objects_crashman_crash_bomber
	.BYTE $00 ;objects_crashman_crash_bomber_explosion
	.BYTE $00 ;objects_explosion
	.BYTE $00 ;objects_woodman_leaf_shield
	.BYTE $00 ;objects_woodman_leaf
	.BYTE $00 ;objects_mecha_dragon_block
	.BYTE $00 ;objects_mecha_dragon
	.BYTE $00 ;objects_mecha_dragon_wing
	.BYTE $00 ;objects_mecha_dragon_tail_head
	.BYTE $00 ;objects_mecha_dragon_beam
	.BYTE $00 ;objects_mecha_dragon_fireball
	.BYTE $00 ;objects_guts_tank_fist
	.BYTE $00 ;objects_picopico_kun_apart
	.BYTE $00 ;objects_large_bullet
	.BYTE $00 ;objects_wily_machine_2_cockpit_damage
	.BYTE $00 ;objects_boobeam_trap
	.BYTE $00 ;objects_boobeam_trap_shoot
	.BYTE $00 ;objects_alien_shot
	.BYTE $00 ;objects_alien_star
	.BYTE $00 ;objects_big_fish
	.BYTE $00 ;objects_red_liquid_1
	.BYTE $00 ;objects_red_liquid_2
	.BYTE $00 ;objects_red_liquid_drop
	.BYTE $00 ;objects_no_effect_large_life_capsule
	.BYTE $00 ;objects_large_life_capsule
	.BYTE $00 ;objects_small_life_capsule

@leaf_shield_damage_table:
	.BYTE $14 ;objects_shrink
	.BYTE $14 ;objects_shrink_move
	.BYTE $00 ;objects_anko_release_shrink
	.BYTE $00 ;objects_m_445
	.BYTE $14 ;objects_m_445_move
	.BYTE $00 ;objects_m_445_remove
	.BYTE $14 ;objects_killed
	.BYTE $00 ;objects_claw
	.BYTE $14 ;objects_claw_move
	.BYTE $00 ;objects_claw_remove
	.BYTE $14 ;objects_tanishi
	.BYTE $14 ;objects_tanishi_no_shell_move
	.BYTE $00 ;objects_kerog
	.BYTE $14 ;objects_petit_kerog
	.BYTE $00 ;objects_bubble
	.BYTE $07 ;objects_anko_lamp
	.BYTE $00 ;objects_anko_eye_tail
	.BYTE $00 ;objects_anko_palette
	.BYTE $00 ;objects_lift
	.BYTE $00 ;objects_drop_platform
	.BYTE $00 ;objects_laser
	.BYTE $00 ;objects_laser_move
	.BYTE $14 ;objects_batton
	.BYTE $14 ;objects_robbit
	.BYTE $00 ;objects_carrot
	.BYTE $14 ;objects_friender_head
	.BYTE $00 ;objects_friender_tail
	.BYTE $00 ;objects_friender_fire_breath
	.BYTE $00 ;objects_friender
	.BYTE $14 ;objects_monking
	.BYTE $00 ;objects_kukku
	.BYTE $14 ;objects_kukku_move
	.BYTE $00 ;objects_kukku_remove
	.BYTE $00 ;objects_telly
	.BYTE $14 ;objects_telly_move
	.BYTE $07 ;objects_changkey_maker
	.BYTE $00 ;objects_changkey
	.BYTE $00 ;objects_light_to_dark
	.BYTE $00 ;objects_changkey_maker_light
	.BYTE $00 ;objects_dark_to_light
	.BYTE $00 ;objects_changkey_maker_killed_to_dark
	.BYTE $07 ;objects_pierrobot_jester
	.BYTE $14 ;objects_pierrobot
	.BYTE $00 ;objects_fly_boy
	.BYTE $07 ;objects_fly_boy_move
	.BYTE $00 ;objects_destroyed_block_2d
	.BYTE $00 ;objects_friender_block
	.BYTE $00 ;objects_shutter
	.BYTE $00 ;objects_press
	.BYTE $00 ;objects_blocky
	.BYTE $00 ;objects_blocky_move
	.BYTE $00 ;objects_blocky_apart
	.BYTE $14 ;objects_neo_metall
	.BYTE $00 ;objects_straight_bullet
	.BYTE $07 ;objects_matasaburo
	.BYTE $00 ;objects_pipi
	.BYTE $14 ;objects_pipi_move
	.BYTE $00 ;objects_pipi_remove
	.BYTE $14 ;objects_pipi_egg
	.BYTE $00 ;objects_pipi_egg_crack
	.BYTE $14 ;objects_copipi
	.BYTE $14 ;objects_kaminari_goro_move
	.BYTE $00 ;objects_kaminari_goro
	.BYTE $00 ;objects_lightning_bolt
	.BYTE $00 ;objects_goblin_1
	.BYTE $00 ;objects_goblin_2
	.BYTE $00 ;objects_goblin_1_palette
	.BYTE $00 ;objects_goblin_2_palette
	.BYTE $00 ;objects_goblin_horn
	.BYTE $14 ;objects_petit_goblin
	.BYTE $14 ;objects_springer
	.BYTE $00 ;objects_mole
	.BYTE $14 ;objects_mole_up
	.BYTE $14 ;objects_mole_down
	.BYTE $00 ;objects_mole_remove
	.BYTE $14 ;objects_shotman_left
	.BYTE $14 ;objects_shotman_right
	.BYTE $00 ;objects_shotman_shoot
	.BYTE $07 ;objects_sniper_armor
	.BYTE $07 ;objects_returning_sniper_joe
	.BYTE $14 ;objects_scworm_pipe
	.BYTE $14 ;objects_scworm
	.BYTE $00 ;objects_unknown_press
	.BYTE $00 ;objects_appearing_block_1
	.BYTE $00 ;objects_appearing_block_2
	.BYTE $00 ;objects_appearing_block_3
	.BYTE $00 ;objects_crashman_palette_swap
	.BYTE $00 ;objects_destroyed_block_57
	.BYTE $00 ;objects_heatman_atomic_fire
	.BYTE $00 ;objects_quickman_quick_boomerang
	.BYTE $00 ;objects_bubbleman_shoot
	.BYTE $00 ;objects_bubbleman_bubble_lead
	.BYTE $00 ;objects_metalman_metall_blade
	.BYTE $00 ;objects_airman_air_shooter
	.BYTE $00 ;objects_crashman_crash_bomber
	.BYTE $00 ;objects_crashman_crash_bomber_explosion
	.BYTE $00 ;objects_explosion
	.BYTE $00 ;objects_woodman_leaf_shield
	.BYTE $00 ;objects_woodman_leaf
	.BYTE $00 ;objects_mecha_dragon_block
	.BYTE $00 ;objects_mecha_dragon
	.BYTE $00 ;objects_mecha_dragon_wing
	.BYTE $00 ;objects_mecha_dragon_tail_head
	.BYTE $00 ;objects_mecha_dragon_beam
	.BYTE $00 ;objects_mecha_dragon_fireball
	.BYTE $00 ;objects_guts_tank_fist
	.BYTE $00 ;objects_picopico_kun_apart
	.BYTE $00 ;objects_large_bullet
	.BYTE $00 ;objects_wily_machine_2_cockpit_damage
	.BYTE $00 ;objects_boobeam_trap
	.BYTE $00 ;objects_boobeam_trap_shoot
	.BYTE $00 ;objects_alien_shot
	.BYTE $00 ;objects_alien_star
	.BYTE $00 ;objects_big_fish
	.BYTE $00 ;objects_red_liquid_1
	.BYTE $00 ;objects_red_liquid_2
	.BYTE $00 ;objects_red_liquid_drop
	.BYTE $00 ;objects_no_effect_large_life_capsule
	.BYTE $00 ;objects_large_life_capsule
	.BYTE $00 ;objects_small_life_capsule

@bubble_lead_damage_table:
	.BYTE $14 ;objects_shrink
	.BYTE $14 ;objects_shrink_move
	.BYTE $00 ;objects_anko_release_shrink
	.BYTE $00 ;objects_m_445
	.BYTE $00 ;objects_m_445_move
	.BYTE $00 ;objects_m_445_remove
	.BYTE $14 ;objects_killed
	.BYTE $00 ;objects_claw
	.BYTE $14 ;objects_claw_move
	.BYTE $00 ;objects_claw_remove
	.BYTE $00 ;objects_tanishi
	.BYTE $14 ;objects_tanishi_no_shell_move
	.BYTE $04 ;objects_kerog
	.BYTE $14 ;objects_petit_kerog
	.BYTE $00 ;objects_bubble
	.BYTE $00 ;objects_anko_lamp
	.BYTE $00 ;objects_anko_eye_tail
	.BYTE $00 ;objects_anko_palette
	.BYTE $00 ;objects_lift
	.BYTE $00 ;objects_drop_platform
	.BYTE $00 ;objects_laser
	.BYTE $00 ;objects_laser_move
	.BYTE $00 ;objects_batton
	.BYTE $07 ;objects_robbit
	.BYTE $00 ;objects_carrot
	.BYTE $00 ;objects_friender_head
	.BYTE $00 ;objects_friender_tail
	.BYTE $00 ;objects_friender_fire_breath
	.BYTE $00 ;objects_friender
	.BYTE $00 ;objects_monking
	.BYTE $00 ;objects_kukku
	.BYTE $00 ;objects_kukku_move
	.BYTE $00 ;objects_kukku_remove
	.BYTE $00 ;objects_telly
	.BYTE $00 ;objects_telly_move
	.BYTE $07 ;objects_changkey_maker
	.BYTE $00 ;objects_changkey
	.BYTE $00 ;objects_light_to_dark
	.BYTE $00 ;objects_changkey_maker_light
	.BYTE $00 ;objects_dark_to_light
	.BYTE $00 ;objects_changkey_maker_killed_to_dark
	.BYTE $00 ;objects_pierrobot_jester
	.BYTE $00 ;objects_pierrobot
	.BYTE $00 ;objects_fly_boy
	.BYTE $00 ;objects_fly_boy_move
	.BYTE $00 ;objects_destroyed_block_2d
	.BYTE $00 ;objects_friender_block
	.BYTE $00 ;objects_shutter
	.BYTE $00 ;objects_press
	.BYTE $00 ;objects_blocky
	.BYTE $00 ;objects_blocky_move
	.BYTE $00 ;objects_blocky_apart
	.BYTE $14 ;objects_neo_metall
	.BYTE $00 ;objects_straight_bullet
	.BYTE $07 ;objects_matasaburo
	.BYTE $00 ;objects_pipi
	.BYTE $00 ;objects_pipi_move
	.BYTE $00 ;objects_pipi_remove
	.BYTE $00 ;objects_pipi_egg
	.BYTE $00 ;objects_pipi_egg_crack
	.BYTE $14 ;objects_copipi
	.BYTE $14 ;objects_kaminari_goro_move
	.BYTE $00 ;objects_kaminari_goro
	.BYTE $00 ;objects_lightning_bolt
	.BYTE $00 ;objects_goblin_1
	.BYTE $00 ;objects_goblin_2
	.BYTE $00 ;objects_goblin_1_palette
	.BYTE $00 ;objects_goblin_2_palette
	.BYTE $00 ;objects_goblin_horn
	.BYTE $00 ;objects_petit_goblin
	.BYTE $07 ;objects_springer
	.BYTE $00 ;objects_mole
	.BYTE $00 ;objects_mole_up
	.BYTE $00 ;objects_mole_down
	.BYTE $00 ;objects_mole_remove
	.BYTE $02 ;objects_shotman_left
	.BYTE $02 ;objects_shotman_right
	.BYTE $00 ;objects_shotman_shoot
	.BYTE $00 ;objects_sniper_armor
	.BYTE $04 ;objects_returning_sniper_joe
	.BYTE $07 ;objects_scworm_pipe
	.BYTE $07 ;objects_scworm
	.BYTE $00 ;objects_unknown_press
	.BYTE $00 ;objects_appearing_block_1
	.BYTE $00 ;objects_appearing_block_2
	.BYTE $00 ;objects_appearing_block_3
	.BYTE $00 ;objects_crashman_palette_swap
	.BYTE $00 ;objects_destroyed_block_57
	.BYTE $00 ;objects_heatman_atomic_fire
	.BYTE $00 ;objects_quickman_quick_boomerang
	.BYTE $00 ;objects_bubbleman_shoot
	.BYTE $00 ;objects_bubbleman_bubble_lead
	.BYTE $00 ;objects_metalman_metall_blade
	.BYTE $00 ;objects_airman_air_shooter
	.BYTE $00 ;objects_crashman_crash_bomber
	.BYTE $00 ;objects_crashman_crash_bomber_explosion
	.BYTE $00 ;objects_explosion
	.BYTE $00 ;objects_woodman_leaf_shield
	.BYTE $00 ;objects_woodman_leaf
	.BYTE $00 ;objects_mecha_dragon_block
	.BYTE $00 ;objects_mecha_dragon
	.BYTE $00 ;objects_mecha_dragon_wing
	.BYTE $00 ;objects_mecha_dragon_tail_head
	.BYTE $00 ;objects_mecha_dragon_beam
	.BYTE $00 ;objects_mecha_dragon_fireball
	.BYTE $00 ;objects_guts_tank_fist
	.BYTE $14 ;objects_picopico_kun_apart
	.BYTE $00 ;objects_large_bullet
	.BYTE $00 ;objects_wily_machine_2_cockpit_damage
	.BYTE $00 ;objects_boobeam_trap
	.BYTE $00 ;objects_boobeam_trap_shoot
	.BYTE $00 ;objects_alien_shot
	.BYTE $00 ;objects_alien_star
	.BYTE $00 ;objects_big_fish
	.BYTE $00 ;objects_red_liquid_1
	.BYTE $00 ;objects_red_liquid_2
	.BYTE $00 ;objects_red_liquid_drop
	.BYTE $00 ;objects_no_effect_large_life_capsule
	.BYTE $00 ;objects_large_life_capsule
	.BYTE $00 ;objects_small_life_capsule

@quick_boomerang_damage_table:
	.BYTE $07 ;objects_shrink
	.BYTE $07 ;objects_shrink_move
	.BYTE $00 ;objects_anko_release_shrink
	.BYTE $00 ;objects_m_445
	.BYTE $14 ;objects_m_445_move
	.BYTE $00 ;objects_m_445_remove
	.BYTE $14 ;objects_killed
	.BYTE $00 ;objects_claw
	.BYTE $07 ;objects_claw_move
	.BYTE $00 ;objects_claw_remove
	.BYTE $04 ;objects_tanishi
	.BYTE $14 ;objects_tanishi_no_shell_move
	.BYTE $04 ;objects_kerog
	.BYTE $14 ;objects_petit_kerog
	.BYTE $00 ;objects_bubble
	.BYTE $02 ;objects_anko_lamp
	.BYTE $00 ;objects_anko_eye_tail
	.BYTE $00 ;objects_anko_palette
	.BYTE $00 ;objects_lift
	.BYTE $00 ;objects_drop_platform
	.BYTE $00 ;objects_laser
	.BYTE $00 ;objects_laser_move
	.BYTE $0A ;objects_batton
	.BYTE $04 ;objects_robbit
	.BYTE $00 ;objects_carrot
	.BYTE $02 ;objects_friender_head
	.BYTE $00 ;objects_friender_tail
	.BYTE $00 ;objects_friender_fire_breath
	.BYTE $00 ;objects_friender
	.BYTE $07 ;objects_monking
	.BYTE $00 ;objects_kukku
	.BYTE $02 ;objects_kukku_move
	.BYTE $00 ;objects_kukku_remove
	.BYTE $00 ;objects_telly
	.BYTE $14 ;objects_telly_move
	.BYTE $02 ;objects_changkey_maker
	.BYTE $00 ;objects_changkey
	.BYTE $00 ;objects_light_to_dark
	.BYTE $00 ;objects_changkey_maker_light
	.BYTE $00 ;objects_dark_to_light
	.BYTE $00 ;objects_changkey_maker_killed_to_dark
	.BYTE $07 ;objects_pierrobot_jester
	.BYTE $07 ;objects_pierrobot
	.BYTE $00 ;objects_fly_boy
	.BYTE $04 ;objects_fly_boy_move
	.BYTE $00 ;objects_destroyed_block_2d
	.BYTE $00 ;objects_friender_block
	.BYTE $00 ;objects_shutter
	.BYTE $00 ;objects_press
	.BYTE $0A ;objects_blocky
	.BYTE $00 ;objects_blocky_move
	.BYTE $00 ;objects_blocky_apart
	.BYTE $14 ;objects_neo_metall
	.BYTE $00 ;objects_straight_bullet
	.BYTE $04 ;objects_matasaburo
	.BYTE $00 ;objects_pipi
	.BYTE $14 ;objects_pipi_move
	.BYTE $00 ;objects_pipi_remove
	.BYTE $00 ;objects_pipi_egg
	.BYTE $00 ;objects_pipi_egg_crack
	.BYTE $14 ;objects_copipi
	.BYTE $07 ;objects_kaminari_goro_move
	.BYTE $00 ;objects_kaminari_goro
	.BYTE $00 ;objects_lightning_bolt
	.BYTE $00 ;objects_goblin_1
	.BYTE $00 ;objects_goblin_2
	.BYTE $00 ;objects_goblin_1_palette
	.BYTE $00 ;objects_goblin_2_palette
	.BYTE $00 ;objects_goblin_horn
	.BYTE $14 ;objects_petit_goblin
	.BYTE $07 ;objects_springer
	.BYTE $00 ;objects_mole
	.BYTE $04 ;objects_mole_up
	.BYTE $04 ;objects_mole_down
	.BYTE $00 ;objects_mole_remove
	.BYTE $04 ;objects_shotman_left
	.BYTE $04 ;objects_shotman_right
	.BYTE $00 ;objects_shotman_shoot
	.BYTE $04 ;objects_sniper_armor
	.BYTE $04 ;objects_returning_sniper_joe
	.BYTE $04 ;objects_scworm_pipe
	.BYTE $04 ;objects_scworm
	.BYTE $00 ;objects_unknown_press
	.BYTE $00 ;objects_appearing_block_1
	.BYTE $00 ;objects_appearing_block_2
	.BYTE $00 ;objects_appearing_block_3
	.BYTE $00 ;objects_crashman_palette_swap
	.BYTE $00 ;objects_destroyed_block_57
	.BYTE $00 ;objects_heatman_atomic_fire
	.BYTE $00 ;objects_quickman_quick_boomerang
	.BYTE $00 ;objects_bubbleman_shoot
	.BYTE $00 ;objects_bubbleman_bubble_lead
	.BYTE $00 ;objects_metalman_metall_blade
	.BYTE $00 ;objects_airman_air_shooter
	.BYTE $00 ;objects_crashman_crash_bomber
	.BYTE $00 ;objects_crashman_crash_bomber_explosion
	.BYTE $00 ;objects_explosion
	.BYTE $00 ;objects_woodman_leaf_shield
	.BYTE $00 ;objects_woodman_leaf
	.BYTE $00 ;objects_mecha_dragon_block
	.BYTE $00 ;objects_mecha_dragon
	.BYTE $00 ;objects_mecha_dragon_wing
	.BYTE $00 ;objects_mecha_dragon_tail_head
	.BYTE $00 ;objects_mecha_dragon_beam
	.BYTE $00 ;objects_mecha_dragon_fireball
	.BYTE $00 ;objects_guts_tank_fist
	.BYTE $07 ;objects_picopico_kun_apart
	.BYTE $00 ;objects_large_bullet
	.BYTE $00 ;objects_wily_machine_2_cockpit_damage
	.BYTE $00 ;objects_boobeam_trap
	.BYTE $00 ;objects_boobeam_trap_shoot
	.BYTE $00 ;objects_alien_shot
	.BYTE $00 ;objects_alien_star
	.BYTE $14 ;objects_big_fish
	.BYTE $00 ;objects_red_liquid_1
	.BYTE $00 ;objects_red_liquid_2
	.BYTE $00 ;objects_red_liquid_drop
	.BYTE $00 ;objects_no_effect_large_life_capsule
	.BYTE $00 ;objects_large_life_capsule
	.BYTE $00 ;objects_small_life_capsule

@crash_bomber_damage_table:
	.BYTE $14 ;objects_shrink
	.BYTE $14 ;objects_shrink_move
	.BYTE $00 ;objects_anko_release_shrink
	.BYTE $00 ;objects_m_445
	.BYTE $14 ;objects_m_445_move
	.BYTE $00 ;objects_m_445_remove
	.BYTE $14 ;objects_killed
	.BYTE $00 ;objects_claw
	.BYTE $14 ;objects_claw_move
	.BYTE $00 ;objects_claw_remove
	.BYTE $14 ;objects_tanishi
	.BYTE $14 ;objects_tanishi_no_shell_move
	.BYTE $00 ;objects_kerog
	.BYTE $14 ;objects_petit_kerog
	.BYTE $00 ;objects_bubble
	.BYTE $00 ;objects_anko_lamp
	.BYTE $00 ;objects_anko_eye_tail
	.BYTE $00 ;objects_anko_palette
	.BYTE $00 ;objects_lift
	.BYTE $00 ;objects_drop_platform
	.BYTE $00 ;objects_laser
	.BYTE $00 ;objects_laser_move
	.BYTE $14 ;objects_batton
	.BYTE $14 ;objects_robbit
	.BYTE $00 ;objects_carrot
	.BYTE $00 ;objects_friender_head
	.BYTE $00 ;objects_friender_tail
	.BYTE $00 ;objects_friender_fire_breath
	.BYTE $00 ;objects_friender
	.BYTE $14 ;objects_monking
	.BYTE $00 ;objects_kukku
	.BYTE $14 ;objects_kukku_move
	.BYTE $00 ;objects_kukku_remove
	.BYTE $00 ;objects_telly
	.BYTE $14 ;objects_telly_move
	.BYTE $00 ;objects_changkey_maker
	.BYTE $00 ;objects_changkey
	.BYTE $00 ;objects_light_to_dark
	.BYTE $00 ;objects_changkey_maker_light
	.BYTE $00 ;objects_dark_to_light
	.BYTE $00 ;objects_changkey_maker_killed_to_dark
	.BYTE $14 ;objects_pierrobot_jester
	.BYTE $14 ;objects_pierrobot
	.BYTE $00 ;objects_fly_boy
	.BYTE $14 ;objects_fly_boy_move
	.BYTE $0A ;objects_destroyed_block_2d
	.BYTE $00 ;objects_friender_block
	.BYTE $00 ;objects_shutter
	.BYTE $00 ;objects_press
	.BYTE $14 ;objects_blocky
	.BYTE $00 ;objects_blocky_move
	.BYTE $00 ;objects_blocky_apart
	.BYTE $14 ;objects_neo_metall
	.BYTE $00 ;objects_straight_bullet
	.BYTE $07 ;objects_matasaburo
	.BYTE $00 ;objects_pipi
	.BYTE $14 ;objects_pipi_move
	.BYTE $00 ;objects_pipi_remove
	.BYTE $14 ;objects_pipi_egg
	.BYTE $00 ;objects_pipi_egg_crack
	.BYTE $14 ;objects_copipi
	.BYTE $14 ;objects_kaminari_goro_move
	.BYTE $00 ;objects_kaminari_goro
	.BYTE $00 ;objects_lightning_bolt
	.BYTE $00 ;objects_goblin_1
	.BYTE $00 ;objects_goblin_2
	.BYTE $00 ;objects_goblin_1_palette
	.BYTE $00 ;objects_goblin_2_palette
	.BYTE $00 ;objects_goblin_horn
	.BYTE $14 ;objects_petit_goblin
	.BYTE $07 ;objects_springer
	.BYTE $00 ;objects_mole
	.BYTE $04 ;objects_mole_up
	.BYTE $04 ;objects_mole_down
	.BYTE $00 ;objects_mole_remove
	.BYTE $04 ;objects_shotman_left
	.BYTE $04 ;objects_shotman_right
	.BYTE $00 ;objects_shotman_shoot
	.BYTE $04 ;objects_sniper_armor
	.BYTE $02 ;objects_returning_sniper_joe
	.BYTE $04 ;objects_scworm_pipe
	.BYTE $04 ;objects_scworm
	.BYTE $00 ;objects_unknown_press
	.BYTE $00 ;objects_appearing_block_1
	.BYTE $00 ;objects_appearing_block_2
	.BYTE $00 ;objects_appearing_block_3
	.BYTE $00 ;objects_crashman_palette_swap
	.BYTE $0A ;objects_destroyed_block_57
	.BYTE $00 ;objects_heatman_atomic_fire
	.BYTE $00 ;objects_quickman_quick_boomerang
	.BYTE $00 ;objects_bubbleman_shoot
	.BYTE $00 ;objects_bubbleman_bubble_lead
	.BYTE $00 ;objects_metalman_metall_blade
	.BYTE $00 ;objects_airman_air_shooter
	.BYTE $00 ;objects_crashman_crash_bomber
	.BYTE $00 ;objects_crashman_crash_bomber_explosion
	.BYTE $00 ;objects_explosion
	.BYTE $00 ;objects_woodman_leaf_shield
	.BYTE $00 ;objects_woodman_leaf
	.BYTE $00 ;objects_mecha_dragon_block
	.BYTE $00 ;objects_mecha_dragon
	.BYTE $00 ;objects_mecha_dragon_wing
	.BYTE $00 ;objects_mecha_dragon_tail_head
	.BYTE $00 ;objects_mecha_dragon_beam
	.BYTE $00 ;objects_mecha_dragon_fireball
	.BYTE $00 ;objects_guts_tank_fist
	.BYTE $00 ;objects_picopico_kun_apart
	.BYTE $00 ;objects_large_bullet
	.BYTE $00 ;objects_wily_machine_2_cockpit_damage
	.BYTE $14 ;objects_boobeam_trap
	.BYTE $00 ;objects_boobeam_trap_shoot
	.BYTE $00 ;objects_alien_shot
	.BYTE $00 ;objects_alien_star
	.BYTE $14 ;objects_big_fish
	.BYTE $00 ;objects_red_liquid_1
	.BYTE $00 ;objects_red_liquid_2
	.BYTE $00 ;objects_red_liquid_drop
	.BYTE $00 ;objects_no_effect_large_life_capsule
	.BYTE $00 ;objects_large_life_capsule
	.BYTE $00 ;objects_small_life_capsule

@metal_blade_damage_table:
	.BYTE $14 ;objects_shrink
	.BYTE $14 ;objects_shrink_move
	.BYTE $00 ;objects_anko_release_shrink
	.BYTE $00 ;objects_m_445
	.BYTE $14 ;objects_m_445_move
	.BYTE $00 ;objects_m_445_remove
	.BYTE $14 ;objects_killed
	.BYTE $00 ;objects_claw
	.BYTE $14 ;objects_claw_move
	.BYTE $00 ;objects_claw_remove
	.BYTE $04 ;objects_tanishi
	.BYTE $14 ;objects_tanishi_no_shell_move
	.BYTE $02 ;objects_kerog
	.BYTE $14 ;objects_petit_kerog
	.BYTE $00 ;objects_bubble
	.BYTE $04 ;objects_anko_lamp
	.BYTE $00 ;objects_anko_eye_tail
	.BYTE $00 ;objects_anko_palette
	.BYTE $00 ;objects_lift
	.BYTE $00 ;objects_drop_platform
	.BYTE $00 ;objects_laser
	.BYTE $00 ;objects_laser_move
	.BYTE $14 ;objects_batton
	.BYTE $04 ;objects_robbit
	.BYTE $00 ;objects_carrot
	.BYTE $02 ;objects_friender_head
	.BYTE $00 ;objects_friender_tail
	.BYTE $00 ;objects_friender_fire_breath
	.BYTE $00 ;objects_friender
	.BYTE $07 ;objects_monking
	.BYTE $00 ;objects_kukku
	.BYTE $00 ;objects_kukku_move
	.BYTE $00 ;objects_kukku_remove
	.BYTE $00 ;objects_telly
	.BYTE $14 ;objects_telly_move
	.BYTE $04 ;objects_changkey_maker
	.BYTE $00 ;objects_changkey
	.BYTE $00 ;objects_light_to_dark
	.BYTE $00 ;objects_changkey_maker_light
	.BYTE $00 ;objects_dark_to_light
	.BYTE $00 ;objects_changkey_maker_killed_to_dark
	.BYTE $00 ;objects_pierrobot_jester
	.BYTE $14 ;objects_pierrobot
	.BYTE $00 ;objects_fly_boy
	.BYTE $14 ;objects_fly_boy_move
	.BYTE $00 ;objects_destroyed_block_2d
	.BYTE $00 ;objects_friender_block
	.BYTE $00 ;objects_shutter
	.BYTE $00 ;objects_press
	.BYTE $0A ;objects_blocky
	.BYTE $00 ;objects_blocky_move
	.BYTE $00 ;objects_blocky_apart
	.BYTE $14 ;objects_neo_metall
	.BYTE $00 ;objects_straight_bullet
	.BYTE $04 ;objects_matasaburo
	.BYTE $00 ;objects_pipi
	.BYTE $14 ;objects_pipi_move
	.BYTE $00 ;objects_pipi_remove
	.BYTE $14 ;objects_pipi_egg
	.BYTE $00 ;objects_pipi_egg_crack
	.BYTE $14 ;objects_copipi
	.BYTE $07 ;objects_kaminari_goro_move
	.BYTE $00 ;objects_kaminari_goro
	.BYTE $00 ;objects_lightning_bolt
	.BYTE $00 ;objects_goblin_1
	.BYTE $00 ;objects_goblin_2
	.BYTE $00 ;objects_goblin_1_palette
	.BYTE $00 ;objects_goblin_2_palette
	.BYTE $00 ;objects_goblin_horn
	.BYTE $14 ;objects_petit_goblin
	.BYTE $00 ;objects_springer
	.BYTE $00 ;objects_mole
	.BYTE $07 ;objects_mole_up
	.BYTE $07 ;objects_mole_down
	.BYTE $00 ;objects_mole_remove
	.BYTE $04 ;objects_shotman_left
	.BYTE $04 ;objects_shotman_right
	.BYTE $00 ;objects_shotman_shoot
	.BYTE $00 ;objects_sniper_armor
	.BYTE $02 ;objects_returning_sniper_joe
	.BYTE $14 ;objects_scworm_pipe
	.BYTE $14 ;objects_scworm
	.BYTE $00 ;objects_unknown_press
	.BYTE $00 ;objects_appearing_block_1
	.BYTE $00 ;objects_appearing_block_2
	.BYTE $00 ;objects_appearing_block_3
	.BYTE $00 ;objects_crashman_palette_swap
	.BYTE $00 ;objects_destroyed_block_57
	.BYTE $00 ;objects_heatman_atomic_fire
	.BYTE $00 ;objects_quickman_quick_boomerang
	.BYTE $00 ;objects_bubbleman_shoot
	.BYTE $00 ;objects_bubbleman_bubble_lead
	.BYTE $00 ;objects_metalman_metall_blade
	.BYTE $00 ;objects_airman_air_shooter
	.BYTE $00 ;objects_crashman_crash_bomber
	.BYTE $00 ;objects_crashman_crash_bomber_explosion
	.BYTE $00 ;objects_explosion
	.BYTE $00 ;objects_woodman_leaf_shield
	.BYTE $00 ;objects_woodman_leaf
	.BYTE $00 ;objects_mecha_dragon_block
	.BYTE $00 ;objects_mecha_dragon
	.BYTE $00 ;objects_mecha_dragon_wing
	.BYTE $00 ;objects_mecha_dragon_tail_head
	.BYTE $00 ;objects_mecha_dragon_beam
	.BYTE $00 ;objects_mecha_dragon_fireball
	.BYTE $00 ;objects_guts_tank_fist
	.BYTE $07 ;objects_picopico_kun_apart
	.BYTE $00 ;objects_large_bullet
	.BYTE $00 ;objects_wily_machine_2_cockpit_damage
	.BYTE $00 ;objects_boobeam_trap
	.BYTE $00 ;objects_boobeam_trap_shoot
	.BYTE $00 ;objects_alien_shot
	.BYTE $00 ;objects_alien_star
	.BYTE $00 ;objects_big_fish
	.BYTE $00 ;objects_red_liquid_1
	.BYTE $00 ;objects_red_liquid_2
	.BYTE $00 ;objects_red_liquid_drop
	.BYTE $00 ;objects_no_effect_large_life_capsule
	.BYTE $00 ;objects_large_life_capsule
	.BYTE $00 ;objects_small_life_capsule
