;32x32 blocksets with 16x16 blocksets | block_attribute.
;block_attribute 2 and 3 setting see home/blocksets.asm. 
	      ;top left,                  bottom left,                top right,                  bottom right
	.BYTE $00 | block_attribute_null, $00 | block_attribute_null, $00 | block_attribute_null, $00 | block_attribute_null ;00
	.BYTE $00 | block_attribute_null, $00 | block_attribute_null, $3D | block_attribute_wall, $00 | block_attribute_null ;01
	.BYTE $3D | block_attribute_wall, $00 | block_attribute_null, $3D | block_attribute_wall, $00 | block_attribute_null ;02
	.BYTE $3D | block_attribute_wall, $00 | block_attribute_null, $00 | block_attribute_null, $00 | block_attribute_null ;03
	.BYTE $00 | block_attribute_null, $00 | block_attribute_null, $09 | block_attribute_wall, $09 | block_attribute_wall ;04
	.BYTE $07 | block_attribute_wall, $0C | block_attribute_wall, $07 | block_attribute_wall, $0D | block_attribute_wall ;05
	.BYTE $0E | block_attribute_wall, $0B | block_attribute_wall, $0F | block_attribute_wall, $0B | block_attribute_wall ;06
	.BYTE $00 | block_attribute_null, $00 | block_attribute_null, $08 | block_attribute_null, $08 | block_attribute_null ;07
	.BYTE $3D | block_attribute_wall, $3D | block_attribute_wall, $3D | block_attribute_wall, $3D | block_attribute_wall ;08
	.BYTE $3F | block_attribute_null, $3E | block_attribute_null, $08 | block_attribute_null, $08 | block_attribute_null ;09
	.BYTE $00 | block_attribute_null, $00 | block_attribute_null, $08 | block_attribute_null, $08 | block_attribute_null ;0A
	.BYTE $3D | block_attribute_wall, $3D | block_attribute_wall, $3F | block_attribute_null, $3E | block_attribute_null ;0B
	.BYTE $3D | block_attribute_wall, $3D | block_attribute_wall, $00 | block_attribute_null, $00 | block_attribute_null ;0C
	.BYTE $3F | block_attribute_null, $3E | block_attribute_null, $3D | block_attribute_wall, $3D | block_attribute_wall ;0D
	.BYTE $00 | block_attribute_null, $00 | block_attribute_null, $3D | block_attribute_wall, $3D | block_attribute_wall ;0E
	.BYTE $01 | block_attribute_null, $01 | block_attribute_null, $01 | block_attribute_wall, $01 | block_attribute_wall ;0F
	.BYTE $01 | block_attribute_null, $36 | block_attribute_null, $01 | block_attribute_wall, $3E | block_attribute_wall ;10
	.BYTE $00 | block_attribute_null, $18 | block_attribute_wall, $00 | block_attribute_null, $19 | block_attribute_wall ;11
	.BYTE $00 | block_attribute_null, $1A | block_attribute_wall, $00 | block_attribute_null, $1B | block_attribute_wall ;12
	.BYTE $00 | block_attribute_null, $1C | block_attribute_wall, $00 | block_attribute_null, $00 | block_attribute_null ;13
	.BYTE $20 | block_attribute_wall, $28 | block_attribute_wall, $21 | block_attribute_wall, $29 | block_attribute_wall ;14
	.BYTE $22 | block_attribute_wall, $2A | block_attribute_wall, $23 | block_attribute_wall, $2B | block_attribute_wall ;15
	.BYTE $24 | block_attribute_wall, $2C | block_attribute_wall, $00 | block_attribute_null, $00 | block_attribute_null ;16
	.BYTE $30 | block_attribute_wall, $38 | block_attribute_wall, $31 | block_attribute_wall, $39 | block_attribute_wall ;17
	.BYTE $32 | block_attribute_wall, $3A | block_attribute_wall, $33 | block_attribute_wall, $3B | block_attribute_wall ;18
	.BYTE $34 | block_attribute_wall, $3C | block_attribute_wall, $00 | block_attribute_null, $00 | block_attribute_null ;19
	.BYTE $00 | block_attribute_null, $00 | block_attribute_null, $00 | block_attribute_null, $18 | block_attribute_wall ;1A
	.BYTE $00 | block_attribute_null, $19 | block_attribute_wall, $00 | block_attribute_null, $1A | block_attribute_wall ;1B
	.BYTE $00 | block_attribute_null, $1B | block_attribute_wall, $00 | block_attribute_null, $1C | block_attribute_wall ;1C
	.BYTE $00 | block_attribute_null, $00 | block_attribute_null, $20 | block_attribute_wall, $28 | block_attribute_wall ;1D
	.BYTE $21 | block_attribute_wall, $29 | block_attribute_wall, $22 | block_attribute_wall, $2A | block_attribute_wall ;1E
	.BYTE $23 | block_attribute_wall, $2B | block_attribute_wall, $24 | block_attribute_wall, $2C | block_attribute_wall ;1F
	.BYTE $00 | block_attribute_null, $00 | block_attribute_null, $30 | block_attribute_wall, $38 | block_attribute_wall ;20
	.BYTE $31 | block_attribute_wall, $39 | block_attribute_wall, $32 | block_attribute_wall, $3A | block_attribute_wall ;21
	.BYTE $33 | block_attribute_wall, $3B | block_attribute_wall, $34 | block_attribute_wall, $3C | block_attribute_wall ;22
	.BYTE $01 | block_attribute_null, $01 | block_attribute_null, $01 | block_attribute_null, $01 | block_attribute_null ;23
	.BYTE $01 | block_attribute_null, $26 | block_attribute_null, $26 | block_attribute_null, $00 | block_attribute_null ;24
	.BYTE $00 | block_attribute_null, $00 | block_attribute_null, $25 | block_attribute_null, $00 | block_attribute_null ;25
	.BYTE $01 | block_attribute_null, $25 | block_attribute_null, $01 | block_attribute_null, $01 | block_attribute_null ;26
	.BYTE $00 | block_attribute_null, $2D | block_attribute_null, $2D | block_attribute_null, $01 | block_attribute_null ;27
	.BYTE $01 | block_attribute_null, $26 | block_attribute_null, $01 | block_attribute_null, $25 | block_attribute_null ;28
	.BYTE $01 | block_attribute_null, $35 | block_attribute_null, $01 | block_attribute_null, $36 | block_attribute_null ;29
	.BYTE $2E | block_attribute_null, $01 | block_attribute_null, $2F | block_attribute_null, $01 | block_attribute_null ;2A
	.BYTE $00 | block_attribute_null, $27 | block_attribute_null, $00 | block_attribute_null, $2D | block_attribute_null ;2B
	.BYTE $00 | block_attribute_null, $27 | block_attribute_null, $00 | block_attribute_null, $00 | block_attribute_null ;2C
	.BYTE $01 | block_attribute_null, $01 | block_attribute_null, $27 | block_attribute_null, $01 | block_attribute_null ;2D
	.BYTE $00 | block_attribute_null, $27 | block_attribute_null, $00 | block_attribute_null, $00 | block_attribute_null ;2E
	.BYTE $00 | block_attribute_null, $00 | block_attribute_null, $00 | block_attribute_null, $2D | block_attribute_null ;2F
	.BYTE $2D | block_attribute_null, $01 | block_attribute_null, $01 | block_attribute_null, $01 | block_attribute_null ;30
	.BYTE $26 | block_attribute_null, $00 | block_attribute_null, $00 | block_attribute_null, $00 | block_attribute_null ;31
	.BYTE $01 | block_attribute_null, $01 | block_attribute_null, $01 | block_attribute_null, $26 | block_attribute_null ;32
	.BYTE $00 | block_attribute_null, $2E | block_attribute_null, $00 | block_attribute_null, $2F | block_attribute_null ;33
	.BYTE $27 | block_attribute_null, $01 | block_attribute_null, $2D | block_attribute_null, $01 | block_attribute_null ;34
	.BYTE $27 | block_attribute_null, $01 | block_attribute_null, $00 | block_attribute_null, $27 | block_attribute_null ;35
	.BYTE $26 | block_attribute_null, $00 | block_attribute_null, $25 | block_attribute_null, $00 | block_attribute_null ;36
	.BYTE $25 | block_attribute_null, $00 | block_attribute_null, $01 | block_attribute_null, $25 | block_attribute_null ;37
	.BYTE $00 | block_attribute_null, $00 | block_attribute_null, $25 | block_attribute_null, $2D | block_attribute_null ;38
	.BYTE $35 | block_attribute_null, $00 | block_attribute_null, $36 | block_attribute_null, $00 | block_attribute_null ;39
	.BYTE $26 | block_attribute_null, $27 | block_attribute_null, $00 | block_attribute_null, $00 | block_attribute_null ;3A
	.BYTE $00 | block_attribute_null, $00 | block_attribute_null, $2D | block_attribute_null, $25 | block_attribute_null ;3B
	.BYTE $3D | block_attribute_wall, $2D | block_attribute_null, $1E | block_attribute_wall, $01 | block_attribute_null ;3C
	.BYTE $01 | block_attribute_wall, $01 | block_attribute_null, $01 | block_attribute_wall, $01 | block_attribute_null ;3D
	.BYTE $25 | block_attribute_null, $2D | block_attribute_null, $01 | block_attribute_null, $01 | block_attribute_null ;3E
	.BYTE $1F | block_attribute_wall, $01 | block_attribute_null, $3D | block_attribute_wall, $27 | block_attribute_null ;3F
	.BYTE $1F | block_attribute_wall, $26 | block_attribute_null, $3D | block_attribute_wall, $00 | block_attribute_null ;40
	.BYTE $27 | block_attribute_null, $26 | block_attribute_null, $00 | block_attribute_null, $00 | block_attribute_null ;41
	.BYTE $01 | block_attribute_null, $01 | block_attribute_null, $26 | block_attribute_null, $27 | block_attribute_null ;42
	.BYTE $01 | block_attribute_wall, $26 | block_attribute_null, $01 | block_attribute_wall, $25 | block_attribute_null ;43
	.BYTE $3D | block_attribute_wall, $00 | block_attribute_null, $1E | block_attribute_wall, $25 | block_attribute_null ;44
	.BYTE $1E | block_attribute_wall, $25 | block_attribute_null, $01 | block_attribute_wall, $01 | block_attribute_null ;45
	.BYTE $01 | block_attribute_wall, $01 | block_attribute_null, $01 | block_attribute_null, $01 | block_attribute_null ;46
	.BYTE $2E | block_attribute_null, $01 | block_attribute_null, $2F | block_attribute_null, $26 | block_attribute_null ;47
	.BYTE $1E | block_attribute_wall, $01 | block_attribute_null, $01 | block_attribute_wall, $01 | block_attribute_null ;48
	.BYTE $01 | block_attribute_null, $01 | block_attribute_null, $27 | block_attribute_null, $26 | block_attribute_null ;49
	.BYTE $01 | block_attribute_wall, $01 | block_attribute_null, $27 | block_attribute_null, $26 | block_attribute_null ;4A
	.BYTE $01 | block_attribute_null, $01 | block_attribute_null, $01 | block_attribute_wall, $01 | block_attribute_null ;4B
	.BYTE $3D | block_attribute_wall, $00 | block_attribute_null, $3D | block_attribute_wall, $2D | block_attribute_null ;4C
	.BYTE $00 | block_attribute_null, $00 | block_attribute_null, $3D | block_attribute_wall, $3D | block_attribute_wall ;4D
	.BYTE $1D | block_attribute_wall, $00 | block_attribute_null, $3D | block_attribute_wall, $00 | block_attribute_null ;4E
	.BYTE $01 | block_attribute_null, $01 | block_attribute_null, $01 | block_attribute_wall, $26 | block_attribute_null ;4F
	.BYTE $1D | block_attribute_wall, $3D | block_attribute_wall, $00 | block_attribute_null, $00 | block_attribute_null ;50
	.BYTE $00 | block_attribute_null, $00 | block_attribute_null, $25 | block_attribute_null, $2D | block_attribute_null ;51
	.BYTE $3D | block_attribute_wall, $27 | block_attribute_null, $3D | block_attribute_wall, $00 | block_attribute_null ;52
	.BYTE $01 | block_attribute_null, $01 | block_attribute_null, $1F | block_attribute_wall, $01 | block_attribute_null ;53
	.BYTE $01 | block_attribute_null, $01 | block_attribute_null, $01 | block_attribute_null, $26 | block_attribute_null ;54
	.BYTE $3F | block_attribute_null, $3E | block_attribute_null, $3E | block_attribute_null, $3E | block_attribute_null ;55
	.BYTE $3D | block_attribute_wall, $3D | block_attribute_wall, $00 | block_attribute_null, $00 | block_attribute_null ;56
	.BYTE $1D | block_attribute_wall, $00 | block_attribute_null, $37 | block_attribute_wall, $00 | block_attribute_null ;57
	.BYTE $3D | block_attribute_wall, $00 | block_attribute_null, $1D | block_attribute_wall, $00 | block_attribute_null ;58
	.BYTE $37 | block_attribute_wall, $00 | block_attribute_null, $3D | block_attribute_wall, $00 | block_attribute_null ;59
	.BYTE $00 | block_attribute_null, $27 | block_attribute_null, $00 | block_attribute_null, $2E | block_attribute_null ;5A
	.BYTE $00 | block_attribute_null, $2F | block_attribute_null, $00 | block_attribute_null, $2D | block_attribute_null ;5B
	.BYTE $00 | block_attribute_null, $00 | block_attribute_null, $00 | block_attribute_null, $2E | block_attribute_null ;5C
	.BYTE $00 | block_attribute_null, $2F | block_attribute_null, $00 | block_attribute_null, $00 | block_attribute_null ;5D
	.BYTE $27 | block_attribute_null, $01 | block_attribute_null, $2E | block_attribute_null, $01 | block_attribute_null ;5E
	.BYTE $2F | block_attribute_null, $01 | block_attribute_null, $2D | block_attribute_null, $01 | block_attribute_null ;5F
	.BYTE $26 | block_attribute_null, $00 | block_attribute_null, $35 | block_attribute_null, $00 | block_attribute_null ;60
	.BYTE $36 | block_attribute_null, $00 | block_attribute_null, $25 | block_attribute_null, $00 | block_attribute_null ;61
	.BYTE $00 | block_attribute_null, $00 | block_attribute_null, $35 | block_attribute_null, $00 | block_attribute_null ;62
	.BYTE $36 | block_attribute_null, $00 | block_attribute_null, $00 | block_attribute_null, $00 | block_attribute_null ;63
	.BYTE $01 | block_attribute_null, $26 | block_attribute_null, $01 | block_attribute_null, $35 | block_attribute_null ;64
	.BYTE $01 | block_attribute_null, $36 | block_attribute_null, $01 | block_attribute_null, $25 | block_attribute_null ;65
	.BYTE $25 | block_attribute_null, $00 | block_attribute_null, $01 | block_attribute_null, $35 | block_attribute_null ;66
	.BYTE $01 | block_attribute_null, $36 | block_attribute_null, $26 | block_attribute_null, $00 | block_attribute_null ;67
	.BYTE $00 | block_attribute_null, $2D | block_attribute_null, $2E | block_attribute_null, $01 | block_attribute_null ;68
	.BYTE $2F | block_attribute_null, $01 | block_attribute_null, $00 | block_attribute_null, $27 | block_attribute_null ;69
	.BYTE $00 | block_attribute_null, $00 | block_attribute_null, $18 | block_attribute_wall, $20 | block_attribute_wall ;6A
	.BYTE $19 | block_attribute_wall, $21 | block_attribute_wall, $1A | block_attribute_wall, $22 | block_attribute_wall ;6B
	.BYTE $1B | block_attribute_wall, $23 | block_attribute_wall, $1C | block_attribute_wall, $24 | block_attribute_wall ;6C
	.BYTE $00 | block_attribute_null, $00 | block_attribute_null, $18 | block_attribute_wall, $20 | block_attribute_wall ;6D
	.BYTE $19 | block_attribute_wall, $21 | block_attribute_wall, $1A | block_attribute_wall, $22 | block_attribute_wall ;6E
	.BYTE $1B | block_attribute_wall, $23 | block_attribute_wall, $1C | block_attribute_wall, $24 | block_attribute_wall ;6F
	.BYTE $18 | block_attribute_wall, $20 | block_attribute_wall, $19 | block_attribute_wall, $21 | block_attribute_wall ;70
	.BYTE $1A | block_attribute_wall, $22 | block_attribute_wall, $1B | block_attribute_wall, $23 | block_attribute_wall ;71
	.BYTE $00 | block_attribute_null, $00 | block_attribute_null, $28 | block_attribute_wall, $30 | block_attribute_wall ;72
	.BYTE $29 | block_attribute_wall, $31 | block_attribute_wall, $2A | block_attribute_wall, $32 | block_attribute_wall ;73
	.BYTE $2B | block_attribute_wall, $33 | block_attribute_wall, $2C | block_attribute_wall, $34 | block_attribute_wall ;74
	.BYTE $00 | block_attribute_null, $00 | block_attribute_null, $28 | block_attribute_wall, $30 | block_attribute_wall ;75
	.BYTE $29 | block_attribute_wall, $31 | block_attribute_wall, $2A | block_attribute_wall, $32 | block_attribute_wall ;76
	.BYTE $2B | block_attribute_wall, $33 | block_attribute_wall, $2C | block_attribute_wall, $34 | block_attribute_wall ;77
	.BYTE $28 | block_attribute_wall, $30 | block_attribute_wall, $29 | block_attribute_wall, $31 | block_attribute_wall ;78
	.BYTE $2A | block_attribute_wall, $32 | block_attribute_wall, $2B | block_attribute_wall, $33 | block_attribute_wall ;79
	.BYTE $00 | block_attribute_null, $00 | block_attribute_null, $38 | block_attribute_wall, $00 | block_attribute_null ;7A
	.BYTE $39 | block_attribute_wall, $00 | block_attribute_null, $3A | block_attribute_wall, $00 | block_attribute_null ;7B
	.BYTE $3B | block_attribute_wall, $00 | block_attribute_null, $3C | block_attribute_wall, $00 | block_attribute_null ;7C
	.BYTE $00 | block_attribute_null, $00 | block_attribute_null, $38 | block_attribute_wall, $00 | block_attribute_null ;7D
	.BYTE $39 | block_attribute_wall, $00 | block_attribute_null, $3A | block_attribute_wall, $00 | block_attribute_null ;7E
	.BYTE $3B | block_attribute_wall, $00 | block_attribute_null, $3C | block_attribute_wall, $00 | block_attribute_null ;7F
	.BYTE $38 | block_attribute_wall, $00 | block_attribute_null, $39 | block_attribute_wall, $00 | block_attribute_null ;80
	.BYTE $3A | block_attribute_wall, $00 | block_attribute_null, $3B | block_attribute_wall, $00 | block_attribute_null ;81
	.BYTE $3C | block_attribute_wall, $00 | block_attribute_null, $00 | block_attribute_null, $00 | block_attribute_null ;82
	.BYTE $1C | block_attribute_wall, $24 | block_attribute_wall, $00 | block_attribute_null, $00 | block_attribute_null ;83
	.BYTE $2C | block_attribute_wall, $34 | block_attribute_wall, $00 | block_attribute_null, $00 | block_attribute_null ;84
	.BYTE $18 | block_attribute_wall, $20 | block_attribute_wall, $19 | block_attribute_wall, $21 | block_attribute_wall ;85
	.BYTE $1A | block_attribute_wall, $22 | block_attribute_wall, $1B | block_attribute_wall, $23 | block_attribute_wall ;86
	.BYTE $1C | block_attribute_wall, $24 | block_attribute_wall, $00 | block_attribute_null, $00 | block_attribute_null ;87
	.BYTE $28 | block_attribute_wall, $30 | block_attribute_wall, $29 | block_attribute_wall, $31 | block_attribute_wall ;88
	.BYTE $2A | block_attribute_wall, $32 | block_attribute_wall, $2B | block_attribute_wall, $33 | block_attribute_wall ;89
	.BYTE $2C | block_attribute_wall, $34 | block_attribute_wall, $00 | block_attribute_null, $00 | block_attribute_null ;8A
	.BYTE $38 | block_attribute_wall, $00 | block_attribute_null, $39 | block_attribute_wall, $00 | block_attribute_null ;8B
	.BYTE $3A | block_attribute_wall, $00 | block_attribute_null, $3B | block_attribute_wall, $00 | block_attribute_null ;8C
	.BYTE $3C | block_attribute_wall, $00 | block_attribute_null, $00 | block_attribute_null, $00 | block_attribute_null ;8D
	.BYTE $00 | block_attribute_null, $00 | block_attribute_null, $00 | block_attribute_null, $3D | block_attribute_wall ;8E
	.BYTE $00 | block_attribute_null, $00 | block_attribute_null, $09 | block_attribute_wall, $0A | block_attribute_wall ;8F
	.BYTE $1A | block_attribute_wall, $1C | block_attribute_wall, $1B | block_attribute_wall, $1D | block_attribute_wall ;90
	.BYTE $24 | block_attribute_null, $24 | block_attribute_null, $24 | block_attribute_null, $24 | block_attribute_null ;91
	.BYTE $24 | block_attribute_null, $18 | block_attribute_wall, $24 | block_attribute_null, $19 | block_attribute_wall ;92
	.BYTE $18 | block_attribute_wall, $1C | block_attribute_wall, $19 | block_attribute_wall, $1D | block_attribute_wall ;93
	.BYTE $24 | block_attribute_null, $22 | block_attribute_null, $24 | block_attribute_null, $22 | block_attribute_null ;94
	.BYTE $23 | block_attribute_3,    $00 | block_attribute_null, $23 | block_attribute_3,    $00 | block_attribute_null ;95
	.BYTE $28 | block_attribute_wall, $30 | block_attribute_wall, $29 | block_attribute_wall, $31 | block_attribute_wall ;96
	.BYTE $2A | block_attribute_wall, $32 | block_attribute_wall, $2B | block_attribute_wall, $33 | block_attribute_wall ;97
	.BYTE $24 | block_attribute_null, $24 | block_attribute_null, $1A | block_attribute_wall, $1C | block_attribute_wall ;98
	.BYTE $1B | block_attribute_wall, $1D | block_attribute_wall, $1A | block_attribute_wall, $1C | block_attribute_wall ;99
	.BYTE $24 | block_attribute_null, $24 | block_attribute_null, $1E | block_attribute_wall, $25 | block_attribute_null ;9A
	.BYTE $1F | block_attribute_wall, $25 | block_attribute_null, $1E | block_attribute_wall, $25 | block_attribute_null ;9B
	.BYTE $1B | block_attribute_wall, $1D | block_attribute_wall, $24 | block_attribute_null, $24 | block_attribute_null ;9C
	.BYTE $1B | block_attribute_wall, $1D | block_attribute_wall, $02 | block_attribute_2,    $02 | block_attribute_2    ;9D
	.BYTE $2C | block_attribute_wall, $34 | block_attribute_wall, $2D | block_attribute_wall, $35 | block_attribute_wall ;9E
	.BYTE $2E | block_attribute_wall, $36 | block_attribute_wall, $2F | block_attribute_wall, $37 | block_attribute_wall ;9F
	.BYTE $1C | block_attribute_wall, $1A | block_attribute_wall, $1D | block_attribute_wall, $1B | block_attribute_wall ;A0
	.BYTE $20 | block_attribute_wall, $25 | block_attribute_null, $20 | block_attribute_wall, $25 | block_attribute_null ;A1
	.BYTE $24 | block_attribute_null, $20 | block_attribute_wall, $24 | block_attribute_null, $20 | block_attribute_wall ;A2
	.BYTE $21 | block_attribute_wall, $21 | block_attribute_wall, $02 | block_attribute_2,    $02 | block_attribute_2    ;A3
	.BYTE $1F | block_attribute_wall, $25 | block_attribute_null, $02 | block_attribute_2,    $02 | block_attribute_2    ;A4
	.BYTE $1B | block_attribute_wall, $1D | block_attribute_wall, $28 | block_attribute_wall, $30 | block_attribute_wall ;A5
	.BYTE $29 | block_attribute_wall, $31 | block_attribute_wall, $2A | block_attribute_wall, $32 | block_attribute_wall ;A6
	.BYTE $2B | block_attribute_wall, $33 | block_attribute_wall, $1A | block_attribute_wall, $1C | block_attribute_wall ;A7
	.BYTE $24 | block_attribute_null, $20 | block_attribute_wall, $24 | block_attribute_null, $02 | block_attribute_2    ;A8
	.BYTE $24 | block_attribute_null, $21 | block_attribute_wall, $24 | block_attribute_null, $02 | block_attribute_2    ;A9
	.BYTE $25 | block_attribute_null, $24 | block_attribute_null, $25 | block_attribute_null, $24 | block_attribute_null ;AA
	.BYTE $25 | block_attribute_null, $24 | block_attribute_null, $02 | block_attribute_2,    $24 | block_attribute_null ;AB
	.BYTE $24 | block_attribute_null, $20 | block_attribute_wall, $02 | block_attribute_2,    $20 | block_attribute_wall ;AC
	.BYTE $1B | block_attribute_wall, $1D | block_attribute_wall, $2C | block_attribute_wall, $34 | block_attribute_wall ;AD
	.BYTE $2D | block_attribute_wall, $35 | block_attribute_wall, $2E | block_attribute_wall, $36 | block_attribute_wall ;AE
	.BYTE $2F | block_attribute_wall, $37 | block_attribute_wall, $1A | block_attribute_wall, $1C | block_attribute_wall ;AF
	.BYTE $24 | block_attribute_null, $24 | block_attribute_null, $02 | block_attribute_2,    $02 | block_attribute_2    ;B0
	.BYTE $20 | block_attribute_wall, $25 | block_attribute_null, $02 | block_attribute_2,    $02 | block_attribute_2    ;B1
	.BYTE $24 | block_attribute_null, $24 | block_attribute_null, $24 | block_attribute_null, $02 | block_attribute_2    ;B2
	.BYTE $24 | block_attribute_null, $02 | block_attribute_2,    $24 | block_attribute_null, $24 | block_attribute_null ;B3
	.BYTE $02 | block_attribute_2,    $02 | block_attribute_2,    $24 | block_attribute_null, $24 | block_attribute_null ;B4
	.BYTE $24 | block_attribute_null, $02 | block_attribute_2,    $24 | block_attribute_null, $21 | block_attribute_wall ;B5
	.BYTE $02 | block_attribute_2,    $20 | block_attribute_wall, $24 | block_attribute_null, $20 | block_attribute_wall ;B6
	.BYTE $02 | block_attribute_2,    $02 | block_attribute_2,    $21 | block_attribute_wall, $21 | block_attribute_wall ;B7
	.BYTE $25 | block_attribute_null, $24 | block_attribute_null, $02 | block_attribute_2,    $02 | block_attribute_2    ;B8
	.BYTE $24 | block_attribute_null, $20 | block_attribute_wall, $24 | block_attribute_null, $21 | block_attribute_wall ;B9
	.BYTE $02 | block_attribute_2,    $02 | block_attribute_2,    $25 | block_attribute_null, $24 | block_attribute_null ;BA
	.BYTE $25 | block_attribute_null, $24 | block_attribute_null, $21 | block_attribute_wall, $21 | block_attribute_wall ;BB
	.BYTE $02 | block_attribute_2,    $02 | block_attribute_2,    $20 | block_attribute_wall, $25 | block_attribute_null ;BC
	.BYTE $20 | block_attribute_wall, $25 | block_attribute_null, $21 | block_attribute_wall, $21 | block_attribute_wall ;BD
	.BYTE $02 | block_attribute_2,    $02 | block_attribute_2,    $24 | block_attribute_null, $20 | block_attribute_wall ;BE
	.BYTE $24 | block_attribute_null, $20 | block_attribute_wall, $21 | block_attribute_wall, $21 | block_attribute_wall ;BF
	.BYTE $1E | block_attribute_wall, $25 | block_attribute_null, $1F | block_attribute_wall, $25 | block_attribute_null ;C0
	.BYTE $21 | block_attribute_wall, $21 | block_attribute_wall, $24 | block_attribute_null, $24 | block_attribute_null ;C1
	.BYTE $24 | block_attribute_null, $24 | block_attribute_null, $21 | block_attribute_wall, $21 | block_attribute_wall ;C2
	.BYTE $24 | block_attribute_null, $24 | block_attribute_null, $24 | block_attribute_null, $20 | block_attribute_wall ;C3
	.BYTE $24 | block_attribute_null, $24 | block_attribute_null, $25 | block_attribute_null, $24 | block_attribute_null ;C4
	.BYTE $24 | block_attribute_null, $20 | block_attribute_wall, $24 | block_attribute_null, $24 | block_attribute_null ;C5
	.BYTE $25 | block_attribute_null, $24 | block_attribute_null, $24 | block_attribute_null, $24 | block_attribute_null ;C6
	.BYTE $00 | block_attribute_null, $19 | block_attribute_wall, $00 | block_attribute_null, $00 | block_attribute_null ;C7
	.BYTE $1D | block_attribute_wall, $1B | block_attribute_wall, $24 | block_attribute_null, $24 | block_attribute_null ;C8
	.BYTE $27 | block_attribute_wall, $26 | block_attribute_wall, $1C | block_attribute_wall, $1E | block_attribute_wall ;C9
	.BYTE $27 | block_attribute_wall, $1F | block_attribute_wall, $1C | block_attribute_wall, $1A | block_attribute_wall ;CA
	.BYTE $21 | block_attribute_wall, $21 | block_attribute_wall, $18 | block_attribute_wall, $1A | block_attribute_wall ;CB
	.BYTE $21 | block_attribute_wall, $21 | block_attribute_wall, $1C | block_attribute_wall, $1A | block_attribute_wall ;CC
	.BYTE $19 | block_attribute_wall, $26 | block_attribute_wall, $00 | block_attribute_null, $19 | block_attribute_wall ;CD
	.BYTE $1D | block_attribute_wall, $26 | block_attribute_wall, $18 | block_attribute_wall, $1A | block_attribute_wall ;CE
	.BYTE $19 | block_attribute_wall, $1B | block_attribute_wall, $1C | block_attribute_wall, $1A | block_attribute_wall ;CF
	.BYTE $1D | block_attribute_wall, $1B | block_attribute_wall, $1C | block_attribute_wall, $1A | block_attribute_wall ;D0
	.BYTE $1D | block_attribute_wall, $1B | block_attribute_wall, $00 | block_attribute_null, $00 | block_attribute_null ;D1
	.BYTE $00 | block_attribute_null, $00 | block_attribute_null, $1C | block_attribute_wall, $1A | block_attribute_wall ;D2
	.BYTE $1D | block_attribute_wall, $1B | block_attribute_wall, $18 | block_attribute_wall, $1A | block_attribute_wall ;D3
	.BYTE $19 | block_attribute_wall, $1B | block_attribute_wall, $18 | block_attribute_wall, $1A | block_attribute_wall ;D4
	.BYTE $00 | block_attribute_null, $00 | block_attribute_null, $1C | block_attribute_wall, $1E | block_attribute_wall ;D5
	.BYTE $1D | block_attribute_wall, $1F | block_attribute_wall, $1C | block_attribute_wall, $1E | block_attribute_wall ;D6
	.BYTE $1D | block_attribute_wall, $1F | block_attribute_wall, $00 | block_attribute_null, $00 | block_attribute_null ;D7
	.BYTE $1F | block_attribute_wall, $00 | block_attribute_null, $1F | block_attribute_wall, $00 | block_attribute_null ;D8
	.BYTE $19 | block_attribute_wall, $1B | block_attribute_wall, $02 | block_attribute_2,    $02 | block_attribute_2    ;D9
	.BYTE $1D | block_attribute_wall, $1B | block_attribute_wall, $02 | block_attribute_2,    $02 | block_attribute_2    ;DA
	.BYTE $1F | block_attribute_wall, $00 | block_attribute_null, $02 | block_attribute_2,    $02 | block_attribute_2    ;DB
	.BYTE $1C | block_attribute_wall, $1E | block_attribute_wall, $1D | block_attribute_wall, $1F | block_attribute_wall ;DC
	.BYTE $1D | block_attribute_wall, $1B | block_attribute_wall, $1C | block_attribute_wall, $28 | block_attribute_wall ;DD
	.BYTE $1D | block_attribute_wall, $29 | block_attribute_wall, $1C | block_attribute_wall, $2A | block_attribute_wall ;DE
	.BYTE $1D | block_attribute_wall, $2B | block_attribute_wall, $1C | block_attribute_wall, $1A | block_attribute_wall ;DF
	.BYTE $1B | block_attribute_wall, $1D | block_attribute_wall, $00 | block_attribute_null, $00 | block_attribute_null ;E0
	.BYTE $1B | block_attribute_wall, $1D | block_attribute_wall, $1E | block_attribute_wall, $00 | block_attribute_null ;E1
	.BYTE $20 | block_attribute_wall, $00 | block_attribute_null, $00 | block_attribute_null, $00 | block_attribute_null ;E2
	.BYTE $00 | block_attribute_null, $00 | block_attribute_null, $00 | block_attribute_null, $20 | block_attribute_wall ;E3
	.BYTE $1E | block_attribute_wall, $00 | block_attribute_null, $1D | block_attribute_wall, $1A | block_attribute_wall ;E4
	.BYTE $1D | block_attribute_wall, $1B | block_attribute_wall, $30 | block_attribute_wall, $2C | block_attribute_wall ;E5
	.BYTE $31 | block_attribute_wall, $2D | block_attribute_wall, $32 | block_attribute_wall, $2E | block_attribute_wall ;E6
	.BYTE $33 | block_attribute_wall, $2F | block_attribute_wall, $1C | block_attribute_wall, $1A | block_attribute_wall ;E7
	.BYTE $1F | block_attribute_wall, $00 | block_attribute_null, $00 | block_attribute_null, $00 | block_attribute_null ;E8
	.BYTE $1B | block_attribute_wall, $1F | block_attribute_wall, $00 | block_attribute_null, $00 | block_attribute_null ;E9
	.BYTE $00 | block_attribute_null, $20 | block_attribute_wall, $00 | block_attribute_null, $20 | block_attribute_wall ;EA
	.BYTE $27 | block_attribute_wall, $1F | block_attribute_wall, $00 | block_attribute_null, $00 | block_attribute_null ;EB
	.BYTE $00 | block_attribute_null, $00 | block_attribute_null, $1E | block_attribute_wall, $00 | block_attribute_null ;EC
	.BYTE $1D | block_attribute_wall, $1B | block_attribute_wall, $34 | block_attribute_wall, $1A | block_attribute_wall ;ED
	.BYTE $35 | block_attribute_wall, $1B | block_attribute_wall, $36 | block_attribute_wall, $1A | block_attribute_wall ;EE
	.BYTE $37 | block_attribute_wall, $1B | block_attribute_wall, $1C | block_attribute_wall, $1A | block_attribute_wall ;EF
	.BYTE $22 | block_attribute_null, $23 | block_attribute_3,    $22 | block_attribute_null, $23 | block_attribute_3    ;F0
	.BYTE $21 | block_attribute_wall, $21 | block_attribute_wall, $00 | block_attribute_null, $00 | block_attribute_null ;F1
	.BYTE $00 | block_attribute_null, $00 | block_attribute_null, $21 | block_attribute_wall, $21 | block_attribute_wall ;F2
	.BYTE $00 | block_attribute_null, $22 | block_attribute_null, $00 | block_attribute_null, $22 | block_attribute_null ;F3
	.BYTE $1D | block_attribute_wall, $26 | block_attribute_wall, $1C | block_attribute_wall, $1A | block_attribute_wall ;F4
	.BYTE $27 | block_attribute_wall, $1B | block_attribute_wall, $1C | block_attribute_wall, $1A | block_attribute_wall ;F5
	.BYTE $19 | block_attribute_wall, $26 | block_attribute_wall, $18 | block_attribute_wall, $1A | block_attribute_wall ;F6
	.BYTE $27 | block_attribute_wall, $26 | block_attribute_wall, $1C | block_attribute_wall, $1A | block_attribute_wall ;F7
	.BYTE $27 | block_attribute_wall, $1F | block_attribute_wall, $1C | block_attribute_wall, $1E | block_attribute_wall ;F8
	.BYTE $38 | block_attribute_wall, $00 | block_attribute_null, $38 | block_attribute_wall, $00 | block_attribute_null ;F9
	.BYTE $38 | block_attribute_wall, $38 | block_attribute_wall, $00 | block_attribute_null, $00 | block_attribute_null ;FA
	.BYTE $00 | block_attribute_null, $00 | block_attribute_null, $38 | block_attribute_wall, $38 | block_attribute_wall ;FB
	.BYTE $38 | block_attribute_wall, $38 | block_attribute_wall, $38 | block_attribute_wall, $00 | block_attribute_null ;FC
	.BYTE $38 | block_attribute_wall, $00 | block_attribute_null, $38 | block_attribute_wall, $38 | block_attribute_wall ;FD
	.BYTE $38 | block_attribute_wall, $00 | block_attribute_null, $00 | block_attribute_null, $00 | block_attribute_null ;FE
	.BYTE $00 | block_attribute_null, $00 | block_attribute_null, $38 | block_attribute_wall, $00 | block_attribute_null ;FF