;32x32 blocksets with 16x16 blocksets | block attribute.
;block_attribute 2 and 3 setting see home/blocksets.asm. 
	      ;top left,                  bottom left,                top right,                  bottom right
	.BYTE $00 | block_attribute_null, $00 | block_attribute_null, $00 | block_attribute_null, $00 | block_attribute_null ;00
	.BYTE $00 | block_attribute_2,    $00 | block_attribute_2,    $00 | block_attribute_2,    $00 | block_attribute_2    ;01
	.BYTE $1C | block_attribute_null, $1D | block_attribute_null, $1D | block_attribute_null, $1C | block_attribute_null ;02
	.BYTE $04 | block_attribute_3,    $1B | block_attribute_2,    $04 | block_attribute_3,    $1B | block_attribute_2    ;03
	.BYTE $1C | block_attribute_null, $18 | block_attribute_wall, $1D | block_attribute_null, $18 | block_attribute_wall ;04
	.BYTE $18 | block_attribute_wall, $27 | block_attribute_null, $18 | block_attribute_wall, $27 | block_attribute_null ;05
	.BYTE $1C | block_attribute_null, $1C | block_attribute_null, $18 | block_attribute_wall, $27 | block_attribute_null ;06
	.BYTE $18 | block_attribute_wall, $27 | block_attribute_null, $1D | block_attribute_null, $1D | block_attribute_null ;07
	.BYTE $1C | block_attribute_null, $1D | block_attribute_null, $1D | block_attribute_null, $18 | block_attribute_wall ;08
	.BYTE $1C | block_attribute_null, $18 | block_attribute_wall, $1D | block_attribute_null, $1C | block_attribute_null ;09
	.BYTE $27 | block_attribute_null, $1D | block_attribute_null, $27 | block_attribute_null, $1C | block_attribute_null ;0A
	.BYTE $19 | block_attribute_wall, $19 | block_attribute_wall, $1D | block_attribute_null, $1C | block_attribute_null ;0B
	.BYTE $19 | block_attribute_wall, $18 | block_attribute_wall, $1D | block_attribute_null, $18 | block_attribute_wall ;0C
	.BYTE $1C | block_attribute_null, $1D | block_attribute_null, $19 | block_attribute_wall, $19 | block_attribute_wall ;0D
	.BYTE $18 | block_attribute_wall, $27 | block_attribute_null, $18 | block_attribute_wall, $19 | block_attribute_wall ;0E
	.BYTE $1E | block_attribute_2,    $1F | block_attribute_2,    $1E | block_attribute_2,    $1F | block_attribute_2    ;0F
	.BYTE $1C | block_attribute_null, $1D | block_attribute_null, $09 | block_attribute_wall, $0A | block_attribute_wall ;10
	.BYTE $04 | block_attribute_3,    $04 | block_attribute_3,    $04 | block_attribute_3,    $00 | block_attribute_null ;11
	.BYTE $19 | block_attribute_wall, $19 | block_attribute_wall, $00 | block_attribute_2,    $00 | block_attribute_2    ;12
	.BYTE $18 | block_attribute_wall, $27 | block_attribute_null, $18 | block_attribute_wall, $27 | block_attribute_null ;13
	.BYTE $29 | block_attribute_wall, $04 | block_attribute_3,    $29 | block_attribute_wall, $00 | block_attribute_2    ;14
	.BYTE $29 | block_attribute_wall, $00 | block_attribute_2,    $29 | block_attribute_wall, $00 | block_attribute_2    ;15
	.BYTE $00 | block_attribute_2,    $04 | block_attribute_3,    $00 | block_attribute_2,    $00 | block_attribute_2    ;16
	.BYTE $00 | block_attribute_2,    $00 | block_attribute_2,    $00 | block_attribute_2,    $04 | block_attribute_3    ;17
	.BYTE $04 | block_attribute_3,    $00 | block_attribute_2,    $04 | block_attribute_3,    $00 | block_attribute_2    ;18
	.BYTE $04 | block_attribute_3,    $00 | block_attribute_2,    $29 | block_attribute_wall, $04 | block_attribute_3    ;19
	.BYTE $21 | block_attribute_wall, $04 | block_attribute_3,    $29 | block_attribute_wall, $04 | block_attribute_3    ;1A
	.BYTE $29 | block_attribute_wall, $04 | block_attribute_3,    $28 | block_attribute_wall, $21 | block_attribute_wall ;1B
	.BYTE $00 | block_attribute_2,    $00 | block_attribute_2,    $04 | block_attribute_3,    $00 | block_attribute_2    ;1C
	.BYTE $21 | block_attribute_wall, $04 | block_attribute_3,    $04 | block_attribute_3,    $00 | block_attribute_2    ;1D
	.BYTE $04 | block_attribute_3,    $04 | block_attribute_3,    $00 | block_attribute_2,    $00 | block_attribute_2    ;1E
	.BYTE $00 | block_attribute_2,    $00 | block_attribute_2,    $04 | block_attribute_3,    $04 | block_attribute_3    ;1F
	.BYTE $01 | block_attribute_null, $01 | block_attribute_null, $01 | block_attribute_null, $01 | block_attribute_null ;20
	.BYTE $22 | block_attribute_2,    $2A | block_attribute_2,    $23 | block_attribute_2,    $2B | block_attribute_2    ;21
	.BYTE $24 | block_attribute_2,    $2C | block_attribute_2,    $25 | block_attribute_2,    $2D | block_attribute_2    ;22
	.BYTE $26 | block_attribute_2,    $2E | block_attribute_2,    $00 | block_attribute_2,    $00 | block_attribute_2    ;23
	.BYTE $19 | block_attribute_wall, $19 | block_attribute_wall, $27 | block_attribute_null, $1C | block_attribute_null ;24
	.BYTE $27 | block_attribute_null, $1D | block_attribute_null, $1D | block_attribute_null, $1C | block_attribute_null ;25
	.BYTE $18 | block_attribute_wall, $19 | block_attribute_wall, $18 | block_attribute_wall, $27 | block_attribute_null ;26
	.BYTE $1C | block_attribute_null, $1D | block_attribute_null, $27 | block_attribute_null, $1C | block_attribute_null ;27
	.BYTE $00 | block_attribute_2,    $00 | block_attribute_2,    $00 | block_attribute_2,    $39 | block_attribute_2    ;28
	.BYTE $32 | block_attribute_2,    $3A | block_attribute_2,    $33 | block_attribute_2,    $3B | block_attribute_2    ;29
	.BYTE $34 | block_attribute_2,    $3C | block_attribute_2,    $35 | block_attribute_2,    $3D | block_attribute_2    ;2A
	.BYTE $36 | block_attribute_2,    $3E | block_attribute_2,    $37 | block_attribute_2,    $3F | block_attribute_2    ;2B
	.BYTE $27 | block_attribute_null, $1D | block_attribute_null, $19 | block_attribute_wall, $19 | block_attribute_wall ;2C
	.BYTE $1C | block_attribute_null, $18 | block_attribute_wall, $19 | block_attribute_wall, $18 | block_attribute_wall ;2D
	.BYTE $00 | block_attribute_2,    $00 | block_attribute_2,    $19 | block_attribute_wall, $19 | block_attribute_wall ;2E
	.BYTE $1E | block_attribute_2,    $1F | block_attribute_2,    $08 | block_attribute_2,    $08 | block_attribute_2    ;2F
	.BYTE $1C | block_attribute_null, $1C | block_attribute_null, $09 | block_attribute_wall, $09 | block_attribute_wall ;30
	.BYTE $07 | block_attribute_wall, $0C | block_attribute_wall, $07 | block_attribute_wall, $0D | block_attribute_wall ;31
	.BYTE $0E | block_attribute_wall, $0B | block_attribute_wall, $0F | block_attribute_wall, $0B | block_attribute_wall ;32
	.BYTE $00 | block_attribute_2,    $00 | block_attribute_2,    $08 | block_attribute_2,    $08 | block_attribute_2    ;33
	.BYTE $1B | block_attribute_2,    $1A | block_attribute_2,    $1B | block_attribute_2,    $1A | block_attribute_2    ;34
	.BYTE $1A | block_attribute_2,    $1A | block_attribute_2,    $1A | block_attribute_2,    $1A | block_attribute_2    ;35
	.BYTE $1B | block_attribute_2,    $1A | block_attribute_2,    $08 | block_attribute_2,    $08 | block_attribute_2    ;36
	.BYTE $1A | block_attribute_2,    $1A | block_attribute_2,    $08 | block_attribute_2,    $08 | block_attribute_2    ;37
	.BYTE $28 | block_attribute_wall, $21 | block_attribute_wall, $04 | block_attribute_3,    $1B | block_attribute_2    ;38
	.BYTE $28 | block_attribute_wall, $28 | block_attribute_wall, $1A | block_attribute_2,    $1A | block_attribute_2    ;39
	.BYTE $04 | block_attribute_3,    $1B | block_attribute_2,    $28 | block_attribute_wall, $28 | block_attribute_wall ;3A
	.BYTE $1A | block_attribute_2,    $1A | block_attribute_2,    $28 | block_attribute_wall, $28 | block_attribute_wall ;3B
	.BYTE $1B | block_attribute_2,    $1A | block_attribute_2,    $1A | block_attribute_2,    $1A | block_attribute_2    ;3C
	.BYTE $20 | block_attribute_wall, $28 | block_attribute_wall, $1A | block_attribute_2,    $1A | block_attribute_2    ;3D
	.BYTE $19 | block_attribute_wall, $19 | block_attribute_wall, $1E | block_attribute_2,    $1F | block_attribute_2    ;3E
	.BYTE $1E | block_attribute_2,    $1F | block_attribute_2,    $19 | block_attribute_wall, $19 | block_attribute_wall ;3F
	.BYTE $18 | block_attribute_wall, $19 | block_attribute_wall, $18 | block_attribute_wall, $00 | block_attribute_2    ;40
	.BYTE $18 | block_attribute_wall, $00 | block_attribute_2,    $18 | block_attribute_wall, $19 | block_attribute_wall ;41
	.BYTE $00 | block_attribute_2,    $18 | block_attribute_wall, $19 | block_attribute_wall, $18 | block_attribute_wall ;42
	.BYTE $18 | block_attribute_wall, $19 | block_attribute_wall, $18 | block_attribute_wall, $19 | block_attribute_wall ;43
	.BYTE $19 | block_attribute_wall, $19 | block_attribute_wall, $19 | block_attribute_wall, $19 | block_attribute_wall ;44
	.BYTE $19 | block_attribute_wall, $00 | block_attribute_2,    $19 | block_attribute_wall, $00 | block_attribute_2    ;45
	.BYTE $18 | block_attribute_wall, $19 | block_attribute_wall, $18 | block_attribute_wall, $19 | block_attribute_wall ;46
	.BYTE $19 | block_attribute_wall, $29 | block_attribute_wall, $19 | block_attribute_wall, $29 | block_attribute_wall ;47
	.BYTE $00 | block_attribute_2,    $00 | block_attribute_2,    $30 | block_attribute_wall, $38 | block_attribute_2    ;48
	.BYTE $00 | block_attribute_2,    $00 | block_attribute_2,    $31 | block_attribute_2,    $00 | block_attribute_2    ;49
	.BYTE $30 | block_attribute_wall, $38 | block_attribute_2,    $04 | block_attribute_3,    $00 | block_attribute_2    ;4A
	.BYTE $31 | block_attribute_2,    $00 | block_attribute_2,    $00 | block_attribute_2,    $00 | block_attribute_2    ;4B
	.BYTE $04 | block_attribute_3,    $00 | block_attribute_2,    $30 | block_attribute_wall, $38 | block_attribute_2    ;4C
	.BYTE $18 | block_attribute_wall, $00 | block_attribute_2,    $18 | block_attribute_wall, $00 | block_attribute_2    ;4D
	.BYTE $00 | block_attribute_2,    $18 | block_attribute_wall, $00 | block_attribute_2,    $18 | block_attribute_wall ;4E
	.BYTE $29 | block_attribute_wall, $27 | block_attribute_null, $21 | block_attribute_wall, $27 | block_attribute_null ;4F
	.BYTE $20 | block_attribute_wall, $28 | block_attribute_wall, $18 | block_attribute_wall, $29 | block_attribute_wall ;50
	.BYTE $18 | block_attribute_wall, $29 | block_attribute_wall, $20 | block_attribute_wall, $28 | block_attribute_wall ;51
	.BYTE $18 | block_attribute_wall, $29 | block_attribute_wall, $18 | block_attribute_wall, $29 | block_attribute_wall ;52
	.BYTE $20 | block_attribute_wall, $28 | block_attribute_wall, $20 | block_attribute_wall, $28 | block_attribute_wall ;53
	.BYTE $19 | block_attribute_wall, $19 | block_attribute_wall, $18 | block_attribute_wall, $29 | block_attribute_wall ;54
	.BYTE $20 | block_attribute_wall, $28 | block_attribute_wall, $18 | block_attribute_wall, $19 | block_attribute_wall ;55
	.BYTE $18 | block_attribute_wall, $19 | block_attribute_wall, $20 | block_attribute_wall, $28 | block_attribute_wall ;56
	.BYTE $19 | block_attribute_wall, $29 | block_attribute_wall, $19 | block_attribute_wall, $29 | block_attribute_wall ;57
	.BYTE $28 | block_attribute_wall, $28 | block_attribute_wall, $29 | block_attribute_wall, $29 | block_attribute_wall ;58
	.BYTE $29 | block_attribute_wall, $29 | block_attribute_wall, $28 | block_attribute_wall, $28 | block_attribute_wall ;59
	.BYTE $29 | block_attribute_wall, $29 | block_attribute_wall, $29 | block_attribute_wall, $29 | block_attribute_wall ;5A
	.BYTE $28 | block_attribute_wall, $28 | block_attribute_wall, $28 | block_attribute_wall, $28 | block_attribute_wall ;5B
	.BYTE $19 | block_attribute_wall, $19 | block_attribute_wall, $29 | block_attribute_wall, $29 | block_attribute_wall ;5C
	.BYTE $28 | block_attribute_wall, $28 | block_attribute_wall, $19 | block_attribute_wall, $19 | block_attribute_wall ;5D
	.BYTE $19 | block_attribute_wall, $19 | block_attribute_wall, $28 | block_attribute_wall, $28 | block_attribute_wall ;5E
	.BYTE $00 | block_attribute_2,    $00 | block_attribute_2,    $20 | block_attribute_wall, $28 | block_attribute_wall ;5F
	.BYTE $28 | block_attribute_wall, $21 | block_attribute_wall, $29 | block_attribute_wall, $29 | block_attribute_wall ;60
	.BYTE $29 | block_attribute_wall, $29 | block_attribute_wall, $28 | block_attribute_wall, $21 | block_attribute_wall ;61
	.BYTE $18 | block_attribute_wall, $29 | block_attribute_wall, $00 | block_attribute_2,    $00 | block_attribute_2    ;62
	.BYTE $28 | block_attribute_wall, $21 | block_attribute_wall, $28 | block_attribute_wall, $21 | block_attribute_wall ;63
	.BYTE $29 | block_attribute_wall, $29 | block_attribute_wall, $00 | block_attribute_2,    $00 | block_attribute_2    ;64
	.BYTE $28 | block_attribute_wall, $21 | block_attribute_wall, $19 | block_attribute_wall, $29 | block_attribute_wall ;65
	.BYTE $19 | block_attribute_wall, $29 | block_attribute_wall, $28 | block_attribute_wall, $21 | block_attribute_wall ;66
	.BYTE $18 | block_attribute_wall, $29 | block_attribute_wall, $28 | block_attribute_wall, $28 | block_attribute_wall ;67
	.BYTE $29 | block_attribute_wall, $04 | block_attribute_3,    $29 | block_attribute_wall, $04 | block_attribute_3    ;68
	.BYTE $21 | block_attribute_wall, $04 | block_attribute_3,    $21 | block_attribute_wall, $04 | block_attribute_3    ;69
	.BYTE $29 | block_attribute_wall, $04 | block_attribute_3,    $21 | block_attribute_wall, $04 | block_attribute_3    ;6A
	.BYTE $29 | block_attribute_wall, $00 | block_attribute_2,    $28 | block_attribute_wall, $30 | block_attribute_wall ;6B
	.BYTE $28 | block_attribute_wall, $30 | block_attribute_wall, $29 | block_attribute_wall, $00 | block_attribute_2    ;6C
	.BYTE $21 | block_attribute_wall, $00 | block_attribute_2,    $29 | block_attribute_wall, $00 | block_attribute_2    ;6D
	.BYTE $29 | block_attribute_wall, $29 | block_attribute_wall, $18 | block_attribute_wall, $29 | block_attribute_wall ;6E
	.BYTE $20 | block_attribute_wall, $28 | block_attribute_wall, $18 | block_attribute_wall, $29 | block_attribute_wall ;6F
	.BYTE $21 | block_attribute_wall, $00 | block_attribute_2,    $29 | block_attribute_wall, $00 | block_attribute_2    ;70
	.BYTE $29 | block_attribute_wall, $00 | block_attribute_2,    $21 | block_attribute_wall, $00 | block_attribute_2    ;71
	.BYTE $29 | block_attribute_wall, $04 | block_attribute_3,    $28 | block_attribute_wall, $30 | block_attribute_wall ;72
	.BYTE $00 | block_attribute_2,    $00 | block_attribute_2,    $38 | block_attribute_2,    $31 | block_attribute_2    ;73
	.BYTE $28 | block_attribute_wall, $30 | block_attribute_wall, $29 | block_attribute_wall, $04 | block_attribute_3    ;74
	.BYTE $38 | block_attribute_2,    $31 | block_attribute_2,    $00 | block_attribute_2,    $00 | block_attribute_2    ;75
	.BYTE $28 | block_attribute_wall, $28 | block_attribute_wall, $18 | block_attribute_wall, $29 | block_attribute_wall ;76
	.BYTE $18 | block_attribute_wall, $29 | block_attribute_wall, $28 | block_attribute_wall, $28 | block_attribute_wall ;77
	.BYTE $18 | block_attribute_wall, $29 | block_attribute_wall, $20 | block_attribute_wall, $28 | block_attribute_wall ;78
	.BYTE $29 | block_attribute_wall, $29 | block_attribute_wall, $28 | block_attribute_wall, $28 | block_attribute_wall ;79
	.BYTE $28 | block_attribute_wall, $28 | block_attribute_wall, $29 | block_attribute_wall, $29 | block_attribute_wall ;7A
	.BYTE $29 | block_attribute_wall, $29 | block_attribute_wall, $28 | block_attribute_wall, $21 | block_attribute_wall ;7B
	.BYTE $29 | block_attribute_wall, $29 | block_attribute_wall, $29 | block_attribute_wall, $29 | block_attribute_wall ;7C
	.BYTE $28 | block_attribute_wall, $21 | block_attribute_wall, $29 | block_attribute_wall, $29 | block_attribute_wall ;7D
	.BYTE $20 | block_attribute_wall, $28 | block_attribute_wall, $18 | block_attribute_wall, $29 | block_attribute_wall ;7E
	.BYTE $18 | block_attribute_wall, $29 | block_attribute_wall, $18 | block_attribute_wall, $29 | block_attribute_wall ;7F
	.BYTE $1E | block_attribute_wall, $00 | block_attribute_null, $02 | block_attribute_2,    $00 | block_attribute_null ;80
	.BYTE $1A | block_attribute_wall, $1C | block_attribute_wall, $26 | block_attribute_wall, $27 | block_attribute_wall ;81
	.BYTE $1A | block_attribute_wall, $1C | block_attribute_wall, $1B | block_attribute_wall, $1D | block_attribute_wall ;82
	.BYTE $1A | block_attribute_wall, $1E | block_attribute_wall, $1B | block_attribute_wall, $1F | block_attribute_wall ;83
	.BYTE $18 | block_attribute_wall, $1C | block_attribute_wall, $19 | block_attribute_wall, $1D | block_attribute_wall ;84
	.BYTE $18 | block_attribute_wall, $1E | block_attribute_wall, $19 | block_attribute_wall, $1F | block_attribute_wall ;85
	.BYTE $25 | block_attribute_null, $24 | block_attribute_null, $25 | block_attribute_null, $24 | block_attribute_null ;86
	.BYTE $1B | block_attribute_wall, $1D | block_attribute_wall, $24 | block_attribute_null, $24 | block_attribute_null ;87
	.BYTE $25 | block_attribute_null, $24 | block_attribute_null, $24 | block_attribute_null, $24 | block_attribute_null ;88
	.BYTE $02 | block_attribute_2,    $02 | block_attribute_2,    $1A | block_attribute_wall, $1C | block_attribute_wall ;89
	.BYTE $02 | block_attribute_2,    $24 | block_attribute_null, $1A | block_attribute_wall, $1E | block_attribute_wall ;8A
	.BYTE $1B | block_attribute_wall, $1F | block_attribute_wall, $24 | block_attribute_null, $24 | block_attribute_null ;8B
	.BYTE $24 | block_attribute_null, $24 | block_attribute_null, $02 | block_attribute_2,    $02 | block_attribute_2    ;8C
	.BYTE $24 | block_attribute_null, $24 | block_attribute_null, $24 | block_attribute_null, $24 | block_attribute_null ;8D
	.BYTE $19 | block_attribute_wall, $1D | block_attribute_wall, $24 | block_attribute_null, $24 | block_attribute_null ;8E
	.BYTE $02 | block_attribute_2,    $02 | block_attribute_2,    $18 | block_attribute_wall, $1C | block_attribute_wall ;8F
	.BYTE $1B | block_attribute_wall, $1F | block_attribute_wall, $02 | block_attribute_2,    $02 | block_attribute_2    ;90
	.BYTE $1B | block_attribute_wall, $1D | block_attribute_wall, $02 | block_attribute_2,    $02 | block_attribute_2    ;91
	.BYTE $1A | block_attribute_null, $1C | block_attribute_null, $1B | block_attribute_null, $1D | block_attribute_null ;92
	.BYTE $1A | block_attribute_null, $1E | block_attribute_null, $1B | block_attribute_null, $1F | block_attribute_null ;93
	.BYTE $18 | block_attribute_null, $1E | block_attribute_null, $19 | block_attribute_null, $1F | block_attribute_null ;94
	.BYTE $19 | block_attribute_wall, $1D | block_attribute_wall, $02 | block_attribute_2,    $02 | block_attribute_2    ;95
	.BYTE $25 | block_attribute_null, $24 | block_attribute_null, $02 | block_attribute_2,    $02 | block_attribute_2    ;96
	.BYTE $19 | block_attribute_wall, $1F | block_attribute_wall, $02 | block_attribute_2,    $02 | block_attribute_2    ;97
	.BYTE $1E | block_attribute_wall, $25 | block_attribute_null, $1F | block_attribute_wall, $25 | block_attribute_null ;98
	.BYTE $18 | block_attribute_null, $1C | block_attribute_null, $19 | block_attribute_null, $1D | block_attribute_null ;99
	.BYTE $02 | block_attribute_2,    $02 | block_attribute_2,    $24 | block_attribute_null, $24 | block_attribute_null ;9A
	.BYTE $20 | block_attribute_wall, $00 | block_attribute_null, $20 | block_attribute_null, $00 | block_attribute_null ;9B
	.BYTE $20 | block_attribute_null, $00 | block_attribute_null, $20 | block_attribute_wall, $00 | block_attribute_null ;9C
	.BYTE $20 | block_attribute_wall, $00 | block_attribute_null, $20 | block_attribute_wall, $00 | block_attribute_null ;9D
	.BYTE $20 | block_attribute_wall, $21 | block_attribute_wall, $02 | block_attribute_2,    $02 | block_attribute_2    ;9E
	.BYTE $21 | block_attribute_wall, $21 | block_attribute_wall, $02 | block_attribute_2,    $02 | block_attribute_2    ;9F
	.BYTE $21 | block_attribute_wall, $20 | block_attribute_wall, $02 | block_attribute_2,    $02 | block_attribute_2    ;A0
	.BYTE $02 | block_attribute_2,    $02 | block_attribute_2,    $25 | block_attribute_null, $24 | block_attribute_null ;A1
	.BYTE $23 | block_attribute_3,    $20 | block_attribute_wall, $23 | block_attribute_3,    $20 | block_attribute_wall ;A2
	.BYTE $02 | block_attribute_2,    $02 | block_attribute_2,    $19 | block_attribute_wall, $1F | block_attribute_wall ;A3
	.BYTE $25 | block_attribute_null, $24 | block_attribute_null, $21 | block_attribute_wall, $21 | block_attribute_wall ;A4
	.BYTE $02 | block_attribute_2,    $02 | block_attribute_2,    $21 | block_attribute_wall, $21 | block_attribute_wall ;A5
	.BYTE $21 | block_attribute_wall, $21 | block_attribute_wall, $00 | block_attribute_null, $00 | block_attribute_null ;A6
	.BYTE $00 | block_attribute_null, $00 | block_attribute_null, $28 | block_attribute_null, $2C | block_attribute_null ;A7
	.BYTE $29 | block_attribute_null, $00 | block_attribute_null, $29 | block_attribute_null, $28 | block_attribute_null ;A8
	.BYTE $28 | block_attribute_null, $2B | block_attribute_null, $29 | block_attribute_null, $29 | block_attribute_null ;A9
	.BYTE $29 | block_attribute_null, $2A | block_attribute_null, $29 | block_attribute_null, $00 | block_attribute_null ;AA
	.BYTE $2A | block_attribute_null, $2C | block_attribute_null, $00 | block_attribute_null, $00 | block_attribute_null ;AB
	.BYTE $02 | block_attribute_2,    $00 | block_attribute_null, $21 | block_attribute_wall, $21 | block_attribute_wall ;AC
	.BYTE $21 | block_attribute_wall, $00 | block_attribute_null, $00 | block_attribute_null, $00 | block_attribute_null ;AD
	.BYTE $00 | block_attribute_null, $00 | block_attribute_null, $2C | block_attribute_null, $2C | block_attribute_null ;AE
	.BYTE $00 | block_attribute_null, $28 | block_attribute_null, $2B | block_attribute_null, $29 | block_attribute_null ;AF
	.BYTE $29 | block_attribute_null, $2A | block_attribute_null, $29 | block_attribute_null, $28 | block_attribute_null ;B0
	.BYTE $29 | block_attribute_null, $29 | block_attribute_null, $2A | block_attribute_null, $2D | block_attribute_null ;B1
	.BYTE $2C | block_attribute_null, $2C | block_attribute_null, $00 | block_attribute_null, $28 | block_attribute_null ;B2
	.BYTE $2B | block_attribute_null, $29 | block_attribute_null, $29 | block_attribute_null, $29 | block_attribute_null ;B3
	.BYTE $2A | block_attribute_null, $2D | block_attribute_null, $21 | block_attribute_wall, $21 | block_attribute_wall ;B4
	.BYTE $20 | block_attribute_wall, $20 | block_attribute_wall, $20 | block_attribute_wall, $20 | block_attribute_wall ;B5
	.BYTE $00 | block_attribute_null, $00 | block_attribute_null, $2B | block_attribute_null, $00 | block_attribute_null ;B6
	.BYTE $2D | block_attribute_null, $28 | block_attribute_null, $00 | block_attribute_null, $29 | block_attribute_null ;B7
	.BYTE $2C | block_attribute_null, $2D | block_attribute_null, $2C | block_attribute_null, $2C | block_attribute_null ;B8
	.BYTE $2D | block_attribute_null, $2A | block_attribute_null, $2C | block_attribute_null, $2C | block_attribute_null ;B9
	.BYTE $00 | block_attribute_null, $00 | block_attribute_null, $21 | block_attribute_wall, $21 | block_attribute_wall ;BA
	.BYTE $20 | block_attribute_wall, $00 | block_attribute_null, $20 | block_attribute_wall, $00 | block_attribute_null ;BB
	.BYTE $2C | block_attribute_null, $2C | block_attribute_null, $00 | block_attribute_null, $00 | block_attribute_null ;BC
	.BYTE $2C | block_attribute_null, $2C | block_attribute_null, $2C | block_attribute_null, $2C | block_attribute_null ;BD
	.BYTE $2C | block_attribute_null, $2C | block_attribute_null, $21 | block_attribute_wall, $00 | block_attribute_null ;BE
	.BYTE $00 | block_attribute_null, $00 | block_attribute_null, $2C | block_attribute_null, $2B | block_attribute_null ;BF
	.BYTE $00 | block_attribute_null, $29 | block_attribute_null, $00 | block_attribute_null, $29 | block_attribute_null ;C0
	.BYTE $00 | block_attribute_null, $00 | block_attribute_null, $00 | block_attribute_null, $21 | block_attribute_wall ;C1
	.BYTE $2B | block_attribute_null, $22 | block_attribute_null, $29 | block_attribute_null, $22 | block_attribute_null ;C2
	.BYTE $29 | block_attribute_null, $22 | block_attribute_null, $29 | block_attribute_null, $22 | block_attribute_null ;C3
	.BYTE $29 | block_attribute_null, $22 | block_attribute_null, $2D | block_attribute_null, $22 | block_attribute_null ;C4
	.BYTE $00 | block_attribute_null, $22 | block_attribute_null, $00 | block_attribute_null, $22 | block_attribute_null ;C5
	.BYTE $00 | block_attribute_null, $22 | block_attribute_null, $21 | block_attribute_wall, $21 | block_attribute_wall ;C6
	.BYTE $2C | block_attribute_null, $2D | block_attribute_null, $2B | block_attribute_null, $00 | block_attribute_null ;C7
	.BYTE $23 | block_attribute_3,    $20 | block_attribute_wall, $21 | block_attribute_wall, $20 | block_attribute_wall ;C8
	.BYTE $20 | block_attribute_wall, $21 | block_attribute_wall, $20 | block_attribute_wall, $00 | block_attribute_null ;C9
	.BYTE $20 | block_attribute_wall, $00 | block_attribute_null, $21 | block_attribute_wall, $21 | block_attribute_wall ;CA
	.BYTE $28 | block_attribute_null, $2C | block_attribute_null, $29 | block_attribute_null, $00 | block_attribute_null ;CB
	.BYTE $29 | block_attribute_null, $21 | block_attribute_wall, $29 | block_attribute_null, $00 | block_attribute_null ;CC
	.BYTE $00 | block_attribute_null, $20 | block_attribute_wall, $00 | block_attribute_null, $20 | block_attribute_wall ;CD
	.BYTE $2C | block_attribute_null, $2B | block_attribute_null, $00 | block_attribute_null, $29 | block_attribute_null ;CE
	.BYTE $21 | block_attribute_wall, $29 | block_attribute_null, $00 | block_attribute_null, $29 | block_attribute_null ;CF
	.BYTE $00 | block_attribute_null, $2A | block_attribute_null, $21 | block_attribute_wall, $21 | block_attribute_wall ;D0
	.BYTE $2C | block_attribute_null, $2C | block_attribute_null, $21 | block_attribute_wall, $21 | block_attribute_wall ;D1
	.BYTE $21 | block_attribute_wall, $21 | block_attribute_wall, $00 | block_attribute_null, $20 | block_attribute_wall ;D2
	.BYTE $28 | block_attribute_null, $2C | block_attribute_null, $2A | block_attribute_null, $2C | block_attribute_null ;D3
	.BYTE $21 | block_attribute_wall, $21 | block_attribute_wall, $00 | block_attribute_null, $28 | block_attribute_null ;D4
	.BYTE $21 | block_attribute_wall, $21 | block_attribute_wall, $2C | block_attribute_null, $2C | block_attribute_null ;D5
	.BYTE $21 | block_attribute_wall, $21 | block_attribute_wall, $2B | block_attribute_null, $22 | block_attribute_null ;D6
	.BYTE $21 | block_attribute_wall, $20 | block_attribute_wall, $23 | block_attribute_3,    $20 | block_attribute_wall ;D7
	.BYTE $2D | block_attribute_null, $22 | block_attribute_null, $21 | block_attribute_wall, $21 | block_attribute_wall ;D8
	.BYTE $21 | block_attribute_wall, $21 | block_attribute_wall, $20 | block_attribute_wall, $00 | block_attribute_null ;D9
	.BYTE $00 | block_attribute_null, $28 | block_attribute_null, $00 | block_attribute_null, $29 | block_attribute_null ;DA
	.BYTE $00 | block_attribute_null, $29 | block_attribute_null, $00 | block_attribute_null, $2A | block_attribute_null ;DB
	.BYTE $00 | block_attribute_null, $00 | block_attribute_null, $00 | block_attribute_null, $28 | block_attribute_null ;DC
	.BYTE $00 | block_attribute_null, $2A | block_attribute_null, $00 | block_attribute_null, $00 | block_attribute_null ;DD
	.BYTE $2B | block_attribute_null, $00 | block_attribute_null, $2A | block_attribute_null, $2C | block_attribute_null ;DE
	.BYTE $29 | block_attribute_null, $00 | block_attribute_null, $2A | block_attribute_null, $2B | block_attribute_null ;DF
	.BYTE $2B | block_attribute_null, $29 | block_attribute_null, $29 | block_attribute_null, $2A | block_attribute_null ;E0
	.BYTE $2A | block_attribute_null, $2C | block_attribute_null, $21 | block_attribute_wall, $21 | block_attribute_wall ;E1
	.BYTE $00 | block_attribute_null, $00 | block_attribute_null, $2B | block_attribute_null, $20 | block_attribute_wall ;E2
	.BYTE $29 | block_attribute_null, $20 | block_attribute_wall, $29 | block_attribute_null, $22 | block_attribute_null ;E3
	.BYTE $2A | block_attribute_null, $2C | block_attribute_null, $2C | block_attribute_null, $2C | block_attribute_null ;E4
	.BYTE $00 | block_attribute_null, $00 | block_attribute_null, $20 | block_attribute_wall, $00 | block_attribute_null ;E5
	.BYTE $20 | block_attribute_wall, $00 | block_attribute_null, $23 | block_attribute_3,    $20 | block_attribute_wall ;E6
	.BYTE $00 | block_attribute_null, $29 | block_attribute_null, $20 | block_attribute_wall, $29 | block_attribute_null ;E7
	.BYTE $2C | block_attribute_null, $2B | block_attribute_null, $2C | block_attribute_null, $2D | block_attribute_null ;E8
	.BYTE $00 | block_attribute_null, $22 | block_attribute_null, $2B | block_attribute_null, $22 | block_attribute_null ;E9
	.BYTE $00 | block_attribute_null, $20 | block_attribute_wall, $21 | block_attribute_wall, $21 | block_attribute_wall ;EA
	.BYTE $00 | block_attribute_null, $00 | block_attribute_null, $00 | block_attribute_null, $20 | block_attribute_wall ;EB
	.BYTE $25 | block_attribute_null, $24 | block_attribute_null, $08 | block_attribute_null, $08 | block_attribute_null ;EC
	.BYTE $24 | block_attribute_null, $24 | block_attribute_null, $08 | block_attribute_null, $08 | block_attribute_null ;ED
	.BYTE $21 | block_attribute_wall, $21 | block_attribute_wall, $24 | block_attribute_null, $24 | block_attribute_null ;EE
	.BYTE $24 | block_attribute_null, $24 | block_attribute_null, $21 | block_attribute_wall, $21 | block_attribute_wall ;EF
	.BYTE $21 | block_attribute_wall, $25 | block_attribute_null, $24 | block_attribute_null, $24 | block_attribute_null ;F0
	.BYTE $08 | block_attribute_null, $08 | block_attribute_null, $00 | block_attribute_null, $00 | block_attribute_null ;F1
	.BYTE $24 | block_attribute_null, $24 | block_attribute_null, $25 | block_attribute_null, $24 | block_attribute_null ;F2
	.BYTE $29 | block_attribute_null, $00 | block_attribute_null, $29 | block_attribute_null, $00 | block_attribute_null ;F3
	.BYTE $2E | block_attribute_null, $2C | block_attribute_null, $2D | block_attribute_null, $00 | block_attribute_null ;F4
	.BYTE $2C | block_attribute_null, $2E | block_attribute_null, $2C | block_attribute_null, $2D | block_attribute_null ;F5
	.BYTE $2D | block_attribute_null, $22 | block_attribute_null, $00 | block_attribute_null, $22 | block_attribute_null ;F6
	.BYTE $00 | block_attribute_null, $20 | block_attribute_wall, $00 | block_attribute_null, $00 | block_attribute_null ;F7
	.BYTE $20 | block_attribute_wall, $00 | block_attribute_null, $00 | block_attribute_null, $00 | block_attribute_null ;F8
	.BYTE $2B | block_attribute_null, $00 | block_attribute_null, $29 | block_attribute_null, $00 | block_attribute_null ;F9
	.BYTE $02 | block_attribute_2,    $02 | block_attribute_2,    $1A | block_attribute_wall, $1E | block_attribute_wall ;FA
	.BYTE $21 | block_attribute_wall, $21 | block_attribute_wall, $00 | block_attribute_null, $22 | block_attribute_null ;FB
	.BYTE $2C | block_attribute_null, $2E | block_attribute_null, $00 | block_attribute_null, $2A | block_attribute_null ;FC
	.BYTE $2D | block_attribute_null, $22 | block_attribute_null, $2B | block_attribute_null, $22 | block_attribute_null ;FD
	.BYTE $21 | block_attribute_wall, $21 | block_attribute_wall, $28 | block_attribute_null, $2C | block_attribute_null ;FE
	.BYTE $21 | block_attribute_wall, $21 | block_attribute_wall, $2C | block_attribute_null, $2B | block_attribute_null ;FF