;32x32 blocksets with 16x16 blocksets | block_attribute.
          ;top left,                  bottom left,                top right,                  bottom right
	.BYTE $00 | block_attribute_null, $00 | block_attribute_null, $00 | block_attribute_null, $00 | block_attribute_null
	.BYTE $18 | block_attribute_wall, $20 | block_attribute_wall, $18 | block_attribute_wall, $20 | block_attribute_wall
	.BYTE $20 | block_attribute_wall, $20 | block_attribute_wall, $20 | block_attribute_wall, $20 | block_attribute_wall
	.BYTE $20 | block_attribute_wall, $28 | block_attribute_wall, $20 | block_attribute_wall, $28 | block_attribute_wall
	.BYTE $00 | block_attribute_null, $21 | block_attribute_null, $00 | block_attribute_null, $21 | block_attribute_null
	.BYTE $22 | block_attribute_null, $23 | block_attribute_null, $22 | block_attribute_null, $23 | block_attribute_null
	.BYTE $24 | block_attribute_null, $25 | block_attribute_null, $24 | block_attribute_null, $25 | block_attribute_null
	.BYTE $25 | block_attribute_null, $25 | block_attribute_null, $25 | block_attribute_null, $25 | block_attribute_null
	.BYTE $26 | block_attribute_null, $27 | block_attribute_null, $26 | block_attribute_null, $27 | block_attribute_null
	.BYTE $29 | block_attribute_null, $2A | block_attribute_null, $29 | block_attribute_null, $2A | block_attribute_null
	.BYTE $2B | block_attribute_null, $00 | block_attribute_null, $2B | block_attribute_null, $00 | block_attribute_null
	.BYTE $31 | block_attribute_null, $18 | block_attribute_wall, $31 | block_attribute_null, $18 | block_attribute_wall
	.BYTE $31 | block_attribute_null, $1B | block_attribute_wall, $31 | block_attribute_null, $1B | block_attribute_wall
	.BYTE $1C | block_attribute_wall, $1D | block_attribute_wall, $1C | block_attribute_wall, $1D | block_attribute_wall
	.BYTE $2C | block_attribute_null, $1F | block_attribute_3,    $2D | block_attribute_null, $1F | block_attribute_3
	.BYTE $29 | block_attribute_null, $32 | block_attribute_null, $29 | block_attribute_null, $32 | block_attribute_null
	.BYTE $29 | block_attribute_null, $39 | block_attribute_null, $31 | block_attribute_null, $1E | block_attribute_wall
	.BYTE $31 | block_attribute_null, $1E | block_attribute_wall, $31 | block_attribute_null, $1E | block_attribute_wall
	.BYTE $31 | block_attribute_null, $1B | block_attribute_wall, $31 | block_attribute_null, $1E | block_attribute_wall
	.BYTE $31 | block_attribute_null, $1E | block_attribute_wall, $31 | block_attribute_null, $1B | block_attribute_wall
	.BYTE $1C | block_attribute_wall, $1D | block_attribute_wall, $2D | block_attribute_null, $1F | block_attribute_3
	.BYTE $2C | block_attribute_null, $1F | block_attribute_3,    $1C | block_attribute_wall, $1D | block_attribute_wall
	.BYTE $24 | block_attribute_null, $33 | block_attribute_null, $24 | block_attribute_null, $25 | block_attribute_null
	.BYTE $25 | block_attribute_null, $33 | block_attribute_null, $25 | block_attribute_null, $25 | block_attribute_null
	.BYTE $33 | block_attribute_null, $25 | block_attribute_null, $24 | block_attribute_null, $25 | block_attribute_null
	.BYTE $33 | block_attribute_null, $25 | block_attribute_null, $25 | block_attribute_null, $25 | block_attribute_null
	.BYTE $25 | block_attribute_null, $25 | block_attribute_null, $25 | block_attribute_null, $35 | block_attribute_null
	.BYTE $26 | block_attribute_null, $27 | block_attribute_null, $36 | block_attribute_null, $1A | block_attribute_wall
	.BYTE $36 | block_attribute_null, $1A | block_attribute_wall, $26 | block_attribute_null, $27 | block_attribute_null
	.BYTE $26 | block_attribute_null, $27 | block_attribute_null, $1A | block_attribute_wall, $1A | block_attribute_wall
	.BYTE $26 | block_attribute_null, $27 | block_attribute_null, $26 | block_attribute_null, $33 | block_attribute_null
	.BYTE $22 | block_attribute_null, $33 | block_attribute_null, $22 | block_attribute_null, $23 | block_attribute_null
	.BYTE $29 | block_attribute_null, $39 | block_attribute_null, $31 | block_attribute_null, $1B | block_attribute_wall
	.BYTE $31 | block_attribute_null, $1B | block_attribute_wall, $29 | block_attribute_null, $39 | block_attribute_null
	.BYTE $29 | block_attribute_null, $39 | block_attribute_null, $1A | block_attribute_wall, $1A | block_attribute_wall
	.BYTE $1A | block_attribute_wall, $1A | block_attribute_wall, $29 | block_attribute_null, $39 | block_attribute_null
	.BYTE $29 | block_attribute_null, $39 | block_attribute_null, $31 | block_attribute_null, $1A | block_attribute_wall
	.BYTE $31 | block_attribute_null, $1A | block_attribute_wall, $29 | block_attribute_null, $39 | block_attribute_null
	.BYTE $25 | block_attribute_null, $35 | block_attribute_null, $25 | block_attribute_null, $25 | block_attribute_null
	.BYTE $26 | block_attribute_null, $27 | block_attribute_null, $26 | block_attribute_null, $37 | block_attribute_null
	.BYTE $1A | block_attribute_wall, $1A | block_attribute_wall, $26 | block_attribute_null, $27 | block_attribute_null
	.BYTE $26 | block_attribute_null, $37 | block_attribute_null, $26 | block_attribute_null, $27 | block_attribute_null
	.BYTE $2E | block_attribute_null, $2F | block_attribute_null, $2B | block_attribute_null, $00 | block_attribute_null
	.BYTE $30 | block_attribute_null, $00 | block_attribute_null, $00 | block_attribute_null, $00 | block_attribute_null
	.BYTE $1A | block_attribute_wall, $27 | block_attribute_null, $26 | block_attribute_null, $27 | block_attribute_null
	.BYTE $29 | block_attribute_null, $32 | block_attribute_null, $29 | block_attribute_null, $2A | block_attribute_null
	.BYTE $1F | block_attribute_wall, $00 | block_attribute_null, $1F | block_attribute_wall, $00 | block_attribute_null
	.BYTE $1F | block_attribute_wall, $18 | block_attribute_wall, $1F | block_attribute_wall, $18 | block_attribute_wall
	.BYTE $1D | block_attribute_wall, $18 | block_attribute_wall, $02 | block_attribute_2,    $02 | block_attribute_2
	.BYTE $20 | block_attribute_wall, $20 | block_attribute_wall, $02 | block_attribute_2,    $02 | block_attribute_2
	.BYTE $34 | block_attribute_null, $19 | block_attribute_wall, $34 | block_attribute_null, $19 | block_attribute_wall
	.BYTE $24 | block_attribute_null, $35 | block_attribute_null, $24 | block_attribute_null, $35 | block_attribute_null
	.BYTE $25 | block_attribute_null, $35 | block_attribute_null, $25 | block_attribute_null, $35 | block_attribute_null
	.BYTE $19 | block_attribute_wall, $25 | block_attribute_null, $19 | block_attribute_wall, $25 | block_attribute_null
	.BYTE $18 | block_attribute_wall, $20 | block_attribute_wall, $18 | block_attribute_wall, $20 | block_attribute_wall
	.BYTE $19 | block_attribute_wall, $27 | block_attribute_null, $19 | block_attribute_wall, $27 | block_attribute_null
	.BYTE $26 | block_attribute_null, $37 | block_attribute_null, $26 | block_attribute_null, $37 | block_attribute_null
	.BYTE $1B | block_attribute_wall, $1C | block_attribute_wall, $1B | block_attribute_wall, $1C | block_attribute_wall
	.BYTE $1D | block_attribute_wall, $00 | block_attribute_null, $1D | block_attribute_wall, $00 | block_attribute_null
	.BYTE $22 | block_attribute_null, $23 | block_attribute_null, $22 | block_attribute_null, $38 | block_attribute_null
	.BYTE $02 | block_attribute_2,    $02 | block_attribute_2,    $18 | block_attribute_wall, $20 | block_attribute_wall
	.BYTE $02 | block_attribute_2,    $02 | block_attribute_2,    $20 | block_attribute_wall, $20 | block_attribute_wall
	.BYTE $29 | block_attribute_null, $2A | block_attribute_null, $1A | block_attribute_wall, $2A | block_attribute_null
	.BYTE $1A | block_attribute_wall, $2A | block_attribute_null, $29 | block_attribute_null, $2A | block_attribute_null
	.BYTE $2B | block_attribute_null, $18 | block_attribute_wall, $2B | block_attribute_null, $18 | block_attribute_wall
	.BYTE $00 | block_attribute_null, $21 | block_attribute_null, $02 | block_attribute_2,    $02 | block_attribute_2
	.BYTE $22 | block_attribute_null, $23 | block_attribute_null, $02 | block_attribute_2,    $02 | block_attribute_2
	.BYTE $24 | block_attribute_null, $25 | block_attribute_null, $02 | block_attribute_2,    $02 | block_attribute_2
	.BYTE $25 | block_attribute_null, $25 | block_attribute_null, $02 | block_attribute_2,    $02 | block_attribute_2
	.BYTE $26 | block_attribute_null, $27 | block_attribute_null, $02 | block_attribute_2,    $02 | block_attribute_2
	.BYTE $02 | block_attribute_2,    $02 | block_attribute_2,    $20 | block_attribute_wall, $28 | block_attribute_wall
	.BYTE $24 | block_attribute_null, $25 | block_attribute_null, $24 | block_attribute_null, $33 | block_attribute_null
	.BYTE $24 | block_attribute_null, $25 | block_attribute_null, $33 | block_attribute_null, $25 | block_attribute_null
	.BYTE $24 | block_attribute_null, $25 | block_attribute_null, $34 | block_attribute_null, $1A | block_attribute_wall
	.BYTE $25 | block_attribute_null, $25 | block_attribute_null, $1A | block_attribute_wall, $1A | block_attribute_wall
	.BYTE $07 | block_attribute_null, $07 | block_attribute_null, $26 | block_attribute_null, $27 | block_attribute_null
	.BYTE $26 | block_attribute_null, $27 | block_attribute_null, $07 | block_attribute_null, $07 | block_attribute_null
	.BYTE $07 | block_attribute_null, $07 | block_attribute_null, $29 | block_attribute_null, $2A | block_attribute_null
	.BYTE $29 | block_attribute_null, $2A | block_attribute_null, $29 | block_attribute_null, $32 | block_attribute_null
	.BYTE $29 | block_attribute_null, $32 | block_attribute_null, $07 | block_attribute_null, $07 | block_attribute_null
	.BYTE $18 | block_attribute_wall, $20 | block_attribute_wall, $2B | block_attribute_null, $00 | block_attribute_null
	.BYTE $20 | block_attribute_wall, $20 | block_attribute_wall, $00 | block_attribute_null, $00 | block_attribute_null
	.BYTE $2B | block_attribute_null, $00 | block_attribute_null, $18 | block_attribute_wall, $20 | block_attribute_wall
	.BYTE $00 | block_attribute_null, $00 | block_attribute_null, $20 | block_attribute_wall, $28 | block_attribute_wall
	.BYTE $25 | block_attribute_null, $25 | block_attribute_null, $25 | block_attribute_null, $33 | block_attribute_null
	.BYTE $33 | block_attribute_null, $27 | block_attribute_null, $26 | block_attribute_null, $27 | block_attribute_null
	.BYTE $07 | block_attribute_null, $07 | block_attribute_null, $29 | block_attribute_null, $32 | block_attribute_null
	.BYTE $29 | block_attribute_null, $32 | block_attribute_null, $29 | block_attribute_null, $2A | block_attribute_null
	.BYTE $26 | block_attribute_null, $37 | block_attribute_null, $26 | block_attribute_null, $37 | block_attribute_null
	.BYTE $36 | block_attribute_null, $19 | block_attribute_wall, $36 | block_attribute_null, $19 | block_attribute_wall
	.BYTE $18 | block_attribute_wall, $28 | block_attribute_wall, $18 | block_attribute_wall, $28 | block_attribute_wall
	.BYTE $31 | block_attribute_null, $1E | block_attribute_wall, $29 | block_attribute_null, $39 | block_attribute_null
	.BYTE $29 | block_attribute_null, $39 | block_attribute_null, $31 | block_attribute_null, $1B | block_attribute_wall
	.BYTE $18 | block_attribute_wall, $20 | block_attribute_wall, $02 | block_attribute_2,    $02 | block_attribute_2
	.BYTE $28 | block_attribute_wall, $1B | block_attribute_wall, $28 | block_attribute_wall, $1B | block_attribute_wall
	.BYTE $28 | block_attribute_wall, $1B | block_attribute_wall, $02 | block_attribute_2,    $02 | block_attribute_2
	.BYTE $1C | block_attribute_wall, $1D | block_attribute_wall, $02 | block_attribute_2,    $02 | block_attribute_2
	.BYTE $28 | block_attribute_wall, $1E | block_attribute_wall, $28 | block_attribute_wall, $1E | block_attribute_wall
	.BYTE $18 | block_attribute_wall, $20 | block_attribute_wall, $24 | block_attribute_null, $25 | block_attribute_null
	.BYTE $20 | block_attribute_wall, $20 | block_attribute_wall, $25 | block_attribute_null, $25 | block_attribute_null
	.BYTE $20 | block_attribute_wall, $20 | block_attribute_wall, $26 | block_attribute_null, $27 | block_attribute_null
	.BYTE $28 | block_attribute_wall, $1B | block_attribute_wall, $29 | block_attribute_null, $02 | block_attribute_2
	.BYTE $20 | block_attribute_wall, $20 | block_attribute_wall, $02 | block_attribute_2,    $23 | block_attribute_null
	.BYTE $31 | block_attribute_null, $1E | block_attribute_wall, $02 | block_attribute_2,    $1E | block_attribute_wall
	.BYTE $20 | block_attribute_wall, $20 | block_attribute_wall, $26 | block_attribute_null, $37 | block_attribute_null
	.BYTE $20 | block_attribute_wall, $20 | block_attribute_wall, $18 | block_attribute_wall, $20 | block_attribute_wall
	.BYTE $28 | block_attribute_wall, $23 | block_attribute_null, $28 | block_attribute_wall, $23 | block_attribute_null
	.BYTE $00 | block_attribute_null, $21 | block_attribute_null, $09 | block_attribute_wall, $09 | block_attribute_wall
	.BYTE $22 | block_attribute_null, $23 | block_attribute_null, $09 | block_attribute_wall, $09 | block_attribute_wall
	.BYTE $24 | block_attribute_null, $25 | block_attribute_null, $09 | block_attribute_wall, $0A | block_attribute_wall
	.BYTE $07 | block_attribute_wall, $0C | block_attribute_wall, $07 | block_attribute_wall, $0D | block_attribute_wall
	.BYTE $0E | block_attribute_wall, $0B | block_attribute_wall, $0F | block_attribute_wall, $0B | block_attribute_wall
	.BYTE $29 | block_attribute_null, $39 | block_attribute_null, $29 | block_attribute_null, $39 | block_attribute_null
	.BYTE $25 | block_attribute_null, $25 | block_attribute_null, $08 | block_attribute_null, $08 | block_attribute_null
	.BYTE $26 | block_attribute_null, $37 | block_attribute_null, $08 | block_attribute_null, $08 | block_attribute_null
	.BYTE $20 | block_attribute_wall, $20 | block_attribute_wall, $20 | block_attribute_wall, $28 | block_attribute_wall
	.BYTE $20 | block_attribute_wall, $28 | block_attribute_wall, $20 | block_attribute_wall, $20 | block_attribute_wall
	.BYTE $20 | block_attribute_wall, $20 | block_attribute_wall, $22 | block_attribute_null, $23 | block_attribute_null
	.BYTE $20 | block_attribute_wall, $28 | block_attribute_wall, $24 | block_attribute_null, $25 | block_attribute_null
	.BYTE $18 | block_attribute_wall, $20 | block_attribute_wall, $29 | block_attribute_null, $32 | block_attribute_null
	.BYTE $22 | block_attribute_null, $23 | block_attribute_null, $20 | block_attribute_wall, $20 | block_attribute_wall
	.BYTE $24 | block_attribute_null, $25 | block_attribute_null, $20 | block_attribute_wall, $20 | block_attribute_wall
	.BYTE $25 | block_attribute_null, $25 | block_attribute_null, $20 | block_attribute_wall, $20 | block_attribute_wall
	.BYTE $26 | block_attribute_null, $27 | block_attribute_null, $20 | block_attribute_wall, $20 | block_attribute_wall
	.BYTE $29 | block_attribute_null, $32 | block_attribute_null, $20 | block_attribute_wall, $20 | block_attribute_wall
	.BYTE $1B | block_attribute_wall, $1C | block_attribute_wall, $1E | block_attribute_wall, $2D | block_attribute_null
	.BYTE $1E | block_attribute_wall, $2C | block_attribute_null, $1B | block_attribute_wall, $1C | block_attribute_wall
	.BYTE $1E | block_attribute_wall, $2C | block_attribute_null, $1E | block_attribute_wall, $2D | block_attribute_null
	.BYTE $1D | block_attribute_wall, $00 | block_attribute_null, $1F | block_attribute_wall, $00 | block_attribute_null
	.BYTE $1F | block_attribute_wall, $00 | block_attribute_null, $1D | block_attribute_wall, $00 | block_attribute_null
	.BYTE $1A | block_attribute_wall, $25 | block_attribute_null, $25 | block_attribute_null, $25 | block_attribute_null
	.BYTE $1A | block_attribute_wall, $2A | block_attribute_null, $29 | block_attribute_null, $2A | block_attribute_null
	.BYTE $36 | block_attribute_null, $1A | block_attribute_wall, $26 | block_attribute_null, $27 | block_attribute_null
	.BYTE $24 | block_attribute_null, $35 | block_attribute_null, $24 | block_attribute_null, $25 | block_attribute_null
	.BYTE $26 | block_attribute_null, $27 | block_attribute_null, $36 | block_attribute_null, $1A | block_attribute_wall
	.BYTE $31 | block_attribute_null, $1A | block_attribute_wall, $29 | block_attribute_null, $2A | block_attribute_null
	.BYTE $20 | block_attribute_wall, $20 | block_attribute_wall, $24 | block_attribute_null, $25 | block_attribute_null
	.BYTE $29 | block_attribute_null, $39 | block_attribute_null, $29 | block_attribute_null, $2A | block_attribute_null
	.BYTE $28 | block_attribute_wall, $1E | block_attribute_wall, $28 | block_attribute_wall, $1E | block_attribute_wall
	.BYTE $20 | block_attribute_wall, $28 | block_attribute_wall, $02 | block_attribute_2,    $02 | block_attribute_2
	.BYTE $2C | block_attribute_null, $1F | block_attribute_wall, $2D | block_attribute_null, $1F | block_attribute_wall
	.BYTE $06 | block_attribute_wall, $06 | block_attribute_wall, $06 | block_attribute_wall, $06 | block_attribute_wall
	.BYTE $29 | block_attribute_null, $32 | block_attribute_null, $1A | block_attribute_wall, $1A | block_attribute_wall
	.BYTE $1A | block_attribute_wall, $1A | block_attribute_wall, $29 | block_attribute_null, $2A | block_attribute_null
	.BYTE $00 | block_attribute_null, $00 | block_attribute_null, $00 | block_attribute_null, $00 | block_attribute_null
	.BYTE $01 | block_attribute_null, $01 | block_attribute_null, $01 | block_attribute_null, $01 | block_attribute_null
	.BYTE $23 | block_attribute_wall, $25 | block_attribute_wall, $24 | block_attribute_wall, $26 | block_attribute_wall
	.BYTE $25 | block_attribute_wall, $25 | block_attribute_wall, $26 | block_attribute_wall, $26 | block_attribute_wall
	.BYTE $01 | block_attribute_null, $23 | block_attribute_wall, $01 | block_attribute_null, $24 | block_attribute_wall
	.BYTE $20 | block_attribute_wall, $20 | block_attribute_wall, $21 | block_attribute_wall, $27 | block_attribute_wall
	.BYTE $20 | block_attribute_wall, $20 | block_attribute_wall, $3C | block_attribute_wall, $3C | block_attribute_wall
	.BYTE $21 | block_attribute_wall, $3C | block_attribute_wall, $21 | block_attribute_wall, $3C | block_attribute_wall
	.BYTE $3C | block_attribute_wall, $3C | block_attribute_wall, $3C | block_attribute_wall, $3C | block_attribute_wall
	.BYTE $01 | block_attribute_null, $01 | block_attribute_null, $30 | block_attribute_null, $38 | block_attribute_null
	.BYTE $31 | block_attribute_null, $39 | block_attribute_null, $32 | block_attribute_null, $3A | block_attribute_null
	.BYTE $01 | block_attribute_null, $3B | block_attribute_null, $01 | block_attribute_null, $01 | block_attribute_null
	.BYTE $01 | block_attribute_null, $29 | block_attribute_null, $01 | block_attribute_null, $2A | block_attribute_null
	.BYTE $21 | block_attribute_wall, $3C | block_attribute_wall, $22 | block_attribute_wall, $22 | block_attribute_wall
	.BYTE $3C | block_attribute_wall, $3C | block_attribute_wall, $22 | block_attribute_wall, $22 | block_attribute_wall
	.BYTE $1B | block_attribute_null, $1B | block_attribute_null, $1B | block_attribute_null, $1B | block_attribute_null
	.BYTE $1E | block_attribute_null, $1D | block_attribute_null, $1E | block_attribute_null, $1D | block_attribute_null
	.BYTE $1D | block_attribute_null, $1D | block_attribute_null, $1D | block_attribute_null, $1D | block_attribute_null
	.BYTE $1D | block_attribute_null, $1D | block_attribute_null, $28 | block_attribute_null, $28 | block_attribute_null
	.BYTE $01 | block_attribute_null, $1E | block_attribute_null, $01 | block_attribute_null, $1E | block_attribute_null
	.BYTE $1D | block_attribute_null, $28 | block_attribute_null, $1D | block_attribute_null, $1D | block_attribute_null
	.BYTE $1D | block_attribute_null, $23 | block_attribute_wall, $1D | block_attribute_null, $24 | block_attribute_wall
	.BYTE $1D | block_attribute_null, $1D | block_attribute_null, $1D | block_attribute_null, $28 | block_attribute_null
	.BYTE $1D | block_attribute_null, $23 | block_attribute_wall, $28 | block_attribute_null, $24 | block_attribute_wall
	.BYTE $3D | block_attribute_null, $3D | block_attribute_null, $3D | block_attribute_null, $3D | block_attribute_null
	.BYTE $28 | block_attribute_null, $23 | block_attribute_wall, $1D | block_attribute_null, $24 | block_attribute_wall
	.BYTE $3C | block_attribute_wall, $3C | block_attribute_wall, $0C | block_attribute_wall, $0E | block_attribute_wall
	.BYTE $0D | block_attribute_wall, $0F | block_attribute_wall, $3C | block_attribute_wall, $3C | block_attribute_wall
	.BYTE $01 | block_attribute_null, $01 | block_attribute_null, $2C | block_attribute_wall, $01 | block_attribute_null
	.BYTE $01 | block_attribute_null, $01 | block_attribute_null, $2E | block_attribute_wall, $37 | block_attribute_wall
	.BYTE $2F | block_attribute_wall, $33 | block_attribute_wall, $33 | block_attribute_wall, $34 | block_attribute_wall
	.BYTE $33 | block_attribute_wall, $33 | block_attribute_wall, $34 | block_attribute_wall, $34 | block_attribute_wall
	.BYTE $33 | block_attribute_wall, $33 | block_attribute_wall, $34 | block_attribute_wall, $3E | block_attribute_null
	.BYTE $2D | block_attribute_wall, $3E | block_attribute_null, $3D | block_attribute_null, $3D | block_attribute_null
	.BYTE $34 | block_attribute_wall, $34 | block_attribute_wall, $34 | block_attribute_wall, $34 | block_attribute_wall
	.BYTE $34 | block_attribute_wall, $3E | block_attribute_null, $34 | block_attribute_wall, $3E | block_attribute_null
	.BYTE $3F | block_attribute_null, $3D | block_attribute_null, $3F | block_attribute_null, $3F | block_attribute_null
	.BYTE $34 | block_attribute_wall, $33 | block_attribute_wall, $34 | block_attribute_wall, $34 | block_attribute_wall
	.BYTE $3E | block_attribute_null, $3D | block_attribute_null, $3E | block_attribute_null, $3D | block_attribute_null
	.BYTE $35 | block_attribute_wall, $35 | block_attribute_wall, $3D | block_attribute_null, $3D | block_attribute_null
	.BYTE $35 | block_attribute_wall, $35 | block_attribute_wall, $3F | block_attribute_null, $3D | block_attribute_null
	.BYTE $3E | block_attribute_null, $3F | block_attribute_null, $3D | block_attribute_null, $3D | block_attribute_null
	.BYTE $35 | block_attribute_wall, $35 | block_attribute_wall, $3E | block_attribute_null, $3F | block_attribute_null
	.BYTE $33 | block_attribute_wall, $33 | block_attribute_wall, $02 | block_attribute_2,    $02 | block_attribute_2
	.BYTE $33 | block_attribute_wall, $33 | block_attribute_wall, $02 | block_attribute_2,    $3D | block_attribute_null
	.BYTE $3D | block_attribute_null, $3F | block_attribute_null, $3D | block_attribute_null, $3D | block_attribute_null
	.BYTE $2F | block_attribute_wall, $33 | block_attribute_wall, $3D | block_attribute_null, $34 | block_attribute_wall
	.BYTE $3D | block_attribute_null, $34 | block_attribute_wall, $3F | block_attribute_null, $35 | block_attribute_wall
	.BYTE $33 | block_attribute_wall, $3E | block_attribute_null, $34 | block_attribute_wall, $3E | block_attribute_null
	.BYTE $34 | block_attribute_wall, $3E | block_attribute_null, $34 | block_attribute_wall, $3E | block_attribute_null
	.BYTE $35 | block_attribute_wall, $3E | block_attribute_null, $02 | block_attribute_2,    $3D | block_attribute_null
	.BYTE $3D | block_attribute_null, $02 | block_attribute_2,    $3D | block_attribute_null, $33 | block_attribute_wall
	.BYTE $3D | block_attribute_null, $34 | block_attribute_wall, $3F | block_attribute_null, $34 | block_attribute_wall
	.BYTE $3D | block_attribute_null, $34 | block_attribute_wall, $3F | block_attribute_null, $35 | block_attribute_wall
	.BYTE $02 | block_attribute_2,    $02 | block_attribute_2,    $33 | block_attribute_wall, $33 | block_attribute_wall
	.BYTE $34 | block_attribute_wall, $34 | block_attribute_wall, $35 | block_attribute_wall, $35 | block_attribute_wall
	.BYTE $02 | block_attribute_2,    $02 | block_attribute_2,    $3E | block_attribute_null, $3D | block_attribute_null
	.BYTE $3E | block_attribute_null, $3F | block_attribute_null, $3E | block_attribute_null, $3D | block_attribute_null
	.BYTE $35 | block_attribute_wall, $35 | block_attribute_wall, $02 | block_attribute_2,    $02 | block_attribute_2
	.BYTE $01 | block_attribute_null, $01 | block_attribute_null, $2B | block_attribute_wall, $2C | block_attribute_wall
	.BYTE $33 | block_attribute_wall, $2D | block_attribute_wall, $3E | block_attribute_null, $3F | block_attribute_null
	.BYTE $01 | block_attribute_null, $01 | block_attribute_null, $01 | block_attribute_null, $2E | block_attribute_wall
	.BYTE $3E | block_attribute_null, $2F | block_attribute_wall, $3D | block_attribute_null, $3D | block_attribute_null
	.BYTE $01 | block_attribute_null, $01 | block_attribute_null, $37 | block_attribute_wall, $01 | block_attribute_null
	.BYTE $01 | block_attribute_null, $01 | block_attribute_null, $02 | block_attribute_2,    $02 | block_attribute_2
	.BYTE $01 | block_attribute_null, $01 | block_attribute_null, $02 | block_attribute_2,    $01 | block_attribute_null
	.BYTE $20 | block_attribute_wall, $20 | block_attribute_wall, $18 | block_attribute_wall, $3C | block_attribute_wall
	.BYTE $20 | block_attribute_wall, $20 | block_attribute_wall, $21 | block_attribute_wall, $3C | block_attribute_wall
	.BYTE $20 | block_attribute_wall, $01 | block_attribute_null, $18 | block_attribute_wall, $01 | block_attribute_null
	.BYTE $19 | block_attribute_wall, $3C | block_attribute_wall, $19 | block_attribute_wall, $3C | block_attribute_wall
	.BYTE $19 | block_attribute_wall, $01 | block_attribute_null, $19 | block_attribute_wall, $01 | block_attribute_null
	.BYTE $1A | block_attribute_wall, $01 | block_attribute_null, $3C | block_attribute_wall, $01 | block_attribute_null
	.BYTE $1A | block_attribute_wall, $3C | block_attribute_wall, $3C | block_attribute_wall, $3C | block_attribute_wall
	.BYTE $18 | block_attribute_wall, $20 | block_attribute_wall, $19 | block_attribute_wall, $3C | block_attribute_wall
	.BYTE $18 | block_attribute_wall, $3C | block_attribute_wall, $19 | block_attribute_wall, $3C | block_attribute_wall
	.BYTE $01 | block_attribute_null, $01 | block_attribute_null, $01 | block_attribute_null, $2B | block_attribute_wall
	.BYTE $20 | block_attribute_wall, $20 | block_attribute_wall, $3C | block_attribute_wall, $21 | block_attribute_wall
	.BYTE $3C | block_attribute_wall, $21 | block_attribute_wall, $3C | block_attribute_wall, $21 | block_attribute_wall
	.BYTE $3C | block_attribute_wall, $21 | block_attribute_wall, $22 | block_attribute_wall, $22 | block_attribute_wall
	.BYTE $1A | block_attribute_wall, $3C | block_attribute_wall, $22 | block_attribute_wall, $22 | block_attribute_wall
	.BYTE $00 | block_attribute_null, $00 | block_attribute_null, $36 | block_attribute_wall, $00 | block_attribute_null
	.BYTE $36 | block_attribute_wall, $00 | block_attribute_null, $36 | block_attribute_wall, $00 | block_attribute_null
	.BYTE $00 | block_attribute_null, $36 | block_attribute_wall, $00 | block_attribute_null, $00 | block_attribute_null
	.BYTE $1F | block_attribute_null, $01 | block_attribute_null, $27 | block_attribute_null, $01 | block_attribute_null
	.BYTE $1B | block_attribute_null, $27 | block_attribute_null, $1B | block_attribute_null, $1B | block_attribute_null
	.BYTE $1F | block_attribute_null, $1B | block_attribute_null, $27 | block_attribute_null, $1B | block_attribute_null
	.BYTE $1B | block_attribute_null, $1B | block_attribute_null, $1B | block_attribute_null, $1F | block_attribute_null
	.BYTE $1B | block_attribute_null, $01 | block_attribute_null, $1B | block_attribute_null, $01 | block_attribute_null
	.BYTE $1B | block_attribute_null, $27 | block_attribute_null, $1F | block_attribute_null, $1B | block_attribute_null
	.BYTE $01 | block_attribute_null, $1B | block_attribute_null, $27 | block_attribute_null, $1F | block_attribute_null
	.BYTE $27 | block_attribute_null, $01 | block_attribute_null, $1B | block_attribute_null, $01 | block_attribute_null
	.BYTE $1F | block_attribute_null, $01 | block_attribute_null, $01 | block_attribute_null, $01 | block_attribute_null
	.BYTE $27 | block_attribute_null, $01 | block_attribute_null, $1F | block_attribute_null, $01 | block_attribute_null
	.BYTE $1B | block_attribute_null, $1B | block_attribute_null, $1B | block_attribute_null, $1B | block_attribute_null
	.BYTE $1B | block_attribute_null, $01 | block_attribute_null, $1F | block_attribute_null, $01 | block_attribute_null
	.BYTE $1B | block_attribute_null, $01 | block_attribute_null, $1B | block_attribute_null, $27 | block_attribute_null
	.BYTE $1B | block_attribute_null, $1B | block_attribute_null, $1F | block_attribute_null, $1B | block_attribute_null
	.BYTE $01 | block_attribute_null, $1B | block_attribute_null, $01 | block_attribute_null, $1F | block_attribute_null
	.BYTE $01 | block_attribute_null, $01 | block_attribute_null, $27 | block_attribute_null, $01 | block_attribute_null
	.BYTE $27 | block_attribute_null, $1B | block_attribute_null, $1B | block_attribute_null, $1B | block_attribute_null
	.BYTE $1B | block_attribute_null, $27 | block_attribute_null, $1B | block_attribute_null, $1F | block_attribute_null
	.BYTE $27 | block_attribute_null, $01 | block_attribute_null, $1B | block_attribute_null, $27 | block_attribute_null
	.BYTE $1F | block_attribute_null, $1B | block_attribute_null, $01 | block_attribute_null, $1F | block_attribute_null
	.BYTE $01 | block_attribute_null, $1F | block_attribute_null, $01 | block_attribute_null, $01 | block_attribute_null
	.BYTE $1A | block_attribute_wall, $1A | block_attribute_wall, $29 | block_attribute_null, $32 | block_attribute_null
	.BYTE $30 | block_attribute_wall, $32 | block_attribute_wall, $31 | block_attribute_wall, $33 | block_attribute_wall
	.BYTE $3F | block_attribute_null, $00 | block_attribute_null, $3F | block_attribute_null, $00 | block_attribute_null
	.BYTE $34 | block_attribute_wall, $35 | block_attribute_wall, $36 | block_attribute_wall, $37 | block_attribute_wall
	.BYTE $0A | block_attribute_wall, $12 | block_attribute_wall, $17 | block_attribute_null, $17 | block_attribute_null
	.BYTE $3F | block_attribute_2,    $16 | block_attribute_null, $17 | block_attribute_null, $17 | block_attribute_null
	.BYTE $17 | block_attribute_null, $17 | block_attribute_null, $05 | block_attribute_3,    $05 | block_attribute_3
	.BYTE $3F | block_attribute_2,    $16 | block_attribute_null, $3F | block_attribute_2,    $16 | block_attribute_null