;32x32 blocksets with 16x16 blocksets | block_attribute.
;block_attribute 2 and 3 setting see home/blocksets.asm. 
	      ;top left,                  bottom left,                top right,                  bottom right
	.BYTE $01 | block_attribute_null, $01 | block_attribute_null, $01 | block_attribute_null, $01 | block_attribute_null ;00
	.BYTE $00 | block_attribute_null, $00 | block_attribute_null, $00 | block_attribute_null, $00 | block_attribute_null ;01
	.BYTE $2E | block_attribute_wall, $2E | block_attribute_wall, $2E | block_attribute_wall, $2E | block_attribute_wall ;02
	.BYTE $2E | block_attribute_wall, $2E | block_attribute_wall, $2F | block_attribute_wall, $2F | block_attribute_wall ;03
	.BYTE $2E | block_attribute_wall, $2E | block_attribute_wall, $2F | block_attribute_null, $2F | block_attribute_null ;04
	.BYTE $32 | block_attribute_null, $3E | block_attribute_null, $31 | block_attribute_null, $3E | block_attribute_null ;05
	.BYTE $31 | block_attribute_null, $3E | block_attribute_null, $31 | block_attribute_null, $3E | block_attribute_null ;06
	.BYTE $31 | block_attribute_null, $3E | block_attribute_null, $33 | block_attribute_null, $3E | block_attribute_null ;07
	.BYTE $31 | block_attribute_null, $28 | block_attribute_null, $31 | block_attribute_null, $3E | block_attribute_null ;08
	.BYTE $31 | block_attribute_null, $3E | block_attribute_null, $2E | block_attribute_null, $32 | block_attribute_null ;09
	.BYTE $2E | block_attribute_null, $2E | block_attribute_null, $2E | block_attribute_null, $2E | block_attribute_null ;0A
	.BYTE $2E | block_attribute_null, $2E | block_attribute_null, $2F | block_attribute_null, $2F | block_attribute_null ;0B
	.BYTE $32 | block_attribute_null, $3E | block_attribute_null, $2E | block_attribute_null, $32 | block_attribute_null ;0C
	.BYTE $2E | block_attribute_null, $31 | block_attribute_null, $2E | block_attribute_null, $31 | block_attribute_null ;0D
	.BYTE $2E | block_attribute_null, $33 | block_attribute_null, $33 | block_attribute_null, $3E | block_attribute_null ;0E
	.BYTE $2A | block_attribute_null, $2A | block_attribute_null, $00 | block_attribute_null, $00 | block_attribute_null ;0F
	.BYTE $2E | block_attribute_null, $32 | block_attribute_null, $2E | block_attribute_null, $31 | block_attribute_null ;10
	.BYTE $2E | block_attribute_null, $33 | block_attribute_null, $31 | block_attribute_null, $3E | block_attribute_null ;11
	.BYTE $28 | block_attribute_null, $28 | block_attribute_null, $3D | block_attribute_null, $00 | block_attribute_null ;12
	.BYTE $3D | block_attribute_null, $00 | block_attribute_null, $3E | block_attribute_null, $36 | block_attribute_null ;13
	.BYTE $37 | block_attribute_null, $00 | block_attribute_null, $36 | block_attribute_null, $00 | block_attribute_null ;14
	.BYTE $3E | block_attribute_null, $3D | block_attribute_null, $3E | block_attribute_null, $3D | block_attribute_null ;15
	.BYTE $36 | block_attribute_null, $00 | block_attribute_null, $3D | block_attribute_null, $00 | block_attribute_null ;16
	.BYTE $2A | block_attribute_null, $2B | block_attribute_null, $2D | block_attribute_null, $20 | block_attribute_wall ;17
	.BYTE $3E | block_attribute_null, $3D | block_attribute_null, $3E | block_attribute_null, $37 | block_attribute_null ;18
	.BYTE $3D | block_attribute_null, $2A | block_attribute_null, $3D | block_attribute_null, $00 | block_attribute_null ;19
	.BYTE $28 | block_attribute_null, $28 | block_attribute_null, $3E | block_attribute_null, $3D | block_attribute_null ;1A
	.BYTE $3E | block_attribute_null, $2A | block_attribute_null, $37 | block_attribute_null, $00 | block_attribute_null ;1B
	.BYTE $3E | block_attribute_null, $2A | block_attribute_null, $3E | block_attribute_null, $36 | block_attribute_null ;1C
	.BYTE $00 | block_attribute_null, $2D | block_attribute_null, $00 | block_attribute_null, $2D | block_attribute_null ;1D
	.BYTE $2A | block_attribute_null, $2B | block_attribute_null, $00 | block_attribute_null, $2D | block_attribute_null ;1E
	.BYTE $28 | block_attribute_null, $28 | block_attribute_null, $00 | block_attribute_null, $2D | block_attribute_null ;1F
	.BYTE $01 | block_attribute_null, $34 | block_attribute_null, $34 | block_attribute_null, $2E | block_attribute_null ;20
	.BYTE $2C | block_attribute_null, $2E | block_attribute_null, $2C | block_attribute_null, $2E | block_attribute_null ;21
	.BYTE $28 | block_attribute_null, $28 | block_attribute_null, $3E | block_attribute_null, $3E | block_attribute_null ;22
	.BYTE $35 | block_attribute_null, $2E | block_attribute_null, $01 | block_attribute_null, $35 | block_attribute_null ;23
	.BYTE $2C | block_attribute_null, $2E | block_attribute_null, $3F | block_attribute_null, $2F | block_attribute_null ;24
	.BYTE $3E | block_attribute_null, $3E | block_attribute_null, $3E | block_attribute_null, $3E | block_attribute_null ;25
	.BYTE $2E | block_attribute_null, $31 | block_attribute_null, $21 | block_attribute_null, $33 | block_attribute_null ;26
	.BYTE $3E | block_attribute_null, $37 | block_attribute_null, $3D | block_attribute_null, $00 | block_attribute_null ;27
	.BYTE $00 | block_attribute_null, $2D | block_attribute_null, $08 | block_attribute_null, $08 | block_attribute_null ;28
	.BYTE $31 | block_attribute_null, $3E | block_attribute_null, $19 | block_attribute_wall, $19 | block_attribute_wall ;29
	.BYTE $38 | block_attribute_wall, $38 | block_attribute_wall, $19 | block_attribute_wall, $19 | block_attribute_wall ;2A
	.BYTE $39 | block_attribute_wall, $39 | block_attribute_wall, $21 | block_attribute_null, $21 | block_attribute_null ;2B
	.BYTE $21 | block_attribute_null, $21 | block_attribute_null, $38 | block_attribute_wall, $38 | block_attribute_wall ;2C
	.BYTE $2B | block_attribute_null, $20 | block_attribute_wall, $2D | block_attribute_null, $20 | block_attribute_wall ;2D
	.BYTE $28 | block_attribute_null, $20 | block_attribute_wall, $2D | block_attribute_null, $20 | block_attribute_wall ;2E
	.BYTE $2A | block_attribute_null, $2B | block_attribute_null, $2D | block_attribute_null, $20 | block_attribute_wall ;2F
	.BYTE $2E | block_attribute_wall, $2E | block_attribute_wall, $19 | block_attribute_wall, $19 | block_attribute_wall ;30
	.BYTE $3E | block_attribute_null, $37 | block_attribute_null, $19 | block_attribute_wall, $19 | block_attribute_wall ;31
	.BYTE $18 | block_attribute_wall, $18 | block_attribute_wall, $39 | block_attribute_wall, $39 | block_attribute_wall ;32
	.BYTE $39 | block_attribute_wall, $18 | block_attribute_wall, $21 | block_attribute_null, $20 | block_attribute_wall ;33
	.BYTE $1A | block_attribute_wall, $01 | block_attribute_null, $01 | block_attribute_null, $01 | block_attribute_null ;34
	.BYTE $02 | block_attribute_2,    $00 | block_attribute_null, $1A | block_attribute_wall, $00 | block_attribute_null ;35
	.BYTE $1A | block_attribute_wall, $00 | block_attribute_null, $1A | block_attribute_wall, $00 | block_attribute_null ;36
	.BYTE $02 | block_attribute_2,    $02 | block_attribute_2,    $2E | block_attribute_null, $2E | block_attribute_null ;37
	.BYTE $2E | block_attribute_null, $2E | block_attribute_null, $19 | block_attribute_wall, $19 | block_attribute_wall ;38
	.BYTE $00 | block_attribute_null, $00 | block_attribute_null, $19 | block_attribute_wall, $19 | block_attribute_wall ;39
	.BYTE $18 | block_attribute_wall, $18 | block_attribute_wall, $19 | block_attribute_wall, $39 | block_attribute_wall ;3A
	.BYTE $20 | block_attribute_wall, $38 | block_attribute_wall, $20 | block_attribute_wall, $19 | block_attribute_wall ;3B
	.BYTE $20 | block_attribute_wall, $18 | block_attribute_wall, $20 | block_attribute_wall, $39 | block_attribute_wall ;3C
	.BYTE $1B | block_attribute_wall, $1D | block_attribute_wall, $2F | block_attribute_3,    $20 | block_attribute_wall ;3D
	.BYTE $1B | block_attribute_wall, $1D | block_attribute_wall, $2F | block_attribute_3,    $01 | block_attribute_2    ;3E
	.BYTE $00 | block_attribute_null, $00 | block_attribute_null, $00 | block_attribute_null, $00 | block_attribute_null ;3F
	.BYTE $01 | block_attribute_null, $20 | block_attribute_wall, $01 | block_attribute_null, $20 | block_attribute_wall ;40
	.BYTE $28 | block_attribute_3,    $20 | block_attribute_wall, $01 | block_attribute_null, $20 | block_attribute_wall ;41
	.BYTE $02 | block_attribute_2,    $02 | block_attribute_2,    $19 | block_attribute_wall, $19 | block_attribute_wall ;42
	.BYTE $01 | block_attribute_null, $01 | block_attribute_null, $19 | block_attribute_wall, $19 | block_attribute_wall ;43
	.BYTE $21 | block_attribute_null, $21 | block_attribute_null, $21 | block_attribute_null, $21 | block_attribute_null ;44
	.BYTE $22 | block_attribute_null, $21 | block_attribute_null, $22 | block_attribute_null, $21 | block_attribute_null ;45
	.BYTE $21 | block_attribute_null, $21 | block_attribute_null, $22 | block_attribute_null, $21 | block_attribute_null ;46
	.BYTE $22 | block_attribute_null, $21 | block_attribute_null, $21 | block_attribute_null, $21 | block_attribute_null ;47
	.BYTE $21 | block_attribute_null, $21 | block_attribute_null, $02 | block_attribute_2,    $02 | block_attribute_2    ;48
	.BYTE $21 | block_attribute_null, $21 | block_attribute_null, $02 | block_attribute_2,    $21 | block_attribute_null ;49
	.BYTE $21 | block_attribute_null, $24 | block_attribute_null, $1D | block_attribute_null, $25 | block_attribute_null ;4A
	.BYTE $1E | block_attribute_null, $26 | block_attribute_null, $1F | block_attribute_null, $27 | block_attribute_null ;4B
	.BYTE $22 | block_attribute_null, $21 | block_attribute_null, $21 | block_attribute_null, $23 | block_attribute_null ;4C
	.BYTE $21 | block_attribute_null, $1B | block_attribute_null, $21 | block_attribute_null, $1C | block_attribute_null ;4D
	.BYTE $20 | block_attribute_wall, $18 | block_attribute_wall, $20 | block_attribute_wall, $19 | block_attribute_wall ;4E
	.BYTE $18 | block_attribute_wall, $18 | block_attribute_wall, $19 | block_attribute_wall, $19 | block_attribute_wall ;4F
	.BYTE $00 | block_attribute_null, $00 | block_attribute_null, $08 | block_attribute_null, $08 | block_attribute_null ;50
	.BYTE $2E | block_attribute_null, $31 | block_attribute_null, $09 | block_attribute_wall, $09 | block_attribute_wall ;51
	.BYTE $07 | block_attribute_wall, $0C | block_attribute_wall, $07 | block_attribute_wall, $0D | block_attribute_wall ;52
	.BYTE $0E | block_attribute_wall, $0B | block_attribute_wall, $0F | block_attribute_wall, $0B | block_attribute_wall ;53
	.BYTE $22 | block_attribute_null, $21 | block_attribute_null, $08 | block_attribute_null, $08 | block_attribute_null ;54
	.BYTE $21 | block_attribute_null, $21 | block_attribute_null, $08 | block_attribute_null, $08 | block_attribute_null ;55
	.BYTE $1A | block_attribute_wall, $22 | block_attribute_null, $22 | block_attribute_null, $21 | block_attribute_null ;56
	.BYTE $21 | block_attribute_null, $20 | block_attribute_wall, $21 | block_attribute_null, $20 | block_attribute_wall ;57
	.BYTE $02 | block_attribute_2,    $02 | block_attribute_2,    $22 | block_attribute_null, $21 | block_attribute_null ;58
	.BYTE $22 | block_attribute_null, $21 | block_attribute_null, $19 | block_attribute_wall, $19 | block_attribute_wall ;59
	.BYTE $18 | block_attribute_wall, $18 | block_attribute_wall, $21 | block_attribute_null, $21 | block_attribute_null ;5A
	.BYTE $22 | block_attribute_null, $21 | block_attribute_null, $02 | block_attribute_2,    $02 | block_attribute_2    ;5B
	.BYTE $18 | block_attribute_wall, $18 | block_attribute_wall, $02 | block_attribute_2,    $02 | block_attribute_2    ;5C
	.BYTE $1A | block_attribute_wall, $22 | block_attribute_null, $19 | block_attribute_wall, $19 | block_attribute_wall ;5D
	.BYTE $22 | block_attribute_null, $21 | block_attribute_null, $1A | block_attribute_wall, $22 | block_attribute_null ;5E
	.BYTE $18 | block_attribute_wall, $18 | block_attribute_wall, $1A | block_attribute_wall, $22 | block_attribute_null ;5F
	.BYTE $29 | block_attribute_wall, $01 | block_attribute_null, $29 | block_attribute_wall, $01 | block_attribute_null ;60
	.BYTE $21 | block_attribute_null, $21 | block_attribute_null, $00 | block_attribute_null, $01 | block_attribute_null ;61
	.BYTE $18 | block_attribute_wall, $1A | block_attribute_wall, $22 | block_attribute_null, $21 | block_attribute_null ;62
	.BYTE $21 | block_attribute_null, $21 | block_attribute_null, $19 | block_attribute_wall, $19 | block_attribute_wall ;63
	.BYTE $21 | block_attribute_null, $02 | block_attribute_2,    $19 | block_attribute_wall, $19 | block_attribute_wall ;64
	.BYTE $1A | block_attribute_wall, $22 | block_attribute_null, $1A | block_attribute_wall, $22 | block_attribute_null ;65
	.BYTE $1A | block_attribute_wall, $01 | block_attribute_null, $19 | block_attribute_wall, $19 | block_attribute_wall ;66
	.BYTE $18 | block_attribute_wall, $18 | block_attribute_wall, $19 | block_attribute_wall, $19 | block_attribute_wall ;67
	.BYTE $35 | block_attribute_null, $36 | block_attribute_null, $38 | block_attribute_null, $37 | block_attribute_null ;68
	.BYTE $34 | block_attribute_null, $36 | block_attribute_null, $2F | block_attribute_null, $37 | block_attribute_null ;69
	.BYTE $1A | block_attribute_wall, $22 | block_attribute_null, $19 | block_attribute_wall, $1A | block_attribute_wall ;6A
	.BYTE $02 | block_attribute_2,    $20 | block_attribute_wall, $21 | block_attribute_null, $20 | block_attribute_wall ;6B
	.BYTE $02 | block_attribute_2,    $02 | block_attribute_2,    $1A | block_attribute_wall, $22 | block_attribute_null ;6C
	.BYTE $38 | block_attribute_null, $38 | block_attribute_null, $19 | block_attribute_wall, $19 | block_attribute_wall ;6D
	.BYTE $20 | block_attribute_wall, $18 | block_attribute_wall, $19 | block_attribute_wall, $19 | block_attribute_wall ;6E
	.BYTE $18 | block_attribute_wall, $18 | block_attribute_wall, $20 | block_attribute_wall, $19 | block_attribute_wall ;6F
	.BYTE $21 | block_attribute_null, $21 | block_attribute_null, $20 | block_attribute_wall, $19 | block_attribute_wall ;70
	.BYTE $20 | block_attribute_wall, $18 | block_attribute_wall, $02 | block_attribute_2,    $02 | block_attribute_2    ;71
	.BYTE $02 | block_attribute_2,    $02 | block_attribute_2,    $20 | block_attribute_wall, $19 | block_attribute_wall ;72
	.BYTE $20 | block_attribute_wall, $18 | block_attribute_wall, $21 | block_attribute_null, $21 | block_attribute_null ;73
	.BYTE $18 | block_attribute_wall, $1A | block_attribute_wall, $19 | block_attribute_wall, $1A | block_attribute_wall ;74
	.BYTE $18 | block_attribute_wall, $1A | block_attribute_wall, $19 | block_attribute_wall, $19 | block_attribute_wall ;75
	.BYTE $18 | block_attribute_wall, $18 | block_attribute_wall, $19 | block_attribute_wall, $1A | block_attribute_wall ;76
	.BYTE $18 | block_attribute_wall, $1A | block_attribute_wall, $1A | block_attribute_wall, $22 | block_attribute_null ;77
	.BYTE $18 | block_attribute_wall, $1A | block_attribute_wall, $1A | block_attribute_wall, $01 | block_attribute_null ;78
	.BYTE $1A | block_attribute_wall, $2E | block_attribute_null, $2E | block_attribute_null, $2E | block_attribute_null ;79
	.BYTE $18 | block_attribute_wall, $1A | block_attribute_wall, $02 | block_attribute_2,    $02 | block_attribute_2    ;7A
	.BYTE $02 | block_attribute_2,    $02 | block_attribute_2,    $19 | block_attribute_wall, $1A | block_attribute_wall ;7B
	.BYTE $22 | block_attribute_null, $21 | block_attribute_null, $19 | block_attribute_wall, $1A | block_attribute_wall ;7C
	.BYTE $01 | block_attribute_null, $01 | block_attribute_null, $1A | block_attribute_wall, $01 | block_attribute_null ;7D
	.BYTE $21 | block_attribute_null, $20 | block_attribute_wall, $21 | block_attribute_null, $21 | block_attribute_null ;7E
	.BYTE $39 | block_attribute_null, $3A | block_attribute_null, $37 | block_attribute_null, $39 | block_attribute_null ;7F
	.BYTE $00 | block_attribute_null, $00 | block_attribute_null, $3A | block_attribute_null, $00 | block_attribute_null ;80
	.BYTE $3C | block_attribute_null, $3D | block_attribute_null, $37 | block_attribute_null, $3F | block_attribute_null ;81
	.BYTE $3B | block_attribute_null, $2A | block_attribute_null, $39 | block_attribute_null, $3A | block_attribute_null ;82
	.BYTE $36 | block_attribute_null, $3D | block_attribute_null, $39 | block_attribute_null, $3F | block_attribute_null ;83
	.BYTE $38 | block_attribute_null, $35 | block_attribute_null, $38 | block_attribute_null, $37 | block_attribute_null ;84
	.BYTE $00 | block_attribute_null, $00 | block_attribute_null, $19 | block_attribute_wall, $19 | block_attribute_wall ;85
	.BYTE $00 | block_attribute_null, $2D | block_attribute_null, $19 | block_attribute_wall, $19 | block_attribute_wall ;86
	.BYTE $37 | block_attribute_null, $3A | block_attribute_null, $19 | block_attribute_wall, $19 | block_attribute_wall ;87
	.BYTE $30 | block_attribute_3,    $31 | block_attribute_3,    $33 | block_attribute_null, $37 | block_attribute_null ;88
	.BYTE $2D | block_attribute_null, $20 | block_attribute_wall, $2D | block_attribute_null, $20 | block_attribute_wall ;89
	.BYTE $01 | block_attribute_null, $2C | block_attribute_null, $2C | block_attribute_null, $38 | block_attribute_null ;8A
	.BYTE $2C | block_attribute_null, $38 | block_attribute_null, $2C | block_attribute_null, $38 | block_attribute_null ;8B
	.BYTE $2C | block_attribute_null, $38 | block_attribute_null, $01 | block_attribute_null, $2C | block_attribute_null ;8C
	.BYTE $01 | block_attribute_null, $2C | block_attribute_null, $2C | block_attribute_null, $2E | block_attribute_null ;8D
	.BYTE $01 | block_attribute_null, $2C | block_attribute_null, $01 | block_attribute_null, $2C | block_attribute_null ;8E
	.BYTE $01 | block_attribute_null, $2C | block_attribute_null, $01 | block_attribute_null, $01 | block_attribute_null ;8F
	.BYTE $38 | block_attribute_null, $38 | block_attribute_null, $2C | block_attribute_null, $38 | block_attribute_null ;90
	.BYTE $2C | block_attribute_null, $35 | block_attribute_null, $01 | block_attribute_null, $2C | block_attribute_null ;91
	.BYTE $38 | block_attribute_null, $35 | block_attribute_null, $38 | block_attribute_null, $38 | block_attribute_null ;92
	.BYTE $34 | block_attribute_null, $35 | block_attribute_null, $2F | block_attribute_null, $38 | block_attribute_null ;93
	.BYTE $20 | block_attribute_wall, $1A | block_attribute_wall, $20 | block_attribute_wall, $1A | block_attribute_wall ;94
	.BYTE $20 | block_attribute_wall, $18 | block_attribute_wall, $19 | block_attribute_wall, $19 | block_attribute_wall ;95
	.BYTE $18 | block_attribute_wall, $18 | block_attribute_wall, $22 | block_attribute_null, $21 | block_attribute_null ;96
	.BYTE $01 | block_attribute_null, $29 | block_attribute_wall, $01 | block_attribute_null, $29 | block_attribute_wall ;97
	.BYTE $18 | block_attribute_wall, $1A | block_attribute_wall, $22 | block_attribute_null, $21 | block_attribute_null ;98
	.BYTE $1A | block_attribute_wall, $22 | block_attribute_null, $21 | block_attribute_null, $21 | block_attribute_null ;99
	.BYTE $21 | block_attribute_null, $21 | block_attribute_null, $1A | block_attribute_wall, $22 | block_attribute_null ;9A
	.BYTE $18 | block_attribute_wall, $18 | block_attribute_wall, $21 | block_attribute_null, $20 | block_attribute_wall ;9B
	.BYTE $21 | block_attribute_null, $21 | block_attribute_null, $19 | block_attribute_wall, $19 | block_attribute_wall ;9C
	.BYTE $20 | block_attribute_wall, $18 | block_attribute_wall, $21 | block_attribute_null, $21 | block_attribute_null ;9D
	.BYTE $18 | block_attribute_wall, $1A | block_attribute_wall, $21 | block_attribute_null, $21 | block_attribute_null ;9E
	.BYTE $3E | block_attribute_null, $37 | block_attribute_null, $09 | block_attribute_wall, $0A | block_attribute_wall ;9F
	.BYTE $1B | block_attribute_wall, $1D | block_attribute_wall, $00 | block_attribute_null, $00 | block_attribute_null ;A0
	.BYTE $1B | block_attribute_wall, $1D | block_attribute_wall, $1A | block_attribute_wall, $1C | block_attribute_wall ;A1
	.BYTE $1B | block_attribute_wall, $1F | block_attribute_wall, $1A | block_attribute_wall, $1C | block_attribute_wall ;A2
	.BYTE $1B | block_attribute_wall, $1D | block_attribute_wall, $2E | block_attribute_null, $2D | block_attribute_null ;A3
	.BYTE $1B | block_attribute_wall, $1F | block_attribute_wall, $2D | block_attribute_null, $2D | block_attribute_null ;A4
	.BYTE $19 | block_attribute_wall, $1D | block_attribute_wall, $2D | block_attribute_null, $2D | block_attribute_null ;A5
	.BYTE $1F | block_attribute_wall, $2E | block_attribute_null, $2D | block_attribute_null, $2D | block_attribute_null ;A6
	.BYTE $1B | block_attribute_wall, $1F | block_attribute_wall, $1A | block_attribute_wall, $1E | block_attribute_wall ;A7
	.BYTE $2D | block_attribute_null, $2D | block_attribute_null, $2D | block_attribute_null, $2D | block_attribute_null ;A8
	.BYTE $2D | block_attribute_null, $2D | block_attribute_null, $20 | block_attribute_wall, $2E | block_attribute_null ;A9
	.BYTE $20 | block_attribute_wall, $2E | block_attribute_null, $2D | block_attribute_null, $2D | block_attribute_null ;AA
	.BYTE $2D | block_attribute_null, $2D | block_attribute_null, $2D | block_attribute_null, $20 | block_attribute_wall ;AB
	.BYTE $2D | block_attribute_null, $2D | block_attribute_null, $2E | block_attribute_null, $2D | block_attribute_null ;AC
	.BYTE $2E | block_attribute_null, $2D | block_attribute_null, $2D | block_attribute_null, $2D | block_attribute_null ;AD
	.BYTE $2D | block_attribute_null, $2D | block_attribute_null, $1E | block_attribute_wall, $2E | block_attribute_null ;AE
	.BYTE $2E | block_attribute_null, $2D | block_attribute_null, $2E | block_attribute_null, $2D | block_attribute_null ;AF
	.BYTE $19 | block_attribute_wall, $1D | block_attribute_wall, $18 | block_attribute_wall, $1C | block_attribute_wall ;B0
	.BYTE $1B | block_attribute_wall, $1D | block_attribute_wall, $18 | block_attribute_wall, $1C | block_attribute_wall ;B1
	.BYTE $2D | block_attribute_null, $19 | block_attribute_wall, $2D | block_attribute_null, $18 | block_attribute_wall ;B2
	.BYTE $1F | block_attribute_wall, $2E | block_attribute_null, $1E | block_attribute_wall, $2E | block_attribute_null ;B3
	.BYTE $2E | block_attribute_null, $2D | block_attribute_null, $1A | block_attribute_wall, $1C | block_attribute_wall ;B4
	.BYTE $2D | block_attribute_null, $2D | block_attribute_null, $2D | block_attribute_null, $18 | block_attribute_wall ;B5
	.BYTE $2D | block_attribute_null, $2D | block_attribute_null, $1A | block_attribute_wall, $1C | block_attribute_wall ;B6
	.BYTE $1F | block_attribute_wall, $2E | block_attribute_null, $1A | block_attribute_wall, $1C | block_attribute_wall ;B7
	.BYTE $2D | block_attribute_null, $19 | block_attribute_wall, $1A | block_attribute_wall, $1C | block_attribute_wall ;B8
	.BYTE $2D | block_attribute_null, $20 | block_attribute_wall, $2D | block_attribute_null, $20 | block_attribute_wall ;B9
	.BYTE $21 | block_attribute_wall, $20 | block_attribute_wall, $2D | block_attribute_null, $20 | block_attribute_wall ;BA
	.BYTE $21 | block_attribute_wall, $21 | block_attribute_wall, $2D | block_attribute_null, $2D | block_attribute_null ;BB
	.BYTE $2D | block_attribute_null, $21 | block_attribute_wall, $2D | block_attribute_null, $2D | block_attribute_null ;BC
	.BYTE $20 | block_attribute_wall, $01 | block_attribute_2,    $20 | block_attribute_wall, $01 | block_attribute_2    ;BD
	.BYTE $00 | block_attribute_null, $3C | block_attribute_wall, $00 | block_attribute_null, $3C | block_attribute_wall ;BE
	.BYTE $3C | block_attribute_wall, $3C | block_attribute_wall, $3C | block_attribute_wall, $3C | block_attribute_wall ;BF
	.BYTE $1B | block_attribute_wall, $1D | block_attribute_wall, $1E | block_attribute_wall, $2E | block_attribute_null ;C0
	.BYTE $1B | block_attribute_wall, $1D | block_attribute_wall, $01 | block_attribute_2,    $01 | block_attribute_2    ;C1
	.BYTE $01 | block_attribute_2,    $01 | block_attribute_2,    $1A | block_attribute_wall, $1C | block_attribute_wall ;C2
	.BYTE $1B | block_attribute_wall, $1D | block_attribute_wall, $2D | block_attribute_null, $2D | block_attribute_null ;C3
	.BYTE $1B | block_attribute_wall, $1D | block_attribute_wall, $28 | block_attribute_2,    $01 | block_attribute_2    ;C4
	.BYTE $28 | block_attribute_2,    $01 | block_attribute_2,    $28 | block_attribute_2,    $01 | block_attribute_2    ;C5
	.BYTE $2A | block_attribute_null, $2A | block_attribute_null, $2C | block_attribute_null, $2C | block_attribute_null ;C6
	.BYTE $2A | block_attribute_null, $2A | block_attribute_null, $2B | block_attribute_null, $2B | block_attribute_null ;C7
	.BYTE $2D | block_attribute_null, $20 | block_attribute_wall, $1A | block_attribute_wall, $1E | block_attribute_wall ;C8
	.BYTE $01 | block_attribute_2,    $19 | block_attribute_wall, $1A | block_attribute_wall, $1C | block_attribute_wall ;C9
	.BYTE $2D | block_attribute_null, $2D | block_attribute_null, $00 | block_attribute_null, $2D | block_attribute_null ;CA
	.BYTE $1B | block_attribute_wall, $1D | block_attribute_wall, $2F | block_attribute_3,    $2F | block_attribute_3    ;CB
	.BYTE $1B | block_attribute_wall, $1D | block_attribute_wall, $21 | block_attribute_wall, $21 | block_attribute_wall ;CC
	.BYTE $01 | block_attribute_2,    $2F | block_attribute_3,    $01 | block_attribute_2,    $2F | block_attribute_3    ;CD
	.BYTE $01 | block_attribute_2,    $01 | block_attribute_2,    $01 | block_attribute_2,    $01 | block_attribute_2    ;CE
	.BYTE $21 | block_attribute_wall, $21 | block_attribute_wall, $21 | block_attribute_wall, $21 | block_attribute_wall ;CF
	.BYTE $21 | block_attribute_wall, $21 | block_attribute_wall, $2F | block_attribute_3,    $2F | block_attribute_3    ;D0
	.BYTE $21 | block_attribute_wall, $21 | block_attribute_wall, $01 | block_attribute_2,    $29 | block_attribute_2    ;D1
	.BYTE $21 | block_attribute_wall, $21 | block_attribute_wall, $00 | block_attribute_2,    $00 | block_attribute_2    ;D2
	.BYTE $01 | block_attribute_2,    $2F | block_attribute_3,    $21 | block_attribute_wall, $21 | block_attribute_wall ;D3
	.BYTE $01 | block_attribute_2,    $29 | block_attribute_2,    $21 | block_attribute_wall, $21 | block_attribute_wall ;D4
	.BYTE $00 | block_attribute_2,    $00 | block_attribute_2,    $21 | block_attribute_wall, $21 | block_attribute_wall ;D5
	.BYTE $21 | block_attribute_wall, $21 | block_attribute_wall, $2F | block_attribute_3,    $29 | block_attribute_2    ;D6
	.BYTE $21 | block_attribute_wall, $21 | block_attribute_wall, $01 | block_attribute_2,    $2F | block_attribute_3    ;D7
	.BYTE $2F | block_attribute_3,    $29 | block_attribute_2,    $2F | block_attribute_3,    $29 | block_attribute_2    ;D8
	.BYTE $1F | block_attribute_wall, $00 | block_attribute_null, $1E | block_attribute_wall, $08 | block_attribute_null ;D9
	.BYTE $01 | block_attribute_2,    $01 | block_attribute_2,    $01 | block_attribute_2,    $21 | block_attribute_wall ;DA
	.BYTE $01 | block_attribute_2,    $01 | block_attribute_2,    $01 | block_attribute_2,    $2F | block_attribute_3    ;DB
	.BYTE $01 | block_attribute_2,    $2F | block_attribute_3,    $01 | block_attribute_2,    $01 | block_attribute_2    ;DC
	.BYTE $01 | block_attribute_2,    $29 | block_attribute_2,    $01 | block_attribute_2,    $29 | block_attribute_2    ;DD
	.BYTE $28 | block_attribute_2,    $01 | block_attribute_2,    $18 | block_attribute_wall, $1C | block_attribute_wall ;DE
	.BYTE $1F | block_attribute_wall, $01 | block_attribute_2,    $1E | block_attribute_wall, $01 | block_attribute_2    ;DF
	.BYTE $1B | block_attribute_wall, $1D | block_attribute_wall, $1A | block_attribute_wall, $1C | block_attribute_wall ;E0
	.BYTE $19 | block_attribute_wall, $1D | block_attribute_wall, $18 | block_attribute_wall, $1C | block_attribute_wall ;E1
	.BYTE $19 | block_attribute_wall, $1D | block_attribute_wall, $01 | block_attribute_2,    $2F | block_attribute_3    ;E2
	.BYTE $1B | block_attribute_wall, $1D | block_attribute_wall, $2F | block_attribute_3,    $2F | block_attribute_3    ;E3
	.BYTE $2F | block_attribute_3,    $2F | block_attribute_3,    $1A | block_attribute_wall, $1C | block_attribute_wall ;E4
	.BYTE $1F | block_attribute_wall, $2F | block_attribute_3,    $1E | block_attribute_wall, $2F | block_attribute_3    ;E5
	.BYTE $1F | block_attribute_wall, $2F | block_attribute_3,    $2F | block_attribute_3,    $2F | block_attribute_3    ;E6
	.BYTE $31 | block_attribute_null, $33 | block_attribute_null, $32 | block_attribute_null, $34 | block_attribute_null ;E7
	.BYTE $01 | block_attribute_2,    $01 | block_attribute_2,    $1E | block_attribute_wall, $01 | block_attribute_2    ;E8
	.BYTE $2F | block_attribute_3,    $01 | block_attribute_2,    $1A | block_attribute_wall, $1C | block_attribute_wall ;E9
	.BYTE $1B | block_attribute_wall, $1D | block_attribute_wall, $1E | block_attribute_wall, $2F | block_attribute_3    ;EA
	.BYTE $1B | block_attribute_wall, $1F | block_attribute_wall, $2F | block_attribute_3,    $2F | block_attribute_3    ;EB
	.BYTE $19 | block_attribute_wall, $1D | block_attribute_wall, $1A | block_attribute_wall, $1C | block_attribute_wall ;EC
	.BYTE $2F | block_attribute_3,    $2F | block_attribute_3,    $01 | block_attribute_2,    $01 | block_attribute_2    ;ED
	.BYTE $01 | block_attribute_2,    $01 | block_attribute_2,    $2F | block_attribute_3,    $2F | block_attribute_3    ;EE
	.BYTE $2F | block_attribute_3,    $01 | block_attribute_2,    $2F | block_attribute_3,    $01 | block_attribute_2    ;EF
	.BYTE $01 | block_attribute_2,    $01 | block_attribute_2,    $2F | block_attribute_3,    $01 | block_attribute_2    ;F0
	.BYTE $1B | block_attribute_wall, $1F | block_attribute_wall, $1A | block_attribute_wall, $1E | block_attribute_wall ;F1
	.BYTE $1B | block_attribute_wall, $1D | block_attribute_wall, $01 | block_attribute_2,    $2F | block_attribute_3    ;F2
	.BYTE $1B | block_attribute_wall, $1D | block_attribute_wall, $1A | block_attribute_wall, $1E | block_attribute_wall ;F3
	.BYTE $2F | block_attribute_3,    $01 | block_attribute_2,    $1E | block_attribute_wall, $2F | block_attribute_3    ;F4
	.BYTE $01 | block_attribute_2,    $2F | block_attribute_3,    $2F | block_attribute_3,    $18 | block_attribute_wall ;F5
	.BYTE $2F | block_attribute_3,    $19 | block_attribute_wall, $01 | block_attribute_2,    $2F | block_attribute_3    ;F6
	.BYTE $2F | block_attribute_3,    $01 | block_attribute_2,    $01 | block_attribute_2,    $01 | block_attribute_2    ;F7
	.BYTE $01 | block_attribute_2,    $19 | block_attribute_wall, $01 | block_attribute_2,    $18 | block_attribute_wall ;F8
	.BYTE $1B | block_attribute_wall, $1D | block_attribute_wall, $01 | block_attribute_2,    $20 | block_attribute_wall ;F9
	.BYTE $01 | block_attribute_2,    $20 | block_attribute_wall, $01 | block_attribute_2,    $20 | block_attribute_wall ;FA
	.BYTE $01 | block_attribute_2,    $01 | block_attribute_2,    $01 | block_attribute_2,    $18 | block_attribute_wall ;FB
	.BYTE $2F | block_attribute_3,    $29 | block_attribute_2,    $21 | block_attribute_wall, $21 | block_attribute_wall ;FC
	.BYTE $1B | block_attribute_wall, $1D | block_attribute_wall, $00 | block_attribute_null, $00 | block_attribute_null ;FD
	.BYTE $00 | block_attribute_null, $00 | block_attribute_null, $08 | block_attribute_null, $08 | block_attribute_null ;FE
	.BYTE $00 | block_attribute_null, $19 | block_attribute_wall, $08 | block_attribute_null, $18 | block_attribute_wall ;FF