base $8000
;incsrc audio.asm
pad $8a50
incsrc track_data_pointers.asm
pad $8ad6
incsrc .\music\flash.asm
;incsrc .\music\wood.asm
;incsrc .\music\crash.asm
;incsrc .\music\heat.asm
;incsrc .\music\air.asm
;incsrc .\music\metal.asm
;incsrc .\music\quick.asm
;incsrc .\music\bubble.asm
;incsrc .\music\wily1.asm
;incsrc .\music\wily3.asm
;incsrc .\music\game_start.asm
;incsrc .\music\boss.asm
;incsrc .\music\stage_select.asm
;incsrc .\music\title.asm
;incsrc .\music\opening.asm
;incsrc .\music\game_over.asm
;incsrc .\music\pass_word.asm
;incsrc .\music\wily_map.asm
;incsrc .\music\ufo.asm
;incsrc .\music\ending.asm
;incsrc .\music\credits.asm
;incsrc .\music\stage_clear.asm
;incsrc .\music\all_stage_clear.asm
;incsrc .\music\get_weapon.asm
;incsrc .\sfx\time_stopper.asm
;incsrc .\unused\unused22.asm
;incsrc .\sfx\metal_blade.asm
;incsrc .\sfx\shoot.asm
;incsrc .\sfx\enemy_shoot.asm
;incsrc .\sfx\damage_mm.asm
;incsrc .\sfx\force_beam.asm
;incsrc .\sfx\health_bar.asm
;incsrc .\sfx\landing.asm
;incsrc .\sfx\broken_alien.asm
;incsrc .\sfx\destroy_enemy.asm
;incsrc .\sfx\dragon.asm
;incsrc .\sfx\shoot_recoil.asm
;incsrc .\sfx\crash_bomb.asm
;incsrc .\sfx\change_weapon.asm
;incsrc .\sfx\teleport_in.asm
;incsrc .\sfx\leaf_shield.asm
;incsrc .\sfx\open_menu.asm
;incsrc .\unused\unused33.asm
;incsrc .\sfx\boss_door.asm
;incsrc .\sfx\atomic_fire_charge1.asm
;incsrc .\sfx\atomic_fire_charge2.asm
;incsrc .\sfx\atomic_fire_charge3.asm
;incsrc .\sfx\atomic_fire_release.asm
;incsrc .\sfx\fly_boy.asm
;incsrc .\sfx\teleport_out.asm
;incsrc .\sfx\water.asm
;incsrc .\sfx\yoku_block.asm
;incsrc .\sfx\red_liquid_1.asm
;incsrc .\sfx\red_liquid_2.asm
;incsrc .\sfx\air_shooter.aasm
;incsrc .\unused\unused40.asm
;incsrc .\sfx\death.asm
;incsrc .\sfx\1up.asm
;incsrc .\unused\unusedpre.asm
pad $c000