;music
	dw music_flash
	dw music_wood
	dw music_crash
	dw music_heat
	dw music_air
	dw music_metal
	dw music_quick
	dw music_bubble
	dw music_wily1
	dw music_wily3
	dw music_game_start
	dw music_boss
	dw music_stage_select
	dw music_title
	dw music_opening
	dw music_game_over
	dw music_pass_word
	dw music_wily_map
	dw music_ufo
	dw music_ending
	dw music_credits
	dw music_stage_clear
	dw music_all_stage_clear
	dw music_get_weapon
	dw music_game_over
	dw music_game_over
	dw music_game_over
	dw music_game_over
	dw music_game_over
	dw music_game_over
	dw music_game_over
	dw music_game_over
	dw music_game_over

;sfx
	dw sfx_time_stopper
	dw sfx_unused22
	dw sfx_metal_blade
	dw sfx_shoot
	dw sfx_enemy_shoot
	dw sfx_damage_mm
	dw sfx_force_beam
	dw sfx_health_bar
	dw sfx_landing
	dw sfx_broken_alien
	dw sfx_destroy_enemy
	dw sfx_dragon
	dw sfx_shoot_recoil
	dw sfx_crash_bomn
	dw sfx_change_weapon
	dw sfx_teleport_in
	dw sfx_leaf_shield
	dw sfx_open_menu
	dw sfx_unused33
	dw sfx_boss_door
	dw sfx_atomic_fire_charge1
	dw sfx_atomic_fire_charge2
	dw sfx_atomic_fire_charge3
	dw sfx_atomic_fire_release
	dw sfx_fly_boy
	dw sfx_teleport_out
	dw sfx_water
	dw sfx_yoku_block
	dw sfx_red_liquid_1
	dw sfx_red_liquid_2
	dw sfx_air_shooter
	dw sfx_unused40
	dw sfx_death
	dw sfx_1up