track_pointers:
	.WORD music_flashman
	.WORD music_woodman
	.WORD music_crashman
	.WORD music_heatman
	.WORD music_airman
	.WORD music_metalman
	.WORD music_quickman
	.WORD music_bubbleman
	.WORD music_wily1_2
	.WORD music_wily3_4_5
	.WORD music_boss_show
	.WORD music_boss_fighting
	.WORD music_stage_select
	.WORD music_title
	.WORD music_opening
	.WORD music_game_over
	.WORD music_password
	.WORD music_wily_castle
	.WORD music_wily_ufo
	.WORD music_ending
	.WORD music_staff_roll
	.WORD music_boss_defeated
	.WORD music_wily_defeated
	.WORD music_get_weapon
	.WORD music_game_over
	.WORD music_game_over
	.WORD music_game_over
	.WORD music_game_over
	.WORD music_game_over
	.WORD music_game_over
	.WORD music_game_over
	.WORD music_game_over
	.WORD music_game_over
	.WORD sfx_time_stopper
	.WORD sfx_22
	.WORD sfx_metal_blade
	.WORD sfx_mega_buster
	.WORD sfx_enemy_bullet
	.WORD sfx_megaman_hit
	.WORD sfx_force_beam
	.WORD sfx_refill
	.WORD sfx_landing
	.WORD sfx_wily_control
	.WORD sfx_enemy_hit
	.WORD sfx_mecha_dragon
	.WORD sfx_enemy_immune
	.WORD sfx_crash_bomber_grab
	.WORD sfx_select
	.WORD sfx_teleport_in
	.WORD sfx_leaf_shield
	.WORD sfx_open_menu
	.WORD sfx_33
	.WORD sfx_door
	.WORD sfx_atomic_fire_charge_1
	.WORD sfx_atomic_fire_charge_2
	.WORD sfx_atomic_fire_charge_3
	.WORD sfx_atomic_fire_release
	.WORD sfx_fly_boy
	.WORD sfx_teleport_out
	.WORD sfx_jump_into_water
	.WORD sfx_appearing_block
	.WORD sfx_red_liquid_1
	.WORD sfx_red_liquid_2
	.WORD sfx_air_shooter
	.WORD sfx_40
	.WORD sfx_death
	.WORD sfx_1up
