;32x32 blocksets with 16x16 blocksets | block attribute.
;block_attribute 2 and 3 setting see home/blocksets.asm. 
	      ;top left,                  bottom left,                top right,                  bottom right
	.BYTE $00 | block_attribute_null, $00 | block_attribute_null, $00 | block_attribute_null, $00 | block_attribute_null ;00
	.BYTE $29 | block_attribute_wall, $29 | block_attribute_wall, $28 | block_attribute_wall, $28 | block_attribute_wall ;01
	.BYTE $2A | block_attribute_wall, $2A | block_attribute_wall, $29 | block_attribute_wall, $29 | block_attribute_wall ;02
	.BYTE $31 | block_attribute_wall, $29 | block_attribute_wall, $26 | block_attribute_wall, $28 | block_attribute_wall ;03
	.BYTE $25 | block_attribute_wall, $2A | block_attribute_wall, $31 | block_attribute_wall, $29 | block_attribute_wall ;04
	.BYTE $29 | block_attribute_wall, $29 | block_attribute_wall, $30 | block_attribute_wall, $29 | block_attribute_wall ;05
	.BYTE $32 | block_attribute_wall, $29 | block_attribute_wall, $29 | block_attribute_wall, $29 | block_attribute_wall ;06
	.BYTE $33 | block_attribute_null, $25 | block_attribute_wall, $33 | block_attribute_null, $31 | block_attribute_wall ;07
	.BYTE $29 | block_attribute_wall, $29 | block_attribute_wall, $29 | block_attribute_wall, $29 | block_attribute_wall ;08
	.BYTE $37 | block_attribute_wall, $37 | block_attribute_wall, $28 | block_attribute_wall, $28 | block_attribute_wall ;09
	.BYTE $2A | block_attribute_wall, $2A | block_attribute_wall, $37 | block_attribute_wall, $37 | block_attribute_wall ;0A
	.BYTE $31 | block_attribute_wall, $37 | block_attribute_wall, $26 | block_attribute_wall, $28 | block_attribute_wall ;0B
	.BYTE $25 | block_attribute_wall, $2A | block_attribute_wall, $31 | block_attribute_wall, $37 | block_attribute_wall ;0C
	.BYTE $37 | block_attribute_wall, $37 | block_attribute_wall, $30 | block_attribute_wall, $29 | block_attribute_wall ;0D
	.BYTE $32 | block_attribute_wall, $29 | block_attribute_wall, $37 | block_attribute_wall, $37 | block_attribute_wall ;0E
	.BYTE $22 | block_attribute_wall, $2D | block_attribute_wall, $29 | block_attribute_wall, $21 | block_attribute_wall ;0F
	.BYTE $31 | block_attribute_wall, $29 | block_attribute_wall, $31 | block_attribute_wall, $29 | block_attribute_wall ;10
	.BYTE $2F | block_attribute_wall, $37 | block_attribute_wall, $28 | block_attribute_wall, $28 | block_attribute_wall ;11
	.BYTE $2A | block_attribute_wall, $2A | block_attribute_wall, $2F | block_attribute_wall, $37 | block_attribute_wall ;12
	.BYTE $29 | block_attribute_wall, $21 | block_attribute_wall, $28 | block_attribute_wall, $2E | block_attribute_wall ;13
	.BYTE $2A | block_attribute_wall, $2D | block_attribute_wall, $29 | block_attribute_wall, $21 | block_attribute_wall ;14
	.BYTE $29 | block_attribute_wall, $29 | block_attribute_wall, $29 | block_attribute_wall, $20 | block_attribute_wall ;15
	.BYTE $29 | block_attribute_wall, $22 | block_attribute_wall, $29 | block_attribute_wall, $29 | block_attribute_wall ;16
	.BYTE $29 | block_attribute_wall, $29 | block_attribute_wall, $30 | block_attribute_wall, $20 | block_attribute_wall ;17
	.BYTE $31 | block_attribute_wall, $29 | block_attribute_wall, $31 | block_attribute_wall, $37 | block_attribute_wall ;18
	.BYTE $37 | block_attribute_wall, $37 | block_attribute_wall, $29 | block_attribute_wall, $29 | block_attribute_wall ;19
	.BYTE $29 | block_attribute_wall, $29 | block_attribute_wall, $37 | block_attribute_wall, $37 | block_attribute_wall ;1A
	.BYTE $37 | block_attribute_wall, $21 | block_attribute_wall, $28 | block_attribute_wall, $2E | block_attribute_wall ;1B
	.BYTE $2A | block_attribute_wall, $2D | block_attribute_wall, $37 | block_attribute_wall, $21 | block_attribute_wall ;1C
	.BYTE $27 | block_attribute_wall, $29 | block_attribute_wall, $27 | block_attribute_wall, $20 | block_attribute_wall ;1D
	.BYTE $27 | block_attribute_wall, $22 | block_attribute_wall, $27 | block_attribute_wall, $29 | block_attribute_wall ;1E
	.BYTE $31 | block_attribute_wall, $21 | block_attribute_wall, $31 | block_attribute_wall, $21 | block_attribute_wall ;1F
	.BYTE $31 | block_attribute_wall, $37 | block_attribute_wall, $31 | block_attribute_wall, $29 | block_attribute_wall ;20
	.BYTE $2F | block_attribute_wall, $37 | block_attribute_wall, $27 | block_attribute_wall, $29 | block_attribute_wall ;21
	.BYTE $27 | block_attribute_wall, $29 | block_attribute_wall, $2F | block_attribute_wall, $37 | block_attribute_wall ;22
	.BYTE $27 | block_attribute_wall, $21 | block_attribute_wall, $28 | block_attribute_wall, $2E | block_attribute_wall ;23
	.BYTE $2A | block_attribute_wall, $2D | block_attribute_wall, $27 | block_attribute_wall, $21 | block_attribute_wall ;24
	.BYTE $37 | block_attribute_wall, $37 | block_attribute_wall, $29 | block_attribute_wall, $20 | block_attribute_wall ;25
	.BYTE $29 | block_attribute_wall, $22 | block_attribute_wall, $37 | block_attribute_wall, $37 | block_attribute_wall ;26
	.BYTE $31 | block_attribute_wall, $21 | block_attribute_wall, $26 | block_attribute_wall, $2E | block_attribute_wall ;27
	.BYTE $29 | block_attribute_wall, $21 | block_attribute_wall, $29 | block_attribute_wall, $21 | block_attribute_wall ;28
	.BYTE $27 | block_attribute_wall, $21 | block_attribute_wall, $27 | block_attribute_wall, $21 | block_attribute_wall ;29
	.BYTE $29 | block_attribute_wall, $21 | block_attribute_wall, $37 | block_attribute_wall, $21 | block_attribute_wall ;2A
	.BYTE $2F | block_attribute_wall, $21 | block_attribute_wall, $28 | block_attribute_wall, $2E | block_attribute_wall ;2B
	.BYTE $2A | block_attribute_wall, $2D | block_attribute_wall, $2F | block_attribute_wall, $21 | block_attribute_wall ;2C
	.BYTE $2F | block_attribute_wall, $37 | block_attribute_wall, $27 | block_attribute_wall, $20 | block_attribute_wall ;2D
	.BYTE $27 | block_attribute_wall, $22 | block_attribute_wall, $2F | block_attribute_wall, $37 | block_attribute_wall ;2E
	.BYTE $31 | block_attribute_wall, $34 | block_attribute_null, $31 | block_attribute_wall, $34 | block_attribute_null ;2F
	.BYTE $37 | block_attribute_wall, $21 | block_attribute_wall, $29 | block_attribute_wall, $21 | block_attribute_wall ;30
	.BYTE $2F | block_attribute_wall, $21 | block_attribute_wall, $27 | block_attribute_wall, $21 | block_attribute_wall ;31
	.BYTE $27 | block_attribute_wall, $21 | block_attribute_wall, $2F | block_attribute_wall, $21 | block_attribute_wall ;32
	.BYTE $27 | block_attribute_wall, $29 | block_attribute_wall, $27 | block_attribute_wall, $29 | block_attribute_wall ;33
	.BYTE $28 | block_attribute_wall, $28 | block_attribute_wall, $34 | block_attribute_null, $33 | block_attribute_null ;34
	.BYTE $25 | block_attribute_wall, $2A | block_attribute_wall, $26 | block_attribute_wall, $28 | block_attribute_wall ;35
	.BYTE $31 | block_attribute_wall, $37 | block_attribute_wall, $26 | block_attribute_wall, $30 | block_attribute_wall ;36
	.BYTE $25 | block_attribute_wall, $2D | block_attribute_wall, $31 | block_attribute_wall, $21 | block_attribute_wall ;37
	.BYTE $29 | block_attribute_wall, $20 | block_attribute_wall, $28 | block_attribute_wall, $2E | block_attribute_wall ;38
	.BYTE $27 | block_attribute_wall, $29 | block_attribute_wall, $28 | block_attribute_wall, $28 | block_attribute_wall ;39
	.BYTE $2A | block_attribute_wall, $2A | block_attribute_wall, $27 | block_attribute_wall, $29 | block_attribute_wall ;3A
	.BYTE $29 | block_attribute_wall, $27 | block_attribute_wall, $29 | block_attribute_wall, $27 | block_attribute_wall ;3B
	.BYTE $28 | block_attribute_wall, $2E | block_attribute_wall, $33 | block_attribute_null, $33 | block_attribute_null ;3C
	.BYTE $2A | block_attribute_wall, $2A | block_attribute_wall, $30 | block_attribute_wall, $29 | block_attribute_wall ;3D
	.BYTE $33 | block_attribute_null, $31 | block_attribute_wall, $33 | block_attribute_null, $31 | block_attribute_wall ;3E
	.BYTE $33 | block_attribute_null, $31 | block_attribute_wall, $33 | block_attribute_null, $26 | block_attribute_wall ;3F
	.BYTE $34 | block_attribute_null, $31 | block_attribute_wall, $34 | block_attribute_null, $31 | block_attribute_wall ;40
	.BYTE $34 | block_attribute_null, $31 | block_attribute_wall, $34 | block_attribute_null, $26 | block_attribute_wall ;41
	.BYTE $34 | block_attribute_null, $25 | block_attribute_wall, $34 | block_attribute_null, $31 | block_attribute_wall ;42
	.BYTE $2A | block_attribute_wall, $32 | block_attribute_wall, $27 | block_attribute_wall, $29 | block_attribute_wall ;43
	.BYTE $33 | block_attribute_null, $19 | block_attribute_wall, $33 | block_attribute_null, $31 | block_attribute_wall ;44
	.BYTE $2A | block_attribute_wall, $2A | block_attribute_wall, $28 | block_attribute_wall, $28 | block_attribute_wall ;45
	.BYTE $34 | block_attribute_null, $19 | block_attribute_wall, $34 | block_attribute_null, $31 | block_attribute_wall ;46
	.BYTE $28 | block_attribute_wall, $28 | block_attribute_wall, $33 | block_attribute_null, $33 | block_attribute_null ;47
	.BYTE $21 | block_attribute_wall, $34 | block_attribute_null, $21 | block_attribute_wall, $34 | block_attribute_null ;48
	.BYTE $21 | block_attribute_wall, $34 | block_attribute_null, $2E | block_attribute_wall, $34 | block_attribute_null ;49
	.BYTE $2D | block_attribute_wall, $34 | block_attribute_null, $21 | block_attribute_wall, $34 | block_attribute_null ;4A
	.BYTE $25 | block_attribute_wall, $2D | block_attribute_wall, $26 | block_attribute_wall, $2E | block_attribute_wall ;4B
	.BYTE $34 | block_attribute_null, $25 | block_attribute_wall, $34 | block_attribute_null, $26 | block_attribute_wall ;4C
	.BYTE $2A | block_attribute_wall, $2D | block_attribute_wall, $28 | block_attribute_wall, $2E | block_attribute_wall ;4D
	.BYTE $33 | block_attribute_null, $26 | block_attribute_wall, $33 | block_attribute_null, $33 | block_attribute_null ;4E
	.BYTE $2E | block_attribute_wall, $34 | block_attribute_null, $33 | block_attribute_null, $33 | block_attribute_null ;4F
	.BYTE $33 | block_attribute_null, $31 | block_attribute_wall, $33 | block_attribute_null, $1A | block_attribute_wall ;50
	.BYTE $2A | block_attribute_wall, $2A | block_attribute_wall, $28 | block_attribute_wall, $30 | block_attribute_wall ;51
	.BYTE $2A | block_attribute_wall, $2A | block_attribute_wall, $27 | block_attribute_wall, $20 | block_attribute_wall ;52
	.BYTE $26 | block_attribute_wall, $2E | block_attribute_wall, $33 | block_attribute_null, $33 | block_attribute_null ;53
	.BYTE $2D | block_attribute_wall, $34 | block_attribute_null, $1B | block_attribute_wall, $34 | block_attribute_null ;54
	.BYTE $25 | block_attribute_wall, $2A | block_attribute_wall, $32 | block_attribute_wall, $29 | block_attribute_wall ;55
	.BYTE $33 | block_attribute_null, $33 | block_attribute_null, $33 | block_attribute_null, $25 | block_attribute_wall ;56
	.BYTE $33 | block_attribute_null, $33 | block_attribute_null, $2A | block_attribute_wall, $2A | block_attribute_wall ;57
	.BYTE $31 | block_attribute_wall, $34 | block_attribute_null, $1A | block_attribute_wall, $34 | block_attribute_null ;58
	.BYTE $27 | block_attribute_wall, $21 | block_attribute_wall, $27 | block_attribute_wall, $22 | block_attribute_wall ;59
	.BYTE $2D | block_attribute_wall, $34 | block_attribute_null, $2E | block_attribute_wall, $34 | block_attribute_null ;5A
	.BYTE $29 | block_attribute_wall, $22 | block_attribute_wall, $20 | block_attribute_wall, $28 | block_attribute_wall ;5B
	.BYTE $34 | block_attribute_null, $33 | block_attribute_null, $2A | block_attribute_wall, $2D | block_attribute_wall ;5C
	.BYTE $33 | block_attribute_null, $33 | block_attribute_null, $2A | block_attribute_wall, $2D | block_attribute_wall ;5D
	.BYTE $2A | block_attribute_wall, $2D | block_attribute_wall, $29 | block_attribute_wall, $22 | block_attribute_wall ;5E
	.BYTE $34 | block_attribute_null, $33 | block_attribute_null, $2A | block_attribute_wall, $2A | block_attribute_wall ;5F
	.BYTE $23 | block_attribute_null, $2B | block_attribute_null, $24 | block_attribute_null, $2C | block_attribute_null ;60
	.BYTE $33 | block_attribute_null, $33 | block_attribute_null, $23 | block_attribute_null, $2B | block_attribute_null ;61
	.BYTE $24 | block_attribute_null, $2C | block_attribute_null, $33 | block_attribute_null, $33 | block_attribute_null ;62
	.BYTE $36 | block_attribute_null, $33 | block_attribute_null, $36 | block_attribute_null, $35 | block_attribute_null ;63
	.BYTE $18 | block_attribute_wall, $34 | block_attribute_null, $18 | block_attribute_wall, $34 | block_attribute_null ;64
	.BYTE $1A | block_attribute_wall, $34 | block_attribute_null, $33 | block_attribute_null, $33 | block_attribute_null ;65
	.BYTE $33 | block_attribute_null, $18 | block_attribute_wall, $33 | block_attribute_null, $18 | block_attribute_wall ;66
	.BYTE $33 | block_attribute_null, $33 | block_attribute_null, $19 | block_attribute_wall, $34 | block_attribute_null ;67
	.BYTE $35 | block_attribute_null, $35 | block_attribute_null, $35 | block_attribute_null, $35 | block_attribute_null ;68
	.BYTE $35 | block_attribute_null, $35 | block_attribute_null, $33 | block_attribute_null, $35 | block_attribute_null ;69
	.BYTE $35 | block_attribute_null, $33 | block_attribute_null, $35 | block_attribute_null, $35 | block_attribute_null ;6A
	.BYTE $34 | block_attribute_null, $33 | block_attribute_null, $34 | block_attribute_null, $33 | block_attribute_null ;6B
	.BYTE $34 | block_attribute_null, $33 | block_attribute_null, $33 | block_attribute_null, $33 | block_attribute_null ;6C
	.BYTE $33 | block_attribute_null, $33 | block_attribute_null, $34 | block_attribute_null, $33 | block_attribute_null ;6D
	.BYTE $33 | block_attribute_null, $33 | block_attribute_null, $25 | block_attribute_wall, $2D | block_attribute_wall ;6E
	.BYTE $31 | block_attribute_wall, $29 | block_attribute_wall, $31 | block_attribute_wall, $20 | block_attribute_wall ;6F
	.BYTE $33 | block_attribute_null, $33 | block_attribute_null, $33 | block_attribute_null, $33 | block_attribute_null ;70
	.BYTE $1C | block_attribute_null, $33 | block_attribute_null, $33 | block_attribute_null, $1C | block_attribute_null ;71
	.BYTE $33 | block_attribute_null, $1C | block_attribute_null, $1C | block_attribute_null, $33 | block_attribute_null ;72
	.BYTE $1C | block_attribute_null, $1C | block_attribute_null, $1C | block_attribute_null, $1C | block_attribute_null ;73
	.BYTE $33 | block_attribute_null, $1C | block_attribute_null, $1C | block_attribute_null, $1C | block_attribute_null ;74
	.BYTE $1C | block_attribute_null, $1C | block_attribute_null, $1C | block_attribute_null, $33 | block_attribute_null ;75
	.BYTE $36 | block_attribute_null, $35 | block_attribute_null, $36 | block_attribute_null, $33 | block_attribute_null ;76
	.BYTE $33 | block_attribute_null, $35 | block_attribute_null, $35 | block_attribute_null, $35 | block_attribute_null ;77
	.BYTE $19 | block_attribute_wall, $34 | block_attribute_null, $31 | block_attribute_wall, $34 | block_attribute_null ;78
	.BYTE $32 | block_attribute_wall, $29 | block_attribute_wall, $30 | block_attribute_wall, $29 | block_attribute_wall ;79
	.BYTE $33 | block_attribute_null, $25 | block_attribute_wall, $33 | block_attribute_null, $26 | block_attribute_wall ;7A
	.BYTE $28 | block_attribute_wall, $28 | block_attribute_wall, $09 | block_attribute_wall, $09 | block_attribute_wall ;7B
	.BYTE $07 | block_attribute_wall, $0C | block_attribute_wall, $07 | block_attribute_wall, $0D | block_attribute_wall ;7C
	.BYTE $0E | block_attribute_wall, $0B | block_attribute_wall, $0F | block_attribute_wall, $0B | block_attribute_wall ;7D
	.BYTE $08 | block_attribute_null, $08 | block_attribute_null, $08 | block_attribute_null, $08 | block_attribute_null ;7E
	.BYTE $34 | block_attribute_null, $33 | block_attribute_null, $08 | block_attribute_null, $08 | block_attribute_null ;7F
	.BYTE $26 | block_attribute_wall, $28 | block_attribute_wall, $33 | block_attribute_null, $33 | block_attribute_null ;80
	.BYTE $31 | block_attribute_wall, $29 | block_attribute_wall, $32 | block_attribute_wall, $29 | block_attribute_wall ;81
	.BYTE $30 | block_attribute_wall, $29 | block_attribute_wall, $31 | block_attribute_wall, $29 | block_attribute_wall ;82
	.BYTE $29 | block_attribute_wall, $21 | block_attribute_wall, $29 | block_attribute_wall, $22 | block_attribute_wall ;83
	.BYTE $29 | block_attribute_wall, $20 | block_attribute_wall, $29 | block_attribute_wall, $21 | block_attribute_wall ;84
	.BYTE $28 | block_attribute_wall, $2E | block_attribute_wall, $34 | block_attribute_null, $33 | block_attribute_null ;85
	.BYTE $28 | block_attribute_wall, $28 | block_attribute_wall, $09 | block_attribute_wall, $0A | block_attribute_wall ;86
	.BYTE $33 | block_attribute_null, $33 | block_attribute_null, $08 | block_attribute_null, $08 | block_attribute_null ;87
	.BYTE $35 | block_attribute_null, $35 | block_attribute_null, $35 | block_attribute_null, $33 | block_attribute_null ;88
	.BYTE $36 | block_attribute_null, $35 | block_attribute_null, $36 | block_attribute_null, $35 | block_attribute_null ;89
	.BYTE $31 | block_attribute_wall, $2A | block_attribute_wall, $31 | block_attribute_wall, $29 | block_attribute_wall ;8A
	.BYTE $33 | block_attribute_null, $33 | block_attribute_null, $1E | block_attribute_wall, $34 | block_attribute_null ;8B
	.BYTE $33 | block_attribute_null, $33 | block_attribute_null, $33 | block_attribute_null, $1F | block_attribute_wall ;8C
	.BYTE $33 | block_attribute_null, $1A | block_attribute_wall, $33 | block_attribute_null, $33 | block_attribute_null ;8D
	.BYTE $33 | block_attribute_null, $33 | block_attribute_null, $2D | block_attribute_wall, $34 | block_attribute_null ;8E
	.BYTE $22 | block_attribute_wall, $2D | block_attribute_wall, $37 | block_attribute_wall, $21 | block_attribute_wall ;8F
	.BYTE $0A | block_attribute_wall, $12 | block_attribute_wall, $00 | block_attribute_null, $00 | block_attribute_null ;90
	.BYTE $33 | block_attribute_null, $33 | block_attribute_null, $33 | block_attribute_null, $25 | block_attribute_wall ;91
	.BYTE $33 | block_attribute_null, $31 | block_attribute_wall, $25 | block_attribute_wall, $32 | block_attribute_wall ;92
	.BYTE $26 | block_attribute_wall, $30 | block_attribute_wall, $33 | block_attribute_null, $31 | block_attribute_wall ;93
	.BYTE $33 | block_attribute_null, $26 | block_attribute_wall, $33 | block_attribute_null, $33 | block_attribute_null ;94
	.BYTE $00 | block_attribute_null, $00 | block_attribute_null, $00 | block_attribute_null, $00 | block_attribute_null ;95
	.BYTE $05 | block_attribute_3,    $05 | block_attribute_3,    $08 | block_attribute_wall, $10 | block_attribute_wall ;96
	.BYTE $05 | block_attribute_3,    $05 | block_attribute_3,    $16 | block_attribute_null, $17 | block_attribute_null ;97
	.BYTE $29 | block_attribute_null, $30 | block_attribute_null, $2A | block_attribute_null, $30 | block_attribute_null ;98
	.BYTE $2B | block_attribute_null, $30 | block_attribute_null, $2C | block_attribute_null, $30 | block_attribute_null ;99
	.BYTE $2D | block_attribute_null, $30 | block_attribute_null, $2E | block_attribute_null, $30 | block_attribute_null ;9A
	.BYTE $2F | block_attribute_null, $30 | block_attribute_null, $30 | block_attribute_null, $30 | block_attribute_null ;9B
	.BYTE $30 | block_attribute_null, $30 | block_attribute_null, $30 | block_attribute_null, $30 | block_attribute_null ;9C
	.BYTE $17 | block_attribute_null, $05 | block_attribute_3,    $17 | block_attribute_null, $0E | block_attribute_wall ;9D
	.BYTE $38 | block_attribute_null, $3A | block_attribute_null, $39 | block_attribute_null, $3B | block_attribute_null ;9E
	.BYTE $17 | block_attribute_null, $2E | block_attribute_2,    $17 | block_attribute_null, $2E | block_attribute_2    ;9F
	.BYTE $01 | block_attribute_null, $0D | block_attribute_null, $02 | block_attribute_null, $0E | block_attribute_null ;A0
	.BYTE $03 | block_attribute_null, $0F | block_attribute_null, $04 | block_attribute_null, $11 | block_attribute_null ;A1
	.BYTE $05 | block_attribute_null, $12 | block_attribute_null, $06 | block_attribute_null, $13 | block_attribute_null ;A2
	.BYTE $07 | block_attribute_null, $14 | block_attribute_null, $08 | block_attribute_null, $15 | block_attribute_null ;A3
	.BYTE $09 | block_attribute_null, $16 | block_attribute_null, $0A | block_attribute_null, $17 | block_attribute_null ;A4
	.BYTE $0B | block_attribute_null, $18 | block_attribute_null, $0C | block_attribute_null, $19 | block_attribute_null ;A5
	.BYTE $1A | block_attribute_null, $37 | block_attribute_null, $1B | block_attribute_null, $26 | block_attribute_null ;A6
	.BYTE $1C | block_attribute_null, $27 | block_attribute_null, $1D | block_attribute_null, $28 | block_attribute_null ;A7
	.BYTE $1E | block_attribute_null, $29 | block_attribute_null, $1F | block_attribute_null, $2A | block_attribute_null ;A8
	.BYTE $20 | block_attribute_null, $2B | block_attribute_null, $21 | block_attribute_null, $2C | block_attribute_null ;A9
	.BYTE $22 | block_attribute_null, $2D | block_attribute_null, $23 | block_attribute_null, $2E | block_attribute_null ;AA
	.BYTE $24 | block_attribute_null, $2F | block_attribute_null, $25 | block_attribute_null, $37 | block_attribute_null ;AB
	.BYTE $37 | block_attribute_null, $37 | block_attribute_null, $37 | block_attribute_null, $37 | block_attribute_null ;AC
	.BYTE $37 | block_attribute_null, $37 | block_attribute_null, $30 | block_attribute_null, $37 | block_attribute_null ;AD
	.BYTE $31 | block_attribute_null, $37 | block_attribute_null, $32 | block_attribute_null, $37 | block_attribute_null ;AE
	.BYTE $33 | block_attribute_null, $37 | block_attribute_null, $34 | block_attribute_null, $37 | block_attribute_null ;AF
	.BYTE $35 | block_attribute_null, $37 | block_attribute_null, $37 | block_attribute_null, $37 | block_attribute_null ;B0
	.BYTE $38 | block_attribute_wall, $3A | block_attribute_wall, $39 | block_attribute_wall, $3B | block_attribute_wall ;B1
	.BYTE $00 | block_attribute_wall, $00 | block_attribute_wall, $36 | block_attribute_null, $37 | block_attribute_null ;B2
	.BYTE $00 | block_attribute_wall, $00 | block_attribute_wall, $37 | block_attribute_null, $37 | block_attribute_null ;B3
	.BYTE $00 | block_attribute_wall, $38 | block_attribute_wall, $37 | block_attribute_null, $39 | block_attribute_wall ;B4
	.BYTE $37 | block_attribute_null, $38 | block_attribute_wall, $37 | block_attribute_null, $39 | block_attribute_wall ;B5
	.BYTE $3A | block_attribute_wall, $38 | block_attribute_wall, $3B | block_attribute_wall, $39 | block_attribute_wall ;B6
	.BYTE $36 | block_attribute_null, $37 | block_attribute_null, $00 | block_attribute_wall, $00 | block_attribute_wall ;B7
	.BYTE $37 | block_attribute_null, $37 | block_attribute_null, $00 | block_attribute_wall, $00 | block_attribute_wall ;B8
	.BYTE $37 | block_attribute_null, $37 | block_attribute_null, $37 | block_attribute_null, $3C | block_attribute_wall ;B9
	.BYTE $37 | block_attribute_null, $3D | block_attribute_wall, $00 | block_attribute_wall, $00 | block_attribute_wall ;BA
	.BYTE $37 | block_attribute_null, $38 | block_attribute_wall, $3E | block_attribute_wall, $39 | block_attribute_wall ;BB
	.BYTE $3F | block_attribute_wall, $38 | block_attribute_wall, $00 | block_attribute_wall, $39 | block_attribute_wall ;BC
	.BYTE $00 | block_attribute_null, $00 | block_attribute_null, $00 | block_attribute_null, $00 | block_attribute_null ;BD
	.BYTE $00 | block_attribute_null, $00 | block_attribute_null, $00 | block_attribute_null, $00 | block_attribute_null ;BE
	.BYTE $00 | block_attribute_null, $00 | block_attribute_null, $00 | block_attribute_null, $00 | block_attribute_null ;BF
	.BYTE $1E | block_attribute_wall, $1E | block_attribute_wall, $2C | block_attribute_wall, $2A | block_attribute_wall ;C0
	.BYTE $2C | block_attribute_wall, $2B | block_attribute_wall, $24 | block_attribute_wall, $2C | block_attribute_wall ;C1
	.BYTE $24 | block_attribute_wall, $2C | block_attribute_wall, $24 | block_attribute_wall, $2C | block_attribute_wall ;C2
	.BYTE $14 | block_attribute_wall, $14 | block_attribute_wall, $14 | block_attribute_wall, $14 | block_attribute_wall ;C3
	.BYTE $00 | block_attribute_null, $00 | block_attribute_null, $00 | block_attribute_null, $00 | block_attribute_null ;C4
	.BYTE $24 | block_attribute_wall, $2C | block_attribute_wall, $1E | block_attribute_wall, $1E | block_attribute_wall ;C5
	.BYTE $24 | block_attribute_wall, $2C | block_attribute_wall, $2C | block_attribute_wall, $2A | block_attribute_wall ;C6
	.BYTE $2C | block_attribute_wall, $2B | block_attribute_wall, $1E | block_attribute_wall, $1E | block_attribute_wall ;C7
	.BYTE $1E | block_attribute_wall, $1E | block_attribute_wall, $20 | block_attribute_wall, $00 | block_attribute_null ;C8
	.BYTE $21 | block_attribute_wall, $00 | block_attribute_null, $30 | block_attribute_null, $38 | block_attribute_null ;C9
	.BYTE $31 | block_attribute_null, $39 | block_attribute_null, $32 | block_attribute_null, $3A | block_attribute_null ;CA
	.BYTE $33 | block_attribute_null, $3B | block_attribute_null, $1A | block_attribute_null, $1C | block_attribute_null ;CB
	.BYTE $1B | block_attribute_null, $1D | block_attribute_null, $30 | block_attribute_null, $38 | block_attribute_null ;CC
	.BYTE $25 | block_attribute_null, $2D | block_attribute_null, $1E | block_attribute_wall, $1E | block_attribute_wall ;CD
	.BYTE $33 | block_attribute_null, $3B | block_attribute_null, $20 | block_attribute_wall, $00 | block_attribute_null ;CE
	.BYTE $21 | block_attribute_wall, $00 | block_attribute_null, $1E | block_attribute_wall, $1E | block_attribute_wall ;CF
	.BYTE $1E | block_attribute_wall, $1E | block_attribute_wall, $00 | block_attribute_null, $28 | block_attribute_wall ;D0
	.BYTE $00 | block_attribute_null, $29 | block_attribute_wall, $34 | block_attribute_null, $3C | block_attribute_null ;D1
	.BYTE $35 | block_attribute_null, $3D | block_attribute_null, $36 | block_attribute_null, $3E | block_attribute_null ;D2
	.BYTE $37 | block_attribute_null, $3F | block_attribute_null, $1A | block_attribute_null, $1C | block_attribute_null ;D3
	.BYTE $1B | block_attribute_null, $1D | block_attribute_null, $34 | block_attribute_null, $3C | block_attribute_null ;D4
	.BYTE $2D | block_attribute_null, $2D | block_attribute_null, $1E | block_attribute_wall, $1E | block_attribute_wall ;D5
	.BYTE $37 | block_attribute_null, $3F | block_attribute_null, $00 | block_attribute_null, $28 | block_attribute_wall ;D6
	.BYTE $00 | block_attribute_null, $29 | block_attribute_wall, $1E | block_attribute_wall, $1E | block_attribute_wall ;D7
	.BYTE $25 | block_attribute_null, $2D | block_attribute_null, $25 | block_attribute_null, $2D | block_attribute_null ;D8
	.BYTE $21 | block_attribute_wall, $00 | block_attribute_null, $26 | block_attribute_null, $2E | block_attribute_null ;D9
	.BYTE $27 | block_attribute_null, $2F | block_attribute_null, $1F | block_attribute_null, $19 | block_attribute_wall ;DA
	.BYTE $1F | block_attribute_null, $1F | block_attribute_null, $1A | block_attribute_null, $1C | block_attribute_null ;DB
	.BYTE $1B | block_attribute_null, $1D | block_attribute_null, $1F | block_attribute_null, $1F | block_attribute_null ;DC
	.BYTE $1F | block_attribute_null, $19 | block_attribute_wall, $26 | block_attribute_null, $2E | block_attribute_null ;DD
	.BYTE $27 | block_attribute_null, $2F | block_attribute_null, $20 | block_attribute_wall, $00 | block_attribute_null ;DE
	.BYTE $00 | block_attribute_null, $00 | block_attribute_null, $00 | block_attribute_null, $00 | block_attribute_null ;DF
	.BYTE $2D | block_attribute_null, $2D | block_attribute_null, $2D | block_attribute_null, $2D | block_attribute_null ;E0
	.BYTE $00 | block_attribute_null, $29 | block_attribute_wall, $30 | block_attribute_null, $38 | block_attribute_null ;E1
	.BYTE $1E | block_attribute_wall, $1E | block_attribute_wall, $2D | block_attribute_null, $0D | block_attribute_null ;E2
	.BYTE $2D | block_attribute_null, $0E | block_attribute_null, $2D | block_attribute_null, $2D | block_attribute_null ;E3
	.BYTE $1E | block_attribute_wall, $1E | block_attribute_wall, $00 | block_attribute_null, $00 | block_attribute_null ;E4
	.BYTE $00 | block_attribute_null, $00 | block_attribute_null, $2D | block_attribute_null, $2D | block_attribute_null ;E5
	.BYTE $33 | block_attribute_null, $3B | block_attribute_null, $00 | block_attribute_null, $28 | block_attribute_wall ;E6
	.BYTE $1E | block_attribute_wall, $1E | block_attribute_wall, $28 | block_attribute_wall, $2A | block_attribute_wall ;E7
	.BYTE $29 | block_attribute_wall, $2B | block_attribute_wall, $24 | block_attribute_wall, $2C | block_attribute_wall ;E8
	.BYTE $21 | block_attribute_wall, $00 | block_attribute_null, $19 | block_attribute_wall, $3C | block_attribute_null ;E9
	.BYTE $1E | block_attribute_wall, $1E | block_attribute_wall, $24 | block_attribute_wall, $2C | block_attribute_wall ;EA
	.BYTE $22 | block_attribute_wall, $00 | block_attribute_null, $23 | block_attribute_wall, $00 | block_attribute_null ;EB
	.BYTE $33 | block_attribute_null, $3B | block_attribute_null, $20 | block_attribute_wall, $00 | block_attribute_null ;EC
	.BYTE $21 | block_attribute_wall, $00 | block_attribute_null, $30 | block_attribute_null, $38 | block_attribute_null ;ED
	.BYTE $19 | block_attribute_wall, $3F | block_attribute_null, $20 | block_attribute_wall, $00 | block_attribute_null ;EE
	.BYTE $1E | block_attribute_wall, $1E | block_attribute_wall, $25 | block_attribute_null, $2D | block_attribute_null ;EF
	.BYTE $1E | block_attribute_wall, $1E | block_attribute_wall, $2D | block_attribute_null, $2D | block_attribute_null ;F0
	.BYTE $00 | block_attribute_null, $29 | block_attribute_wall, $1F | block_attribute_null, $24 | block_attribute_wall ;F1
	.BYTE $1F | block_attribute_null, $24 | block_attribute_wall, $1F | block_attribute_null, $24 | block_attribute_wall ;F2
	.BYTE $00 | block_attribute_null, $28 | block_attribute_wall, $00 | block_attribute_null, $29 | block_attribute_wall ;F3
	.BYTE $37 | block_attribute_null, $3F | block_attribute_null, $00 | block_attribute_null, $28 | block_attribute_wall ;F4
	.BYTE $00 | block_attribute_null, $29 | block_attribute_wall, $34 | block_attribute_null, $3C | block_attribute_null ;F5
	.BYTE $1F | block_attribute_null, $24 | block_attribute_wall, $00 | block_attribute_null, $28 | block_attribute_wall ;F6
	.BYTE $2B | block_attribute_null, $2B | block_attribute_null, $2D | block_attribute_null, $2D | block_attribute_null ;F7
	.BYTE $1E | block_attribute_wall, $1E | block_attribute_wall, $2A | block_attribute_wall, $24 | block_attribute_wall ;F8
	.BYTE $2B | block_attribute_wall, $24 | block_attribute_wall, $2C | block_attribute_wall, $24 | block_attribute_wall ;F9
	.BYTE $2C | block_attribute_wall, $24 | block_attribute_wall, $2C | block_attribute_wall, $24 | block_attribute_wall ;FA
	.BYTE $2A | block_attribute_wall, $24 | block_attribute_wall, $2B | block_attribute_wall, $24 | block_attribute_wall ;FB
	.BYTE $00 | block_attribute_null, $00 | block_attribute_null, $00 | block_attribute_null, $00 | block_attribute_null ;FC
	.BYTE $00 | block_attribute_null, $00 | block_attribute_null, $00 | block_attribute_null, $00 | block_attribute_null ;FD
	.BYTE $2C | block_attribute_wall, $24 | block_attribute_wall, $2A | block_attribute_wall, $24 | block_attribute_wall ;FE
	.BYTE $2B | block_attribute_wall, $24 | block_attribute_wall, $1E | block_attribute_wall, $1E | block_attribute_wall ;FF