;32x32 blocksets with 16x16 blocksets | block attribute.
;block_attribute 2 and 3 setting see home/blocksets.asm. 
	      ;top left,                  bottom left,                top right,                  bottom right
	.BYTE $00 | block_attribute_null, $00 | block_attribute_null, $00 | block_attribute_null, $00 | block_attribute_null ;00
	.BYTE $01 | block_attribute_null, $01 | block_attribute_null, $01 | block_attribute_null, $01 | block_attribute_null ;01
	.BYTE $01 | block_attribute_null, $01 | block_attribute_null, $01 | block_attribute_null, $01 | block_attribute_null ;02
	.BYTE $01 | block_attribute_null, $01 | block_attribute_null, $01 | block_attribute_null, $01 | block_attribute_null ;03
	.BYTE $01 | block_attribute_null, $01 | block_attribute_null, $01 | block_attribute_null, $01 | block_attribute_null ;04
	.BYTE $3A | block_attribute_null, $3A | block_attribute_null, $39 | block_attribute_null, $39 | block_attribute_null ;05
	.BYTE $38 | block_attribute_null, $38 | block_attribute_null, $39 | block_attribute_null, $39 | block_attribute_null ;06
	.BYTE $01 | block_attribute_null, $18 | block_attribute_wall, $01 | block_attribute_null, $3F | block_attribute_wall ;07
	.BYTE $06 | block_attribute_null, $00 | block_attribute_null, $07 | block_attribute_null, $00 | block_attribute_null ;08
	.BYTE $1E | block_attribute_wall, $01 | block_attribute_null, $1E | block_attribute_wall, $01 | block_attribute_null ;09
	.BYTE $01 | block_attribute_null, $1E | block_attribute_wall, $01 | block_attribute_null, $1E | block_attribute_wall ;0A
	.BYTE $1F | block_attribute_wall, $01 | block_attribute_null, $01 | block_attribute_null, $01 | block_attribute_null ;0B
	.BYTE $01 | block_attribute_null, $01 | block_attribute_null, $01 | block_attribute_null, $05 | block_attribute_wall ;0C
	.BYTE $05 | block_attribute_wall, $01 | block_attribute_null, $1E | block_attribute_wall, $01 | block_attribute_null ;0D
	.BYTE $1E | block_attribute_wall, $01 | block_attribute_null, $1F | block_attribute_wall, $01 | block_attribute_null ;0E
	.BYTE $01 | block_attribute_null, $05 | block_attribute_wall, $01 | block_attribute_null, $1E | block_attribute_wall ;0F
	.BYTE $08 | block_attribute_null, $00 | block_attribute_null, $08 | block_attribute_null, $00 | block_attribute_null ;10
	.BYTE $38 | block_attribute_wall, $26 | block_attribute_wall, $21 | block_attribute_wall, $3B | block_attribute_wall ;11
	.BYTE $21 | block_attribute_wall, $27 | block_attribute_wall, $22 | block_attribute_wall, $38 | block_attribute_wall ;12
	.BYTE $2A | block_attribute_wall, $23 | block_attribute_wall, $27 | block_attribute_wall, $39 | block_attribute_wall ;13
	.BYTE $26 | block_attribute_wall, $39 | block_attribute_wall, $38 | block_attribute_wall, $26 | block_attribute_wall ;14
	.BYTE $1A | block_attribute_wall, $24 | block_attribute_wall, $1B | block_attribute_wall, $25 | block_attribute_wall ;15
	.BYTE $02 | block_attribute_null, $03 | block_attribute_null, $02 | block_attribute_null, $03 | block_attribute_null ;16
	.BYTE $38 | block_attribute_wall, $2B | block_attribute_wall, $1D | block_attribute_null, $1D | block_attribute_null ;17
	.BYTE $23 | block_attribute_wall, $26 | block_attribute_wall, $19 | block_attribute_wall, $3B | block_attribute_wall ;18
	.BYTE $22 | block_attribute_wall, $38 | block_attribute_wall, $3A | block_attribute_wall, $39 | block_attribute_wall ;19
	.BYTE $19 | block_attribute_wall, $27 | block_attribute_wall, $22 | block_attribute_wall, $38 | block_attribute_wall ;1A
	.BYTE $3C | block_attribute_wall, $22 | block_attribute_wall, $23 | block_attribute_wall, $26 | block_attribute_wall ;1B
	.BYTE $21 | block_attribute_wall, $3B | block_attribute_wall, $22 | block_attribute_wall, $2B | block_attribute_wall ;1C
	.BYTE $26 | block_attribute_wall, $2A | block_attribute_wall, $38 | block_attribute_wall, $3B | block_attribute_wall ;1D
	.BYTE $39 | block_attribute_wall, $3B | block_attribute_wall, $27 | block_attribute_wall, $3B | block_attribute_wall ;1E
	.BYTE $26 | block_attribute_wall, $2B | block_attribute_wall, $38 | block_attribute_wall, $2A | block_attribute_wall ;1F
	.BYTE $38 | block_attribute_wall, $26 | block_attribute_wall, $21 | block_attribute_wall, $2B | block_attribute_wall ;20
	.BYTE $39 | block_attribute_wall, $27 | block_attribute_wall, $23 | block_attribute_wall, $38 | block_attribute_wall ;21
	.BYTE $2A | block_attribute_wall, $3A | block_attribute_wall, $2B | block_attribute_wall, $23 | block_attribute_wall ;22
	.BYTE $26 | block_attribute_wall, $21 | block_attribute_wall, $38 | block_attribute_wall, $21 | block_attribute_wall ;23
	.BYTE $21 | block_attribute_wall, $2A | block_attribute_wall, $21 | block_attribute_wall, $3B | block_attribute_wall ;24
	.BYTE $22 | block_attribute_wall, $39 | block_attribute_wall, $3A | block_attribute_wall, $38 | block_attribute_wall ;25
	.BYTE $21 | block_attribute_wall, $21 | block_attribute_wall, $2A | block_attribute_wall, $22 | block_attribute_wall ;26
	.BYTE $2A | block_attribute_wall, $22 | block_attribute_wall, $38 | block_attribute_wall, $26 | block_attribute_wall ;27
	.BYTE $1E | block_attribute_wall, $2A | block_attribute_wall, $1E | block_attribute_wall, $38 | block_attribute_wall ;28
	.BYTE $2A | block_attribute_wall, $1E | block_attribute_wall, $38 | block_attribute_wall, $1E | block_attribute_wall ;29
	.BYTE $18 | block_attribute_wall, $01 | block_attribute_null, $3C | block_attribute_wall, $01 | block_attribute_null ;2A
	.BYTE $3C | block_attribute_wall, $01 | block_attribute_null, $3C | block_attribute_wall, $01 | block_attribute_null ;2B
	.BYTE $3F | block_attribute_wall, $01 | block_attribute_null, $01 | block_attribute_null, $01 | block_attribute_null ;2C
	.BYTE $27 | block_attribute_wall, $2A | block_attribute_wall, $3C | block_attribute_wall, $23 | block_attribute_wall ;2D
	.BYTE $01 | block_attribute_null, $01 | block_attribute_null, $21 | block_attribute_wall, $2A | block_attribute_wall ;2E
	.BYTE $3C | block_attribute_wall, $3C | block_attribute_wall, $2B | block_attribute_wall, $3C | block_attribute_wall ;2F
	.BYTE $02 | block_attribute_null, $04 | block_attribute_null, $02 | block_attribute_null, $05 | block_attribute_null ;30
	.BYTE $01 | block_attribute_null, $1E | block_attribute_wall, $2A | block_attribute_wall, $1E | block_attribute_wall ;31
	.BYTE $01 | block_attribute_null, $01 | block_attribute_null, $01 | block_attribute_null, $18 | block_attribute_wall ;32
	.BYTE $01 | block_attribute_null, $3F | block_attribute_wall, $01 | block_attribute_null, $01 | block_attribute_null ;33
	.BYTE $2A | block_attribute_wall, $01 | block_attribute_null, $2B | block_attribute_wall, $01 | block_attribute_null ;34
	.BYTE $3A | block_attribute_null, $00 | block_attribute_null, $39 | block_attribute_null, $00 | block_attribute_null ;35
	.BYTE $3B | block_attribute_wall, $01 | block_attribute_null, $2B | block_attribute_wall, $01 | block_attribute_null ;36
	.BYTE $2A | block_attribute_wall, $01 | block_attribute_null, $3C | block_attribute_wall, $01 | block_attribute_null ;37
	.BYTE $01 | block_attribute_null, $22 | block_attribute_wall, $01 | block_attribute_null, $3A | block_attribute_wall ;38
	.BYTE $01 | block_attribute_null, $3A | block_attribute_wall, $01 | block_attribute_null, $23 | block_attribute_wall ;39
	.BYTE $01 | block_attribute_null, $22 | block_attribute_wall, $01 | block_attribute_null, $23 | block_attribute_wall ;3A
	.BYTE $01 | block_attribute_null, $01 | block_attribute_null, $21 | block_attribute_wall, $39 | block_attribute_wall ;3B
	.BYTE $2A | block_attribute_wall, $01 | block_attribute_null, $38 | block_attribute_wall, $21 | block_attribute_wall ;3C
	.BYTE $23 | block_attribute_wall, $38 | block_attribute_wall, $1D | block_attribute_null, $1D | block_attribute_null ;3D
	.BYTE $21 | block_attribute_wall, $21 | block_attribute_wall, $01 | block_attribute_null, $01 | block_attribute_null ;3E
	.BYTE $1D | block_attribute_null, $1D | block_attribute_null, $08 | block_attribute_null, $08 | block_attribute_null ;3F
	.BYTE $17 | block_attribute_null, $09 | block_attribute_null, $3E | block_attribute_null, $0A | block_attribute_null ;40
	.BYTE $03 | block_attribute_2,    $03 | block_attribute_2,    $3F | block_attribute_wall, $01 | block_attribute_null ;41
	.BYTE $03 | block_attribute_2,    $01 | block_attribute_null, $18 | block_attribute_wall, $01 | block_attribute_null ;42
	.BYTE $3C | block_attribute_wall, $01 | block_attribute_null, $03 | block_attribute_2,    $03 | block_attribute_2    ;43
	.BYTE $17 | block_attribute_null, $0B | block_attribute_null, $16 | block_attribute_null, $00 | block_attribute_null ;44
	.BYTE $15 | block_attribute_null, $15 | block_attribute_null, $15 | block_attribute_null, $16 | block_attribute_null ;45
	.BYTE $01 | block_attribute_null, $03 | block_attribute_2,    $01 | block_attribute_null, $3C | block_attribute_wall ;46
	.BYTE $00 | block_attribute_null, $00 | block_attribute_null, $00 | block_attribute_null, $00 | block_attribute_null ;47
	.BYTE $16 | block_attribute_null, $3E | block_attribute_null, $17 | block_attribute_null, $09 | block_attribute_null ;48
	.BYTE $01 | block_attribute_null, $18 | block_attribute_wall, $01 | block_attribute_null, $03 | block_attribute_2    ;49
	.BYTE $3E | block_attribute_null, $0A | block_attribute_null, $17 | block_attribute_null, $0B | block_attribute_null ;4A
	.BYTE $03 | block_attribute_2,    $03 | block_attribute_2,    $39 | block_attribute_wall, $21 | block_attribute_wall ;4B
	.BYTE $03 | block_attribute_2,    $01 | block_attribute_null, $2A | block_attribute_wall, $22 | block_attribute_wall ;4C
	.BYTE $03 | block_attribute_2,    $03 | block_attribute_2,    $22 | block_attribute_wall, $39 | block_attribute_wall ;4D
	.BYTE $0A | block_attribute_null, $3E | block_attribute_null, $17 | block_attribute_null, $00 | block_attribute_null ;4E
	.BYTE $03 | block_attribute_2,    $03 | block_attribute_2,    $2B | block_attribute_wall, $01 | block_attribute_null ;4F
	.BYTE $01 | block_attribute_null, $01 | block_attribute_null, $03 | block_attribute_2,    $03 | block_attribute_2    ;50
	.BYTE $01 | block_attribute_null, $01 | block_attribute_null, $03 | block_attribute_2,    $01 | block_attribute_null ;51
	.BYTE $03 | block_attribute_2,    $03 | block_attribute_2,    $01 | block_attribute_null, $01 | block_attribute_null ;52
	.BYTE $03 | block_attribute_2,    $01 | block_attribute_null, $01 | block_attribute_null, $01 | block_attribute_null ;53
	.BYTE $2A | block_attribute_wall, $01 | block_attribute_null, $03 | block_attribute_2,    $03 | block_attribute_2    ;54
	.BYTE $16 | block_attribute_null, $15 | block_attribute_null, $09 | block_attribute_null, $16 | block_attribute_null ;55
	.BYTE $01 | block_attribute_null, $01 | block_attribute_null, $34 | block_attribute_null, $33 | block_attribute_null ;56
	.BYTE $23 | block_attribute_wall, $38 | block_attribute_wall, $03 | block_attribute_2,    $03 | block_attribute_2    ;57
	.BYTE $22 | block_attribute_wall, $21 | block_attribute_wall, $03 | block_attribute_2,    $03 | block_attribute_2    ;58
	.BYTE $19 | block_attribute_wall, $29 | block_attribute_wall, $03 | block_attribute_2,    $03 | block_attribute_2    ;59
	.BYTE $03 | block_attribute_2,    $03 | block_attribute_2,    $39 | block_attribute_wall, $39 | block_attribute_wall ;5A
	.BYTE $03 | block_attribute_2,    $03 | block_attribute_2,    $23 | block_attribute_wall, $3B | block_attribute_wall ;5B
	.BYTE $03 | block_attribute_2,    $03 | block_attribute_2,    $3C | block_attribute_wall, $01 | block_attribute_null ;5C
	.BYTE $22 | block_attribute_wall, $21 | block_attribute_wall, $3C | block_attribute_wall, $01 | block_attribute_null ;5D
	.BYTE $01 | block_attribute_null, $03 | block_attribute_2,    $39 | block_attribute_wall, $21 | block_attribute_wall ;5E
	.BYTE $01 | block_attribute_null, $01 | block_attribute_null, $01 | block_attribute_null, $30 | block_attribute_null ;5F
	.BYTE $30 | block_attribute_null, $34 | block_attribute_null, $31 | block_attribute_null, $01 | block_attribute_null ;60
	.BYTE $31 | block_attribute_null, $01 | block_attribute_null, $31 | block_attribute_null, $01 | block_attribute_null ;61
	.BYTE $31 | block_attribute_null, $01 | block_attribute_null, $32 | block_attribute_null, $34 | block_attribute_null ;62
	.BYTE $35 | block_attribute_null, $01 | block_attribute_null, $01 | block_attribute_null, $01 | block_attribute_null ;63
	.BYTE $35 | block_attribute_null, $01 | block_attribute_null, $30 | block_attribute_null, $34 | block_attribute_null ;64
	.BYTE $01 | block_attribute_null, $31 | block_attribute_null, $01 | block_attribute_null, $31 | block_attribute_null ;65
	.BYTE $30 | block_attribute_null, $35 | block_attribute_null, $31 | block_attribute_null, $30 | block_attribute_null ;66
	.BYTE $31 | block_attribute_null, $32 | block_attribute_null, $31 | block_attribute_null, $01 | block_attribute_null ;67
	.BYTE $34 | block_attribute_null, $34 | block_attribute_null, $01 | block_attribute_null, $01 | block_attribute_null ;68
	.BYTE $31 | block_attribute_null, $01 | block_attribute_null, $2D | block_attribute_null, $2C | block_attribute_null ;69
	.BYTE $01 | block_attribute_null, $01 | block_attribute_null, $34 | block_attribute_null, $34 | block_attribute_null ;6A
	.BYTE $31 | block_attribute_null, $30 | block_attribute_null, $31 | block_attribute_null, $31 | block_attribute_null ;6B
	.BYTE $31 | block_attribute_null, $32 | block_attribute_null, $32 | block_attribute_null, $34 | block_attribute_null ;6C
	.BYTE $34 | block_attribute_null, $35 | block_attribute_null, $34 | block_attribute_null, $34 | block_attribute_null ;6D
	.BYTE $33 | block_attribute_null, $31 | block_attribute_null, $31 | block_attribute_null, $31 | block_attribute_null ;6E
	.BYTE $31 | block_attribute_null, $31 | block_attribute_null, $31 | block_attribute_null, $31 | block_attribute_null ;6F
	.BYTE $33 | block_attribute_null, $01 | block_attribute_null, $31 | block_attribute_null, $01 | block_attribute_null ;70
	.BYTE $2D | block_attribute_null, $2C | block_attribute_null, $31 | block_attribute_null, $01 | block_attribute_null ;71
	.BYTE $31 | block_attribute_null, $01 | block_attribute_null, $35 | block_attribute_null, $01 | block_attribute_null ;72
	.BYTE $01 | block_attribute_null, $30 | block_attribute_null, $33 | block_attribute_null, $31 | block_attribute_null ;73
	.BYTE $34 | block_attribute_null, $34 | block_attribute_null, $34 | block_attribute_null, $34 | block_attribute_null ;74
	.BYTE $31 | block_attribute_null, $31 | block_attribute_null, $35 | block_attribute_null, $31 | block_attribute_null ;75
	.BYTE $35 | block_attribute_null, $31 | block_attribute_null, $01 | block_attribute_null, $31 | block_attribute_null ;76
	.BYTE $34 | block_attribute_null, $35 | block_attribute_null, $33 | block_attribute_null, $30 | block_attribute_null ;77
	.BYTE $30 | block_attribute_null, $34 | block_attribute_null, $31 | block_attribute_null, $30 | block_attribute_null ;78
	.BYTE $32 | block_attribute_null, $35 | block_attribute_null, $34 | block_attribute_null, $34 | block_attribute_null ;79
	.BYTE $33 | block_attribute_null, $30 | block_attribute_null, $32 | block_attribute_null, $35 | block_attribute_null ;7A
	.BYTE $1D | block_attribute_null, $01 | block_attribute_null, $09 | block_attribute_wall, $09 | block_attribute_wall ;7B
	.BYTE $07 | block_attribute_wall, $0C | block_attribute_wall, $07 | block_attribute_wall, $0D | block_attribute_wall ;7C
	.BYTE $0E | block_attribute_wall, $0B | block_attribute_wall, $0F | block_attribute_wall, $0B | block_attribute_wall ;7D
	.BYTE $1D | block_attribute_null, $01 | block_attribute_null, $09 | block_attribute_wall, $0A | block_attribute_wall ;7E
	.BYTE $0A | block_attribute_null, $16 | block_attribute_null, $0B | block_attribute_null, $3E | block_attribute_null ;7F
	.BYTE $09 | block_attribute_null, $16 | block_attribute_null, $0A | block_attribute_null, $3E | block_attribute_null ;80
	.BYTE $17 | block_attribute_null, $00 | block_attribute_null, $17 | block_attribute_null, $0E | block_attribute_null ;81
	.BYTE $0C | block_attribute_null, $0D | block_attribute_null, $0E | block_attribute_null, $0F | block_attribute_null ;82
	.BYTE $01 | block_attribute_null, $01 | block_attribute_null, $19 | block_attribute_wall, $29 | block_attribute_wall ;83
	.BYTE $19 | block_attribute_wall, $29 | block_attribute_wall, $01 | block_attribute_null, $01 | block_attribute_null ;84
	.BYTE $0C | block_attribute_null, $0D | block_attribute_null, $3F | block_attribute_null, $0C | block_attribute_null ;85
	.BYTE $09 | block_attribute_null, $16 | block_attribute_null, $0A | block_attribute_null, $16 | block_attribute_null ;86
	.BYTE $01 | block_attribute_null, $22 | block_attribute_wall, $01 | block_attribute_null, $3A | block_attribute_wall ;87
	.BYTE $03 | block_attribute_2,    $03 | block_attribute_2,    $21 | block_attribute_wall, $2B | block_attribute_wall ;88
	.BYTE $03 | block_attribute_2,    $03 | block_attribute_2,    $23 | block_attribute_wall, $38 | block_attribute_wall ;89
	.BYTE $3F | block_attribute_null, $0C | block_attribute_null, $0E | block_attribute_null, $0F | block_attribute_null ;8A
	.BYTE $3F | block_attribute_null, $0C | block_attribute_null, $0F | block_attribute_null, $0F | block_attribute_null ;8B
	.BYTE $01 | block_attribute_null, $03 | block_attribute_2,    $01 | block_attribute_null, $22 | block_attribute_wall ;8C
	.BYTE $1D | block_attribute_null, $23 | block_attribute_wall, $1D | block_attribute_null, $01 | block_attribute_null ;8D
	.BYTE $01 | block_attribute_null, $3A | block_attribute_wall, $01 | block_attribute_null, $23 | block_attribute_wall ;8E
	.BYTE $03 | block_attribute_2,    $3C | block_attribute_wall, $01 | block_attribute_null, $3C | block_attribute_wall ;8F
	.BYTE $01 | block_attribute_null, $01 | block_attribute_null, $01 | block_attribute_null, $18 | block_attribute_wall ;90
	.BYTE $0D | block_attribute_null, $10 | block_attribute_null, $0F | block_attribute_null, $11 | block_attribute_null ;91
	.BYTE $3E | block_attribute_null, $15 | block_attribute_null, $15 | block_attribute_null, $00 | block_attribute_null ;92
	.BYTE $00 | block_attribute_null, $15 | block_attribute_null, $0C | block_attribute_null, $16 | block_attribute_null ;93
	.BYTE $3A | block_attribute_wall, $21 | block_attribute_wall, $23 | block_attribute_wall, $21 | block_attribute_wall ;94
	.BYTE $22 | block_attribute_wall, $2B | block_attribute_wall, $3C | block_attribute_wall, $01 | block_attribute_null ;95
	.BYTE $01 | block_attribute_null, $3C | block_attribute_wall, $21 | block_attribute_wall, $2B | block_attribute_wall ;96
	.BYTE $01 | block_attribute_null, $01 | block_attribute_null, $01 | block_attribute_null, $22 | block_attribute_wall ;97
	.BYTE $21 | block_attribute_wall, $2B | block_attribute_wall, $01 | block_attribute_null, $01 | block_attribute_null ;98
	.BYTE $01 | block_attribute_null, $22 | block_attribute_wall, $01 | block_attribute_null, $3C | block_attribute_wall ;99
	.BYTE $01 | block_attribute_null, $3C | block_attribute_wall, $01 | block_attribute_null, $23 | block_attribute_wall ;9A
	.BYTE $01 | block_attribute_null, $01 | block_attribute_null, $21 | block_attribute_wall, $21 | block_attribute_wall ;9B
	.BYTE $3C | block_attribute_wall, $01 | block_attribute_null, $3B | block_attribute_wall, $01 | block_attribute_null ;9C
	.BYTE $38 | block_attribute_wall, $2A | block_attribute_wall, $01 | block_attribute_null, $3C | block_attribute_wall ;9D
	.BYTE $39 | block_attribute_wall, $2B | block_attribute_wall, $3C | block_attribute_wall, $01 | block_attribute_null ;9E
	.BYTE $2B | block_attribute_wall, $01 | block_attribute_null, $01 | block_attribute_null, $01 | block_attribute_null ;9F
	.BYTE $0D | block_attribute_null, $17 | block_attribute_null, $0F | block_attribute_null, $3E | block_attribute_null ;A0
	.BYTE $3A | block_attribute_wall, $39 | block_attribute_wall, $3C | block_attribute_wall, $3C | block_attribute_wall ;A1
	.BYTE $3C | block_attribute_wall, $3C | block_attribute_wall, $3A | block_attribute_wall, $3B | block_attribute_wall ;A2
	.BYTE $38 | block_attribute_wall, $21 | block_attribute_wall, $1D | block_attribute_null, $1D | block_attribute_null ;A3
	.BYTE $3C | block_attribute_wall, $3C | block_attribute_wall, $3C | block_attribute_wall, $3C | block_attribute_wall ;A4
	.BYTE $01 | block_attribute_null, $01 | block_attribute_null, $21 | block_attribute_wall, $2A | block_attribute_wall ;A5
	.BYTE $01 | block_attribute_null, $1D | block_attribute_null, $22 | block_attribute_wall, $39 | block_attribute_wall ;A6
	.BYTE $1D | block_attribute_null, $1D | block_attribute_null, $39 | block_attribute_wall, $2A | block_attribute_wall ;A7
	.BYTE $01 | block_attribute_null, $3E | block_attribute_null, $01 | block_attribute_null, $01 | block_attribute_null ;A8
	.BYTE $01 | block_attribute_null, $01 | block_attribute_null, $01 | block_attribute_null, $28 | block_attribute_null ;A9
	.BYTE $01 | block_attribute_null, $3E | block_attribute_null, $01 | block_attribute_null, $28 | block_attribute_null ;AA
	.BYTE $28 | block_attribute_null, $01 | block_attribute_null, $3E | block_attribute_null, $01 | block_attribute_null ;AB
	.BYTE $20 | block_attribute_null, $01 | block_attribute_null, $01 | block_attribute_null, $20 | block_attribute_null ;AC
	.BYTE $20 | block_attribute_null, $28 | block_attribute_null, $01 | block_attribute_null, $01 | block_attribute_null ;AD
	.BYTE $3E | block_attribute_null, $01 | block_attribute_null, $28 | block_attribute_null, $01 | block_attribute_null ;AE
	.BYTE $01 | block_attribute_null, $28 | block_attribute_null, $28 | block_attribute_null, $01 | block_attribute_null ;AF
	.BYTE $01 | block_attribute_null, $01 | block_attribute_null, $3E | block_attribute_null, $01 | block_attribute_null ;B0
	.BYTE $28 | block_attribute_null, $01 | block_attribute_null, $01 | block_attribute_null, $01 | block_attribute_null ;B1
	.BYTE $20 | block_attribute_null, $01 | block_attribute_null, $3D | block_attribute_null, $01 | block_attribute_null ;B2
	.BYTE $01 | block_attribute_null, $3D | block_attribute_null, $01 | block_attribute_null, $20 | block_attribute_null ;B3
	.BYTE $17 | block_attribute_null, $10 | block_attribute_null, $3E | block_attribute_null, $11 | block_attribute_null ;B4
	.BYTE $12 | block_attribute_null, $13 | block_attribute_null, $13 | block_attribute_null, $01 | block_attribute_null ;B5
	.BYTE $10 | block_attribute_null, $12 | block_attribute_null, $11 | block_attribute_null, $14 | block_attribute_null ;B6
	.BYTE $00 | block_attribute_null, $15 | block_attribute_null, $15 | block_attribute_null, $16 | block_attribute_null ;B7
	.BYTE $10 | block_attribute_null, $13 | block_attribute_null, $11 | block_attribute_null, $14 | block_attribute_null ;B8
	.BYTE $12 | block_attribute_null, $12 | block_attribute_null, $14 | block_attribute_null, $13 | block_attribute_null ;B9
	.BYTE $01 | block_attribute_null, $00 | block_attribute_null, $01 | block_attribute_null, $00 | block_attribute_null ;BA
	.BYTE $12 | block_attribute_null, $00 | block_attribute_null, $14 | block_attribute_null, $00 | block_attribute_null ;BB
	.BYTE $3F | block_attribute_null, $00 | block_attribute_null, $3F | block_attribute_null, $00 | block_attribute_null ;BC
	.BYTE $01 | block_attribute_null, $00 | block_attribute_null, $14 | block_attribute_null, $00 | block_attribute_null ;BD
	.BYTE $12 | block_attribute_null, $00 | block_attribute_null, $01 | block_attribute_null, $00 | block_attribute_null ;BE
	.BYTE $38 | block_attribute_null, $00 | block_attribute_null, $39 | block_attribute_null, $00 | block_attribute_null ;BF
	.BYTE $23 | block_attribute_wall, $26 | block_attribute_wall, $19 | block_attribute_wall, $3B | block_attribute_wall ;C0
	.BYTE $22 | block_attribute_wall, $38 | block_attribute_wall, $27 | block_attribute_wall, $39 | block_attribute_wall ;C1
	.BYTE $2A | block_attribute_wall, $01 | block_attribute_null, $3C | block_attribute_wall, $01 | block_attribute_null ;C2
	.BYTE $3B | block_attribute_wall, $01 | block_attribute_null, $2B | block_attribute_wall, $01 | block_attribute_null ;C3
	.BYTE $23 | block_attribute_wall, $38 | block_attribute_wall, $01 | block_attribute_null, $01 | block_attribute_null ;C4
	.BYTE $38 | block_attribute_wall, $2B | block_attribute_wall, $01 | block_attribute_null, $01 | block_attribute_null ;C5
	.BYTE $03 | block_attribute_2,    $03 | block_attribute_2,    $01 | block_attribute_null, $01 | block_attribute_null ;C6
	.BYTE $03 | block_attribute_2,    $03 | block_attribute_2,    $23 | block_attribute_wall, $39 | block_attribute_wall ;C7
	.BYTE $03 | block_attribute_2,    $03 | block_attribute_2,    $27 | block_attribute_wall, $38 | block_attribute_wall ;C8
	.BYTE $03 | block_attribute_2,    $03 | block_attribute_2,    $1F | block_attribute_null, $01 | block_attribute_null ;C9
	.BYTE $03 | block_attribute_2,    $03 | block_attribute_2,    $2B | block_attribute_wall, $01 | block_attribute_null ;CA
	.BYTE $21 | block_attribute_wall, $21 | block_attribute_wall, $1F | block_attribute_null, $01 | block_attribute_null ;CB
	.BYTE $2B | block_attribute_wall, $01 | block_attribute_null, $01 | block_attribute_null, $01 | block_attribute_null ;CC
	.BYTE $22 | block_attribute_wall, $39 | block_attribute_wall, $3A | block_attribute_wall, $38 | block_attribute_wall ;CD
	.BYTE $1F | block_attribute_null, $01 | block_attribute_null, $1F | block_attribute_null, $01 | block_attribute_null ;CE
	.BYTE $03 | block_attribute_2,    $31 | block_attribute_null, $01 | block_attribute_null, $31 | block_attribute_null ;CF
	.BYTE $38 | block_attribute_wall, $26 | block_attribute_wall, $21 | block_attribute_wall, $2B | block_attribute_wall ;D0
	.BYTE $39 | block_attribute_wall, $27 | block_attribute_wall, $23 | block_attribute_wall, $38 | block_attribute_wall ;D1
	.BYTE $2A | block_attribute_wall, $3A | block_attribute_wall, $2B | block_attribute_wall, $23 | block_attribute_wall ;D2
	.BYTE $26 | block_attribute_wall, $21 | block_attribute_wall, $38 | block_attribute_wall, $21 | block_attribute_wall ;D3
	.BYTE $21 | block_attribute_wall, $2A | block_attribute_wall, $21 | block_attribute_wall, $3B | block_attribute_wall ;D4
	.BYTE $22 | block_attribute_wall, $39 | block_attribute_wall, $3A | block_attribute_wall, $38 | block_attribute_wall ;D5
	.BYTE $21 | block_attribute_wall, $21 | block_attribute_wall, $2A | block_attribute_wall, $22 | block_attribute_wall ;D6
	.BYTE $2A | block_attribute_wall, $22 | block_attribute_wall, $38 | block_attribute_wall, $26 | block_attribute_wall ;D7
	.BYTE $23 | block_attribute_wall, $26 | block_attribute_wall, $19 | block_attribute_wall, $3B | block_attribute_wall ;D8
	.BYTE $22 | block_attribute_wall, $38 | block_attribute_wall, $27 | block_attribute_wall, $39 | block_attribute_wall ;D9
	.BYTE $21 | block_attribute_wall, $27 | block_attribute_wall, $22 | block_attribute_wall, $38 | block_attribute_wall ;DA
	.BYTE $26 | block_attribute_wall, $2A | block_attribute_wall, $38 | block_attribute_wall, $3B | block_attribute_wall ;DB
	.BYTE $1D | block_attribute_null, $3C | block_attribute_wall, $1D | block_attribute_null, $3C | block_attribute_wall ;DC
	.BYTE $03 | block_attribute_2,    $03 | block_attribute_2,    $21 | block_attribute_wall, $39 | block_attribute_wall ;DD
	.BYTE $3C | block_attribute_wall, $1D | block_attribute_null, $3C | block_attribute_wall, $01 | block_attribute_null ;DE
	.BYTE $39 | block_attribute_wall, $38 | block_attribute_wall, $23 | block_attribute_wall, $29 | block_attribute_wall ;DF
	.BYTE $03 | block_attribute_2,    $03 | block_attribute_2,    $01 | block_attribute_null, $01 | block_attribute_null ;E0
	.BYTE $38 | block_attribute_wall, $2B | block_attribute_wall, $01 | block_attribute_null, $01 | block_attribute_null ;E1
	.BYTE $23 | block_attribute_wall, $38 | block_attribute_wall, $01 | block_attribute_null, $01 | block_attribute_null ;E2
	.BYTE $01 | block_attribute_null, $03 | block_attribute_2,    $39 | block_attribute_wall, $21 | block_attribute_wall ;E3
	.BYTE $01 | block_attribute_null, $01 | block_attribute_null, $03 | block_attribute_2,    $03 | block_attribute_2    ;E4
	.BYTE $03 | block_attribute_2,    $01 | block_attribute_null, $01 | block_attribute_null, $01 | block_attribute_null ;E5
	.BYTE $03 | block_attribute_2,    $03 | block_attribute_2,    $18 | block_attribute_wall, $01 | block_attribute_null ;E6
	.BYTE $23 | block_attribute_wall, $26 | block_attribute_wall, $21 | block_attribute_wall, $3B | block_attribute_wall ;E7
	.BYTE $1D | block_attribute_null, $1C | block_attribute_null, $1D | block_attribute_null, $00 | block_attribute_null ;E8
	.BYTE $1C | block_attribute_null, $00 | block_attribute_null, $1D | block_attribute_null, $00 | block_attribute_null ;E9
	.BYTE $1D | block_attribute_null, $00 | block_attribute_null, $1D | block_attribute_null, $1C | block_attribute_null ;EA
	.BYTE $1C | block_attribute_null, $00 | block_attribute_null, $00 | block_attribute_null, $1C | block_attribute_null ;EB
	.BYTE $1C | block_attribute_null, $00 | block_attribute_null, $1D | block_attribute_null, $1D | block_attribute_null ;EC
	.BYTE $1D | block_attribute_null, $1C | block_attribute_null, $00 | block_attribute_null, $1D | block_attribute_null ;ED
	.BYTE $1D | block_attribute_null, $1D | block_attribute_null, $21 | block_attribute_wall, $21 | block_attribute_wall ;EE
	.BYTE $1D | block_attribute_null, $1D | block_attribute_null, $03 | block_attribute_2,    $03 | block_attribute_2    ;EF
	.BYTE $03 | block_attribute_2,    $03 | block_attribute_2,    $1D | block_attribute_null, $1D | block_attribute_null ;F0
	.BYTE $38 | block_attribute_wall, $2B | block_attribute_wall, $1D | block_attribute_null, $1D | block_attribute_null ;F1
	.BYTE $1D | block_attribute_null, $1D | block_attribute_null, $1C | block_attribute_null, $1D | block_attribute_null ;F2
	.BYTE $2A | block_attribute_wall, $01 | block_attribute_null, $3B | block_attribute_wall, $01 | block_attribute_null ;F3
	.BYTE $3B | block_attribute_wall, $01 | block_attribute_null, $3C | block_attribute_wall, $01 | block_attribute_null ;F4
	.BYTE $00 | block_attribute_null, $1D | block_attribute_null, $1C | block_attribute_null, $00 | block_attribute_null ;F5
	.BYTE $00 | block_attribute_null, $1D | block_attribute_null, $1D | block_attribute_null, $00 | block_attribute_null ;F6
	.BYTE $1D | block_attribute_null, $1D | block_attribute_null, $00 | block_attribute_null, $1C | block_attribute_null ;F7
	.BYTE $1C | block_attribute_null, $00 | block_attribute_null, $00 | block_attribute_null, $1D | block_attribute_null ;F8
	.BYTE $00 | block_attribute_null, $1D | block_attribute_null, $00 | block_attribute_null, $00 | block_attribute_null ;F9
	.BYTE $1D | block_attribute_null, $00 | block_attribute_null, $1C | block_attribute_null, $1D | block_attribute_null ;FA
	.BYTE $1D | block_attribute_null, $00 | block_attribute_null, $00 | block_attribute_null, $1C | block_attribute_null ;FB
	.BYTE $1D | block_attribute_null, $00 | block_attribute_null, $00 | block_attribute_null, $00 | block_attribute_null ;FC
	.BYTE $1D | block_attribute_null, $03 | block_attribute_2,    $00 | block_attribute_null, $18 | block_attribute_wall ;FD
	.BYTE $00 | block_attribute_null, $00 | block_attribute_null, $00 | block_attribute_null, $00 | block_attribute_null ;FE
	.BYTE $00 | block_attribute_null, $00 | block_attribute_null, $00 | block_attribute_null, $00 | block_attribute_null ;FF