oam_sprites_lo_pointers:
	.LOBYTES oam_sprites_00
	.LOBYTES oam_sprites_01
	.LOBYTES oam_sprites_02
	.LOBYTES oam_sprites_03
	.LOBYTES oam_sprites_04
	.LOBYTES oam_sprites_05
	.LOBYTES oam_sprites_06
	.LOBYTES oam_sprites_07
	.LOBYTES oam_sprites_08
	.LOBYTES oam_sprites_09
	.LOBYTES oam_sprites_0a
	.LOBYTES oam_sprites_0b
	.LOBYTES oam_sprites_0c
	.LOBYTES oam_sprites_0d
	.LOBYTES oam_sprites_0e
	.LOBYTES oam_sprites_0f
	.LOBYTES oam_sprites_10
	.LOBYTES oam_sprites_11
	.LOBYTES oam_sprites_12
	.LOBYTES oam_sprites_13
	.LOBYTES oam_sprites_14
	.LOBYTES oam_sprites_15
	.LOBYTES oam_sprites_16
	.LOBYTES oam_sprites_17
	.LOBYTES oam_sprites_18
	.LOBYTES oam_sprites_19
	.LOBYTES oam_sprites_1a
	.LOBYTES oam_sprites_1b
	.LOBYTES oam_sprites_1c
	.LOBYTES oam_sprites_1d
	.LOBYTES oam_sprites_1e
	.LOBYTES oam_sprites_1f
	.LOBYTES oam_sprites_20
	.LOBYTES oam_sprites_21
	.LOBYTES oam_sprites_22
	.LOBYTES oam_sprites_23
	.LOBYTES oam_sprites_24
	.LOBYTES oam_sprites_25
	.LOBYTES oam_sprites_26
	.LOBYTES oam_sprites_27
	.LOBYTES oam_sprites_28
	.LOBYTES oam_sprites_29
	.LOBYTES oam_sprites_2a
	.LOBYTES oam_sprites_2b
	.LOBYTES oam_sprites_2c
	.LOBYTES oam_sprites_2d
	.LOBYTES oam_sprites_2e
	.LOBYTES oam_sprites_2f
	.LOBYTES oam_sprites_30
	.LOBYTES oam_sprites_31
	.LOBYTES oam_sprites_32
	.LOBYTES oam_sprites_33
	.LOBYTES oam_sprites_34
	.LOBYTES oam_sprites_35
	.LOBYTES oam_sprites_36
	.LOBYTES oam_sprites_37
	.LOBYTES oam_sprites_38
	.LOBYTES oam_sprites_39
	.LOBYTES oam_sprites_3a
	.LOBYTES oam_sprites_3b
	.LOBYTES oam_sprites_3c
	.LOBYTES oam_sprites_3d
	.LOBYTES oam_sprites_3e
	.LOBYTES oam_sprites_3f
	.LOBYTES oam_sprites_40
	.LOBYTES oam_sprites_41
	.LOBYTES oam_sprites_42
	.LOBYTES oam_sprites_43
	.LOBYTES oam_sprites_44
	.LOBYTES oam_sprites_45
	.LOBYTES oam_sprites_46
	.LOBYTES oam_sprites_47
	.LOBYTES oam_sprites_48
	.LOBYTES oam_sprites_49
	.LOBYTES oam_sprites_4a
	.LOBYTES oam_sprites_4b
	.LOBYTES oam_sprites_4c
	.LOBYTES oam_sprites_4d
	.LOBYTES oam_sprites_4e
	.LOBYTES oam_sprites_4f
	.LOBYTES oam_sprites_50
	.LOBYTES oam_sprites_51
	.LOBYTES oam_sprites_52
	.LOBYTES oam_sprites_53
	.LOBYTES oam_sprites_54
	.LOBYTES oam_sprites_55
	.LOBYTES oam_sprites_56
	.LOBYTES oam_sprites_57
	.LOBYTES oam_sprites_58
	.LOBYTES oam_sprites_59
	.LOBYTES oam_sprites_5a
	.LOBYTES oam_sprites_5b
	.LOBYTES oam_sprites_5c
	.LOBYTES oam_sprites_5d
	.LOBYTES oam_sprites_5e
	.LOBYTES oam_sprites_5f
	.LOBYTES oam_sprites_60
	.LOBYTES oam_sprites_61
	.LOBYTES oam_sprites_62
	.LOBYTES oam_sprites_63
	.LOBYTES oam_sprites_64
	.LOBYTES oam_sprites_65
	.LOBYTES oam_sprites_66
	.LOBYTES oam_sprites_67
	.LOBYTES oam_sprites_68
	.LOBYTES oam_sprites_69
	.LOBYTES oam_sprites_6a
	.LOBYTES oam_sprites_6b
	.LOBYTES oam_sprites_6c
	.LOBYTES oam_sprites_6d
	.LOBYTES oam_sprites_6e
	.LOBYTES oam_sprites_6f
	.LOBYTES oam_sprites_70
	.LOBYTES oam_sprites_71
	.LOBYTES oam_sprites_72
	.LOBYTES oam_sprites_73
	.LOBYTES oam_sprites_74
	.LOBYTES oam_sprites_75
	.LOBYTES oam_sprites_76
	.LOBYTES oam_sprites_77
	.LOBYTES oam_sprites_78
	.LOBYTES oam_sprites_79
	.LOBYTES oam_sprites_7a
	.LOBYTES oam_sprites_7b
	.LOBYTES oam_sprites_7c
	.LOBYTES oam_sprites_7d
	.LOBYTES oam_sprites_7e
	.LOBYTES oam_sprites_7f
	.LOBYTES oam_sprites_80
	.LOBYTES oam_sprites_81
	.LOBYTES oam_sprites_82
	.LOBYTES oam_sprites_83
	.LOBYTES oam_sprites_84
	.LOBYTES oam_sprites_85
	.LOBYTES oam_sprites_86
	.LOBYTES oam_sprites_87
	.LOBYTES oam_sprites_88
	.LOBYTES oam_sprites_89
	.LOBYTES oam_sprites_8a
	.LOBYTES oam_sprites_8b
	.LOBYTES oam_sprites_8c
	.LOBYTES oam_sprites_8d
	.LOBYTES oam_sprites_8e
	.LOBYTES oam_sprites_8f
	.LOBYTES oam_sprites_90
	.LOBYTES oam_sprites_91
	.LOBYTES oam_sprites_92
	.LOBYTES oam_sprites_93
	.LOBYTES oam_sprites_94
	.LOBYTES oam_sprites_95
	.LOBYTES oam_sprites_96
	.LOBYTES oam_sprites_97
	.LOBYTES oam_sprites_98
	.LOBYTES oam_sprites_99
	.LOBYTES oam_sprites_9a
	.LOBYTES oam_sprites_9b
	.LOBYTES oam_sprites_9c
	.LOBYTES oam_sprites_9d
	.LOBYTES oam_sprites_9e
	.LOBYTES oam_sprites_9f
	.LOBYTES oam_sprites_a0
	.LOBYTES oam_sprites_a1
	.LOBYTES oam_sprites_a2
	.LOBYTES oam_sprites_a3
	.LOBYTES oam_sprites_a4
	.LOBYTES oam_sprites_a5
	.LOBYTES oam_sprites_a6
	.LOBYTES oam_sprites_a7
	.LOBYTES oam_sprites_a8
	.LOBYTES oam_sprites_a9
	.LOBYTES oam_sprites_aa
	.LOBYTES oam_sprites_ab
	.LOBYTES oam_sprites_ac
	.LOBYTES oam_sprites_ad
	.LOBYTES oam_sprites_ae
	.LOBYTES oam_sprites_af
	.LOBYTES oam_sprites_b0
	.LOBYTES oam_sprites_b1
	.LOBYTES oam_sprites_b2
	.LOBYTES oam_sprites_b3
	.LOBYTES oam_sprites_b4
	.LOBYTES oam_sprites_b5
	.LOBYTES oam_sprites_b6
	.LOBYTES oam_sprites_b7
	.LOBYTES oam_sprites_b8
	.LOBYTES oam_sprites_b9
	.LOBYTES oam_sprites_ba
	.LOBYTES oam_sprites_bb
	.LOBYTES oam_sprites_bc
	.LOBYTES oam_sprites_bd
	.LOBYTES oam_sprites_be
	.LOBYTES oam_sprites_bf
	.LOBYTES oam_sprites_c0
	.LOBYTES oam_sprites_c1
	.LOBYTES oam_sprites_c2
	.LOBYTES oam_sprites_c3
	.LOBYTES oam_sprites_c4
	.LOBYTES oam_sprites_c5
	.LOBYTES oam_sprites_c6
	.LOBYTES oam_sprites_c7
	.LOBYTES oam_sprites_c8
	.LOBYTES oam_sprites_c9
	.LOBYTES oam_sprites_ca
	.LOBYTES oam_sprites_cb
	.LOBYTES oam_sprites_cc
	.LOBYTES oam_sprites_cd
	.LOBYTES oam_sprites_ce
	.LOBYTES oam_sprites_cf
	.LOBYTES oam_sprites_d0
	.LOBYTES oam_sprites_d1
	.LOBYTES oam_sprites_d2
	.LOBYTES oam_sprites_d3
	.LOBYTES oam_sprites_d4
	.LOBYTES oam_sprites_d5
	.LOBYTES oam_sprites_d6
	.LOBYTES oam_sprites_d7
	.LOBYTES oam_sprites_d8
	.LOBYTES oam_sprites_d9
	.LOBYTES oam_sprites_da
	.LOBYTES oam_sprites_db
	.LOBYTES oam_sprites_dc
	.LOBYTES oam_sprites_dd
	.LOBYTES oam_sprites_de
	.LOBYTES oam_sprites_df
	
;unused
	.BYTE $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	.BYTE $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	.BYTE $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	.BYTE $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF

oam_enemies_sprites_lo_pointers:
	.LOBYTES oam_sprites_100
	.LOBYTES oam_sprites_101
	.LOBYTES oam_sprites_102
	.LOBYTES oam_sprites_103
	.LOBYTES oam_sprites_104
	.LOBYTES oam_sprites_105
	.LOBYTES oam_sprites_106
	.LOBYTES oam_sprites_107
	.LOBYTES oam_sprites_108
	.LOBYTES oam_sprites_109
	.LOBYTES oam_sprites_10a
	.LOBYTES oam_sprites_10b
	.LOBYTES oam_sprites_10c
	.LOBYTES oam_sprites_10d
	.LOBYTES oam_sprites_10e
	.LOBYTES oam_sprites_10f
	.LOBYTES oam_sprites_110
	.LOBYTES oam_sprites_111
	.LOBYTES oam_sprites_112
	.LOBYTES oam_sprites_113
	.LOBYTES oam_sprites_114
	.LOBYTES oam_sprites_115
	.LOBYTES oam_sprites_116
	.LOBYTES oam_sprites_117
	.LOBYTES oam_sprites_118
	.LOBYTES oam_sprites_119
	.LOBYTES oam_sprites_11a
	.LOBYTES oam_sprites_11b
	.LOBYTES oam_sprites_11c
	.LOBYTES oam_sprites_11d
	.LOBYTES oam_sprites_11e
	.LOBYTES oam_sprites_11f
	.LOBYTES oam_sprites_120
	.LOBYTES oam_sprites_121
	.LOBYTES oam_sprites_122
	.LOBYTES oam_sprites_123
	.LOBYTES oam_sprites_124
	.LOBYTES oam_sprites_125
	.LOBYTES oam_sprites_126
	.LOBYTES oam_sprites_127
	.LOBYTES oam_sprites_128
	.LOBYTES oam_sprites_129
	.LOBYTES oam_sprites_12a
	.LOBYTES oam_sprites_12b
	.LOBYTES oam_sprites_12c
	.LOBYTES oam_sprites_12d
	.LOBYTES oam_sprites_12e
	.LOBYTES oam_sprites_12f
	.LOBYTES oam_sprites_130
	.LOBYTES oam_sprites_131
	.LOBYTES oam_sprites_132
	.LOBYTES oam_sprites_133
	.LOBYTES oam_sprites_134
	.LOBYTES oam_sprites_135
	.LOBYTES oam_sprites_136
	.LOBYTES oam_sprites_137
	.LOBYTES oam_sprites_138
	.LOBYTES oam_sprites_139
	.LOBYTES oam_sprites_13a
	.LOBYTES oam_sprites_13b
	.LOBYTES oam_sprites_13c
	.LOBYTES oam_sprites_13d
	.LOBYTES oam_sprites_13e
	.LOBYTES oam_sprites_13f
	.LOBYTES oam_sprites_140
	.LOBYTES oam_sprites_141
	.LOBYTES oam_sprites_142
	.LOBYTES oam_sprites_143
	.LOBYTES oam_sprites_144
	.LOBYTES oam_sprites_145
	.LOBYTES oam_sprites_146
	.LOBYTES oam_sprites_147
	.LOBYTES oam_sprites_148
	.LOBYTES oam_sprites_149
	.LOBYTES oam_sprites_14a
	.LOBYTES oam_sprites_14b
	.LOBYTES oam_sprites_14c
	.LOBYTES oam_sprites_14d
	.LOBYTES oam_sprites_14e
	.LOBYTES oam_sprites_14f
	.LOBYTES oam_sprites_150
	.LOBYTES oam_sprites_151
	.LOBYTES oam_sprites_152
	.LOBYTES oam_sprites_153
	.LOBYTES oam_sprites_154
	.LOBYTES oam_sprites_155
	.LOBYTES oam_sprites_156
	.LOBYTES oam_sprites_157
	.LOBYTES oam_sprites_158
	.LOBYTES oam_sprites_159
	.LOBYTES oam_sprites_15a
	.LOBYTES oam_sprites_15b
	.LOBYTES oam_sprites_15c
	.LOBYTES oam_sprites_15d
	.LOBYTES oam_sprites_15e
	.LOBYTES oam_sprites_15f
	.LOBYTES oam_sprites_160
	.LOBYTES oam_sprites_161
	.LOBYTES oam_sprites_162
	.LOBYTES oam_sprites_163
	.LOBYTES oam_sprites_164
	.LOBYTES oam_sprites_165
	.LOBYTES oam_sprites_166
	.LOBYTES oam_sprites_167
	.LOBYTES oam_sprites_168
	.LOBYTES oam_sprites_169
	.LOBYTES oam_sprites_16a
	.LOBYTES oam_sprites_16b
	.LOBYTES oam_sprites_16c
	.LOBYTES oam_sprites_16d
	.LOBYTES oam_sprites_16e
	.LOBYTES oam_sprites_16f
	.LOBYTES oam_sprites_170
	.LOBYTES oam_sprites_171
	.LOBYTES oam_sprites_172
	.LOBYTES oam_sprites_173
	.LOBYTES oam_sprites_174
	.LOBYTES oam_sprites_175
	.LOBYTES oam_sprites_176
	.LOBYTES oam_sprites_177
	.LOBYTES oam_sprites_178
	.LOBYTES oam_sprites_179
	.LOBYTES oam_sprites_17a
	.LOBYTES oam_sprites_17b
	.LOBYTES oam_sprites_17c
	.LOBYTES oam_sprites_17d
	.LOBYTES oam_sprites_17e
	.LOBYTES oam_sprites_17f
	.LOBYTES oam_sprites_180
	.LOBYTES oam_sprites_181
	.LOBYTES oam_sprites_182
	.LOBYTES oam_sprites_183
	.LOBYTES oam_sprites_184
	.LOBYTES oam_sprites_185
	.LOBYTES oam_sprites_186
	.LOBYTES oam_sprites_187
	.LOBYTES oam_sprites_188
	.LOBYTES oam_sprites_189
	.LOBYTES oam_sprites_18a
	.LOBYTES oam_sprites_18b
	.LOBYTES oam_sprites_18c
	.LOBYTES oam_sprites_18d
	.LOBYTES oam_sprites_18e
	.LOBYTES oam_sprites_18f
	.LOBYTES oam_sprites_190
	.LOBYTES oam_sprites_191
	.LOBYTES oam_sprites_192
	.LOBYTES oam_sprites_193
	.LOBYTES oam_sprites_194
	.LOBYTES oam_sprites_195
	.LOBYTES oam_sprites_196
	.LOBYTES oam_sprites_197
	.LOBYTES oam_sprites_198
	.LOBYTES oam_sprites_199
	.LOBYTES oam_sprites_19a
	.LOBYTES oam_sprites_19b
	.LOBYTES oam_sprites_19c
	.LOBYTES oam_sprites_19d
	.LOBYTES oam_sprites_19e
	.LOBYTES oam_sprites_19f
	.LOBYTES oam_sprites_1a0
	.LOBYTES oam_sprites_1a1
	.LOBYTES oam_sprites_1a2
	.LOBYTES oam_sprites_1a3
	.LOBYTES oam_sprites_1a4
	.LOBYTES oam_sprites_1a5
	.LOBYTES oam_sprites_1a6
	.LOBYTES oam_sprites_1a7
	.LOBYTES oam_sprites_1a8
	.LOBYTES oam_sprites_1a9
	.LOBYTES oam_sprites_1aa
	.LOBYTES oam_sprites_1ab
	.LOBYTES oam_sprites_1ac
	.LOBYTES oam_sprites_1ad
	.LOBYTES oam_sprites_1ae
	.LOBYTES oam_sprites_1af
	.LOBYTES oam_sprites_1b0
	.LOBYTES oam_sprites_1b1
	.LOBYTES oam_sprites_1b2
	.LOBYTES oam_sprites_1b3
	.LOBYTES oam_sprites_1b4
	.LOBYTES oam_sprites_1b5
	.LOBYTES oam_sprites_1b6
	.LOBYTES oam_sprites_1b7
	.LOBYTES oam_sprites_1b8
	.LOBYTES oam_sprites_1b9
	.LOBYTES oam_sprites_1ba
	.LOBYTES oam_sprites_1bb
	.LOBYTES oam_sprites_1bc
	.LOBYTES oam_sprites_1bd
	.LOBYTES oam_sprites_1be
	.LOBYTES oam_sprites_1bf
	.LOBYTES oam_sprites_1c0
	.LOBYTES oam_sprites_1c1
	.LOBYTES oam_sprites_1c2
	.LOBYTES oam_sprites_1c3
	.LOBYTES oam_sprites_1c4
	.LOBYTES oam_sprites_1c5
	.LOBYTES oam_sprites_1c6
	.LOBYTES oam_sprites_1c7
	.LOBYTES oam_sprites_1c8
	.LOBYTES oam_sprites_1c9
	.LOBYTES oam_sprites_1ca
	.LOBYTES oam_sprites_1cb
	.LOBYTES oam_sprites_1cc
	.LOBYTES oam_sprites_1cd
	.LOBYTES oam_sprites_1ce
	.LOBYTES oam_sprites_1cf
	.LOBYTES oam_sprites_1d0
	.LOBYTES oam_sprites_1d1
	.LOBYTES oam_sprites_1d2
	.LOBYTES oam_sprites_1d3
	.LOBYTES oam_sprites_1d4
	.LOBYTES oam_sprites_1d5
	.LOBYTES oam_sprites_1d6
	.LOBYTES oam_sprites_1d7
	.LOBYTES oam_sprites_1d8
	.LOBYTES oam_sprites_1d9
	.LOBYTES oam_sprites_1da
	.LOBYTES oam_sprites_1db
	.LOBYTES oam_sprites_1dc
	.LOBYTES oam_sprites_1dd
	.LOBYTES oam_sprites_1de
	.LOBYTES oam_sprites_1df
	.LOBYTES oam_sprites_1e0
	.LOBYTES oam_sprites_1e1
	.LOBYTES oam_sprites_1e2
	.LOBYTES oam_sprites_1e3
	.LOBYTES oam_sprites_1e4
	.LOBYTES oam_sprites_1e5
	.LOBYTES oam_sprites_1e6
	.LOBYTES oam_sprites_1e7
	.LOBYTES oam_sprites_1e8
	.LOBYTES oam_sprites_1e9
	.LOBYTES oam_sprites_1ea
	.LOBYTES oam_sprites_1eb
	.LOBYTES oam_sprites_1ec
	.LOBYTES oam_sprites_1ed
	.LOBYTES oam_sprites_1ee
	.LOBYTES oam_sprites_1ef

;unused
	.BYTE $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	.BYTE $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF

oam_sprites_hi_pointers:
	.HIBYTES oam_sprites_00
	.HIBYTES oam_sprites_01
	.HIBYTES oam_sprites_02
	.HIBYTES oam_sprites_03
	.HIBYTES oam_sprites_04
	.HIBYTES oam_sprites_05
	.HIBYTES oam_sprites_06
	.HIBYTES oam_sprites_07
	.HIBYTES oam_sprites_08
	.HIBYTES oam_sprites_09
	.HIBYTES oam_sprites_0a
	.HIBYTES oam_sprites_0b
	.HIBYTES oam_sprites_0c
	.HIBYTES oam_sprites_0d
	.HIBYTES oam_sprites_0e
	.HIBYTES oam_sprites_0f
	.HIBYTES oam_sprites_10
	.HIBYTES oam_sprites_11
	.HIBYTES oam_sprites_12
	.HIBYTES oam_sprites_13
	.HIBYTES oam_sprites_14
	.HIBYTES oam_sprites_15
	.HIBYTES oam_sprites_16
	.HIBYTES oam_sprites_17
	.HIBYTES oam_sprites_18
	.HIBYTES oam_sprites_19
	.HIBYTES oam_sprites_1a
	.HIBYTES oam_sprites_1b
	.HIBYTES oam_sprites_1c
	.HIBYTES oam_sprites_1d
	.HIBYTES oam_sprites_1e
	.HIBYTES oam_sprites_1f
	.HIBYTES oam_sprites_20
	.HIBYTES oam_sprites_21
	.HIBYTES oam_sprites_22
	.HIBYTES oam_sprites_23
	.HIBYTES oam_sprites_24
	.HIBYTES oam_sprites_25
	.HIBYTES oam_sprites_26
	.HIBYTES oam_sprites_27
	.HIBYTES oam_sprites_28
	.HIBYTES oam_sprites_29
	.HIBYTES oam_sprites_2a
	.HIBYTES oam_sprites_2b
	.HIBYTES oam_sprites_2c
	.HIBYTES oam_sprites_2d
	.HIBYTES oam_sprites_2e
	.HIBYTES oam_sprites_2f
	.HIBYTES oam_sprites_30
	.HIBYTES oam_sprites_31
	.HIBYTES oam_sprites_32
	.HIBYTES oam_sprites_33
	.HIBYTES oam_sprites_34
	.HIBYTES oam_sprites_35
	.HIBYTES oam_sprites_36
	.HIBYTES oam_sprites_37
	.HIBYTES oam_sprites_38
	.HIBYTES oam_sprites_39
	.HIBYTES oam_sprites_3a
	.HIBYTES oam_sprites_3b
	.HIBYTES oam_sprites_3c
	.HIBYTES oam_sprites_3d
	.HIBYTES oam_sprites_3e
	.HIBYTES oam_sprites_3f
	.HIBYTES oam_sprites_40
	.HIBYTES oam_sprites_41
	.HIBYTES oam_sprites_42
	.HIBYTES oam_sprites_43
	.HIBYTES oam_sprites_44
	.HIBYTES oam_sprites_45
	.HIBYTES oam_sprites_46
	.HIBYTES oam_sprites_47
	.HIBYTES oam_sprites_48
	.HIBYTES oam_sprites_49
	.HIBYTES oam_sprites_4a
	.HIBYTES oam_sprites_4b
	.HIBYTES oam_sprites_4c
	.HIBYTES oam_sprites_4d
	.HIBYTES oam_sprites_4e
	.HIBYTES oam_sprites_4f
	.HIBYTES oam_sprites_50
	.HIBYTES oam_sprites_51
	.HIBYTES oam_sprites_52
	.HIBYTES oam_sprites_53
	.HIBYTES oam_sprites_54
	.HIBYTES oam_sprites_55
	.HIBYTES oam_sprites_56
	.HIBYTES oam_sprites_57
	.HIBYTES oam_sprites_58
	.HIBYTES oam_sprites_59
	.HIBYTES oam_sprites_5a
	.HIBYTES oam_sprites_5b
	.HIBYTES oam_sprites_5c
	.HIBYTES oam_sprites_5d
	.HIBYTES oam_sprites_5e
	.HIBYTES oam_sprites_5f
	.HIBYTES oam_sprites_60
	.HIBYTES oam_sprites_61
	.HIBYTES oam_sprites_62
	.HIBYTES oam_sprites_63
	.HIBYTES oam_sprites_64
	.HIBYTES oam_sprites_65
	.HIBYTES oam_sprites_66
	.HIBYTES oam_sprites_67
	.HIBYTES oam_sprites_68
	.HIBYTES oam_sprites_69
	.HIBYTES oam_sprites_6a
	.HIBYTES oam_sprites_6b
	.HIBYTES oam_sprites_6c
	.HIBYTES oam_sprites_6d
	.HIBYTES oam_sprites_6e
	.HIBYTES oam_sprites_6f
	.HIBYTES oam_sprites_70
	.HIBYTES oam_sprites_71
	.HIBYTES oam_sprites_72
	.HIBYTES oam_sprites_73
	.HIBYTES oam_sprites_74
	.HIBYTES oam_sprites_75
	.HIBYTES oam_sprites_76
	.HIBYTES oam_sprites_77
	.HIBYTES oam_sprites_78
	.HIBYTES oam_sprites_79
	.HIBYTES oam_sprites_7a
	.HIBYTES oam_sprites_7b
	.HIBYTES oam_sprites_7c
	.HIBYTES oam_sprites_7d
	.HIBYTES oam_sprites_7e
	.HIBYTES oam_sprites_7f
	.HIBYTES oam_sprites_80
	.HIBYTES oam_sprites_81
	.HIBYTES oam_sprites_82
	.HIBYTES oam_sprites_83
	.HIBYTES oam_sprites_84
	.HIBYTES oam_sprites_85
	.HIBYTES oam_sprites_86
	.HIBYTES oam_sprites_87
	.HIBYTES oam_sprites_88
	.HIBYTES oam_sprites_89
	.HIBYTES oam_sprites_8a
	.HIBYTES oam_sprites_8b
	.HIBYTES oam_sprites_8c
	.HIBYTES oam_sprites_8d
	.HIBYTES oam_sprites_8e
	.HIBYTES oam_sprites_8f
	.HIBYTES oam_sprites_90
	.HIBYTES oam_sprites_91
	.HIBYTES oam_sprites_92
	.HIBYTES oam_sprites_93
	.HIBYTES oam_sprites_94
	.HIBYTES oam_sprites_95
	.HIBYTES oam_sprites_96
	.HIBYTES oam_sprites_97
	.HIBYTES oam_sprites_98
	.HIBYTES oam_sprites_99
	.HIBYTES oam_sprites_9a
	.HIBYTES oam_sprites_9b
	.HIBYTES oam_sprites_9c
	.HIBYTES oam_sprites_9d
	.HIBYTES oam_sprites_9e
	.HIBYTES oam_sprites_9f
	.HIBYTES oam_sprites_a0
	.HIBYTES oam_sprites_a1
	.HIBYTES oam_sprites_a2
	.HIBYTES oam_sprites_a3
	.HIBYTES oam_sprites_a4
	.HIBYTES oam_sprites_a5
	.HIBYTES oam_sprites_a6
	.HIBYTES oam_sprites_a7
	.HIBYTES oam_sprites_a8
	.HIBYTES oam_sprites_a9
	.HIBYTES oam_sprites_aa
	.HIBYTES oam_sprites_ab
	.HIBYTES oam_sprites_ac
	.HIBYTES oam_sprites_ad
	.HIBYTES oam_sprites_ae
	.HIBYTES oam_sprites_af
	.HIBYTES oam_sprites_b0
	.HIBYTES oam_sprites_b1
	.HIBYTES oam_sprites_b2
	.HIBYTES oam_sprites_b3
	.HIBYTES oam_sprites_b4
	.HIBYTES oam_sprites_b5
	.HIBYTES oam_sprites_b6
	.HIBYTES oam_sprites_b7
	.HIBYTES oam_sprites_b8
	.HIBYTES oam_sprites_b9
	.HIBYTES oam_sprites_ba
	.HIBYTES oam_sprites_bb
	.HIBYTES oam_sprites_bc
	.HIBYTES oam_sprites_bd
	.HIBYTES oam_sprites_be
	.HIBYTES oam_sprites_bf
	.HIBYTES oam_sprites_c0
	.HIBYTES oam_sprites_c1
	.HIBYTES oam_sprites_c2
	.HIBYTES oam_sprites_c3
	.HIBYTES oam_sprites_c4
	.HIBYTES oam_sprites_c5
	.HIBYTES oam_sprites_c6
	.HIBYTES oam_sprites_c7
	.HIBYTES oam_sprites_c8
	.HIBYTES oam_sprites_c9
	.HIBYTES oam_sprites_ca
	.HIBYTES oam_sprites_cb
	.HIBYTES oam_sprites_cc
	.HIBYTES oam_sprites_cd
	.HIBYTES oam_sprites_ce
	.HIBYTES oam_sprites_cf
	.HIBYTES oam_sprites_d0
	.HIBYTES oam_sprites_d1
	.HIBYTES oam_sprites_d2
	.HIBYTES oam_sprites_d3
	.HIBYTES oam_sprites_d4
	.HIBYTES oam_sprites_d5
	.HIBYTES oam_sprites_d6
	.HIBYTES oam_sprites_d7
	.HIBYTES oam_sprites_d8
	.HIBYTES oam_sprites_d9
	.HIBYTES oam_sprites_da
	.HIBYTES oam_sprites_db
	.HIBYTES oam_sprites_dc
	.HIBYTES oam_sprites_dd
	.HIBYTES oam_sprites_de
	.HIBYTES oam_sprites_df

;unused
	.BYTE $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	.BYTE $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	.BYTE $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	.BYTE $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF

oam_enemies_sprites_hi_pointers:
	.HIBYTES oam_sprites_100
	.HIBYTES oam_sprites_101
	.HIBYTES oam_sprites_102
	.HIBYTES oam_sprites_103
	.HIBYTES oam_sprites_104
	.HIBYTES oam_sprites_105
	.HIBYTES oam_sprites_106
	.HIBYTES oam_sprites_107
	.HIBYTES oam_sprites_108
	.HIBYTES oam_sprites_109
	.HIBYTES oam_sprites_10a
	.HIBYTES oam_sprites_10b
	.HIBYTES oam_sprites_10c
	.HIBYTES oam_sprites_10d
	.HIBYTES oam_sprites_10e
	.HIBYTES oam_sprites_10f
	.HIBYTES oam_sprites_110
	.HIBYTES oam_sprites_111
	.HIBYTES oam_sprites_112
	.HIBYTES oam_sprites_113
	.HIBYTES oam_sprites_114
	.HIBYTES oam_sprites_115
	.HIBYTES oam_sprites_116
	.HIBYTES oam_sprites_117
	.HIBYTES oam_sprites_118
	.HIBYTES oam_sprites_119
	.HIBYTES oam_sprites_11a
	.HIBYTES oam_sprites_11b
	.HIBYTES oam_sprites_11c
	.HIBYTES oam_sprites_11d
	.HIBYTES oam_sprites_11e
	.HIBYTES oam_sprites_11f
	.HIBYTES oam_sprites_120
	.HIBYTES oam_sprites_121
	.HIBYTES oam_sprites_122
	.HIBYTES oam_sprites_123
	.HIBYTES oam_sprites_124
	.HIBYTES oam_sprites_125
	.HIBYTES oam_sprites_126
	.HIBYTES oam_sprites_127
	.HIBYTES oam_sprites_128
	.HIBYTES oam_sprites_129
	.HIBYTES oam_sprites_12a
	.HIBYTES oam_sprites_12b
	.HIBYTES oam_sprites_12c
	.HIBYTES oam_sprites_12d
	.HIBYTES oam_sprites_12e
	.HIBYTES oam_sprites_12f
	.HIBYTES oam_sprites_130
	.HIBYTES oam_sprites_131
	.HIBYTES oam_sprites_132
	.HIBYTES oam_sprites_133
	.HIBYTES oam_sprites_134
	.HIBYTES oam_sprites_135
	.HIBYTES oam_sprites_136
	.HIBYTES oam_sprites_137
	.HIBYTES oam_sprites_138
	.HIBYTES oam_sprites_139
	.HIBYTES oam_sprites_13a
	.HIBYTES oam_sprites_13b
	.HIBYTES oam_sprites_13c
	.HIBYTES oam_sprites_13d
	.HIBYTES oam_sprites_13e
	.HIBYTES oam_sprites_13f
	.HIBYTES oam_sprites_140
	.HIBYTES oam_sprites_141
	.HIBYTES oam_sprites_142
	.HIBYTES oam_sprites_143
	.HIBYTES oam_sprites_144
	.HIBYTES oam_sprites_145
	.HIBYTES oam_sprites_146
	.HIBYTES oam_sprites_147
	.HIBYTES oam_sprites_148
	.HIBYTES oam_sprites_149
	.HIBYTES oam_sprites_14a
	.HIBYTES oam_sprites_14b
	.HIBYTES oam_sprites_14c
	.HIBYTES oam_sprites_14d
	.HIBYTES oam_sprites_14e
	.HIBYTES oam_sprites_14f
	.HIBYTES oam_sprites_150
	.HIBYTES oam_sprites_151
	.HIBYTES oam_sprites_152
	.HIBYTES oam_sprites_153
	.HIBYTES oam_sprites_154
	.HIBYTES oam_sprites_155
	.HIBYTES oam_sprites_156
	.HIBYTES oam_sprites_157
	.HIBYTES oam_sprites_158
	.HIBYTES oam_sprites_159
	.HIBYTES oam_sprites_15a
	.HIBYTES oam_sprites_15b
	.HIBYTES oam_sprites_15c
	.HIBYTES oam_sprites_15d
	.HIBYTES oam_sprites_15e
	.HIBYTES oam_sprites_15f
	.HIBYTES oam_sprites_160
	.HIBYTES oam_sprites_161
	.HIBYTES oam_sprites_162
	.HIBYTES oam_sprites_163
	.HIBYTES oam_sprites_164
	.HIBYTES oam_sprites_165
	.HIBYTES oam_sprites_166
	.HIBYTES oam_sprites_167
	.HIBYTES oam_sprites_168
	.HIBYTES oam_sprites_169
	.HIBYTES oam_sprites_16a
	.HIBYTES oam_sprites_16b
	.HIBYTES oam_sprites_16c
	.HIBYTES oam_sprites_16d
	.HIBYTES oam_sprites_16e
	.HIBYTES oam_sprites_16f
	.HIBYTES oam_sprites_170
	.HIBYTES oam_sprites_171
	.HIBYTES oam_sprites_172
	.HIBYTES oam_sprites_173
	.HIBYTES oam_sprites_174
	.HIBYTES oam_sprites_175
	.HIBYTES oam_sprites_176
	.HIBYTES oam_sprites_177
	.HIBYTES oam_sprites_178
	.HIBYTES oam_sprites_179
	.HIBYTES oam_sprites_17a
	.HIBYTES oam_sprites_17b
	.HIBYTES oam_sprites_17c
	.HIBYTES oam_sprites_17d
	.HIBYTES oam_sprites_17e
	.HIBYTES oam_sprites_17f
	.HIBYTES oam_sprites_180
	.HIBYTES oam_sprites_181
	.HIBYTES oam_sprites_182
	.HIBYTES oam_sprites_183
	.HIBYTES oam_sprites_184
	.HIBYTES oam_sprites_185
	.HIBYTES oam_sprites_186
	.HIBYTES oam_sprites_187
	.HIBYTES oam_sprites_188
	.HIBYTES oam_sprites_189
	.HIBYTES oam_sprites_18a
	.HIBYTES oam_sprites_18b
	.HIBYTES oam_sprites_18c
	.HIBYTES oam_sprites_18d
	.HIBYTES oam_sprites_18e
	.HIBYTES oam_sprites_18f
	.HIBYTES oam_sprites_190
	.HIBYTES oam_sprites_191
	.HIBYTES oam_sprites_192
	.HIBYTES oam_sprites_193
	.HIBYTES oam_sprites_194
	.HIBYTES oam_sprites_195
	.HIBYTES oam_sprites_196
	.HIBYTES oam_sprites_197
	.HIBYTES oam_sprites_198
	.HIBYTES oam_sprites_199
	.HIBYTES oam_sprites_19a
	.HIBYTES oam_sprites_19b
	.HIBYTES oam_sprites_19c
	.HIBYTES oam_sprites_19d
	.HIBYTES oam_sprites_19e
	.HIBYTES oam_sprites_19f
	.HIBYTES oam_sprites_1a0
	.HIBYTES oam_sprites_1a1
	.HIBYTES oam_sprites_1a2
	.HIBYTES oam_sprites_1a3
	.HIBYTES oam_sprites_1a4
	.HIBYTES oam_sprites_1a5
	.HIBYTES oam_sprites_1a6
	.HIBYTES oam_sprites_1a7
	.HIBYTES oam_sprites_1a8
	.HIBYTES oam_sprites_1a9
	.HIBYTES oam_sprites_1aa
	.HIBYTES oam_sprites_1ab
	.HIBYTES oam_sprites_1ac
	.HIBYTES oam_sprites_1ad
	.HIBYTES oam_sprites_1ae
	.HIBYTES oam_sprites_1af
	.HIBYTES oam_sprites_1b0
	.HIBYTES oam_sprites_1b1
	.HIBYTES oam_sprites_1b2
	.HIBYTES oam_sprites_1b3
	.HIBYTES oam_sprites_1b4
	.HIBYTES oam_sprites_1b5
	.HIBYTES oam_sprites_1b6
	.HIBYTES oam_sprites_1b7
	.HIBYTES oam_sprites_1b8
	.HIBYTES oam_sprites_1b9
	.HIBYTES oam_sprites_1ba
	.HIBYTES oam_sprites_1bb
	.HIBYTES oam_sprites_1bc
	.HIBYTES oam_sprites_1bd
	.HIBYTES oam_sprites_1be
	.HIBYTES oam_sprites_1bf
	.HIBYTES oam_sprites_1c0
	.HIBYTES oam_sprites_1c1
	.HIBYTES oam_sprites_1c2
	.HIBYTES oam_sprites_1c3
	.HIBYTES oam_sprites_1c4
	.HIBYTES oam_sprites_1c5
	.HIBYTES oam_sprites_1c6
	.HIBYTES oam_sprites_1c7
	.HIBYTES oam_sprites_1c8
	.HIBYTES oam_sprites_1c9
	.HIBYTES oam_sprites_1ca
	.HIBYTES oam_sprites_1cb
	.HIBYTES oam_sprites_1cc
	.HIBYTES oam_sprites_1cd
	.HIBYTES oam_sprites_1ce
	.HIBYTES oam_sprites_1cf
	.HIBYTES oam_sprites_1d0
	.HIBYTES oam_sprites_1d1
	.HIBYTES oam_sprites_1d2
	.HIBYTES oam_sprites_1d3
	.HIBYTES oam_sprites_1d4
	.HIBYTES oam_sprites_1d5
	.HIBYTES oam_sprites_1d6
	.HIBYTES oam_sprites_1d7
	.HIBYTES oam_sprites_1d8
	.HIBYTES oam_sprites_1d9
	.HIBYTES oam_sprites_1da
	.HIBYTES oam_sprites_1db
	.HIBYTES oam_sprites_1dc
	.HIBYTES oam_sprites_1dd
	.HIBYTES oam_sprites_1de
	.HIBYTES oam_sprites_1df
	.HIBYTES oam_sprites_1e0
	.HIBYTES oam_sprites_1e1
	.HIBYTES oam_sprites_1e2
	.HIBYTES oam_sprites_1e3
	.HIBYTES oam_sprites_1e4
	.HIBYTES oam_sprites_1e5
	.HIBYTES oam_sprites_1e6
	.HIBYTES oam_sprites_1e7
	.HIBYTES oam_sprites_1e8
	.HIBYTES oam_sprites_1e9
	.HIBYTES oam_sprites_1ea
	.HIBYTES oam_sprites_1eb
	.HIBYTES oam_sprites_1ec
	.HIBYTES oam_sprites_1ed
	.HIBYTES oam_sprites_1ee
	.HIBYTES oam_sprites_1ef

;unused
	.BYTE $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	.BYTE $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
