;oamcoord index pointers
;lo
	.LOBYTES oamcoord_index_00 - 2
	.LOBYTES oamcoord_index_01 - 2
	.LOBYTES oamcoord_index_02 - 2
	.LOBYTES oamcoord_index_03 - 2
	.LOBYTES oamcoord_index_04 - 2
	.LOBYTES oamcoord_index_05 - 2
	.LOBYTES oamcoord_index_06 - 2
	.LOBYTES oamcoord_index_07 - 2
	.LOBYTES oamcoord_index_08 - 2
	.LOBYTES oamcoord_index_09 - 2
	.LOBYTES oamcoord_index_0a - 2
	.LOBYTES oamcoord_index_0b - 2
	.LOBYTES oamcoord_index_0c - 2
	.LOBYTES oamcoord_index_0d - 2
	.LOBYTES oamcoord_index_0e - 2
	.LOBYTES oamcoord_index_0f - 2
	.LOBYTES oamcoord_index_10 - 2
	.LOBYTES oamcoord_index_11 - 2
	.LOBYTES oamcoord_index_12 - 2
	.LOBYTES oamcoord_index_13 - 2
	.LOBYTES oamcoord_index_14 - 2
	.LOBYTES oamcoord_index_15 - 2
	.LOBYTES oamcoord_index_16 - 2
	.LOBYTES oamcoord_index_17 - 2
	.LOBYTES oamcoord_index_18 - 2
	.LOBYTES oamcoord_index_19 - 2
	.LOBYTES oamcoord_index_1a - 2
	.LOBYTES oamcoord_index_1b - 2
	.LOBYTES oamcoord_index_1c - 2
	.LOBYTES oamcoord_index_1d - 2
	.LOBYTES oamcoord_index_1e - 2
	.LOBYTES oamcoord_index_1f - 2
	.LOBYTES oamcoord_index_20 - 2
	.LOBYTES oamcoord_index_21 - 2
	.LOBYTES oamcoord_index_22 - 2
	.LOBYTES oamcoord_index_23 - 2
	.LOBYTES oamcoord_index_24 - 2
	.LOBYTES oamcoord_index_25 - 2
	.LOBYTES oamcoord_index_26 - 2
	.LOBYTES oamcoord_index_27 - 2
	.LOBYTES oamcoord_index_28 - 2
	.LOBYTES oamcoord_index_29 - 2
	.LOBYTES oamcoord_index_2a - 2
	.LOBYTES oamcoord_index_2b - 2
	.LOBYTES oamcoord_index_2c - 2
	.LOBYTES oamcoord_index_2d - 2
	.LOBYTES oamcoord_index_2e - 2
	.LOBYTES oamcoord_index_2f - 2
	.LOBYTES oamcoord_index_30 - 2
	.LOBYTES oamcoord_index_31 - 2
	.LOBYTES oamcoord_index_32 - 2
	.LOBYTES oamcoord_index_33 - 2
	.LOBYTES oamcoord_index_34 - 2
	.LOBYTES oamcoord_index_35 - 2
	.LOBYTES oamcoord_index_36 - 2
	.LOBYTES oamcoord_index_37 - 2
	.LOBYTES oamcoord_index_38 - 2
	.LOBYTES oamcoord_index_39 - 2
	.LOBYTES oamcoord_index_3a - 2
	.LOBYTES oamcoord_index_3b - 2
	.LOBYTES oamcoord_index_3c - 2
	.LOBYTES oamcoord_index_3d - 2
	.LOBYTES oamcoord_index_3e - 2
	.LOBYTES oamcoord_index_3f - 2
	.LOBYTES oamcoord_index_40 - 2
	.LOBYTES oamcoord_index_41 - 2
	.LOBYTES oamcoord_index_42 - 2
	.LOBYTES oamcoord_index_43 - 2
	.LOBYTES oamcoord_index_44 - 2
	.LOBYTES oamcoord_index_45 - 2
	.LOBYTES oamcoord_index_46 - 2
	.LOBYTES oamcoord_index_47 - 2
	.LOBYTES oamcoord_index_48 - 2
	.LOBYTES oamcoord_index_49 - 2
	.LOBYTES oamcoord_index_4a - 2
	.LOBYTES oamcoord_index_4b - 2
	.LOBYTES oamcoord_index_4c - 2
	.LOBYTES oamcoord_index_4d - 2
	.LOBYTES oamcoord_index_4e - 2
	.LOBYTES oamcoord_index_4f - 2
	.LOBYTES oamcoord_index_50 - 2
	.LOBYTES oamcoord_index_51 - 2
	.LOBYTES oamcoord_index_52 - 2
	.LOBYTES oamcoord_index_53 - 2
	.LOBYTES oamcoord_index_54 - 2
	.LOBYTES oamcoord_index_55 - 2
	.LOBYTES oamcoord_index_56 - 2
	.LOBYTES oamcoord_index_57 - 2
	.LOBYTES oamcoord_index_58 - 2
	.LOBYTES oamcoord_index_59 - 2
	.LOBYTES oamcoord_index_5a - 2
	.LOBYTES oamcoord_index_5b - 2
	.LOBYTES oamcoord_index_5c - 2
	.LOBYTES oamcoord_index_5d - 2
	.LOBYTES oamcoord_index_5e - 2
	.LOBYTES oamcoord_index_5f - 2
	.LOBYTES oamcoord_index_60 - 2
	.LOBYTES oamcoord_index_61 - 2
	.LOBYTES oamcoord_index_62 - 2
	.LOBYTES oamcoord_index_63 - 2
	.LOBYTES oamcoord_index_64 - 2
	.LOBYTES oamcoord_index_65 - 2
	.LOBYTES oamcoord_index_66 - 2
	.LOBYTES oamcoord_index_67 - 2
	.LOBYTES oamcoord_index_68 - 2
	.LOBYTES oamcoord_index_69 - 2
	.LOBYTES oamcoord_index_6a - 2
	.LOBYTES oamcoord_index_6b - 2
	.LOBYTES oamcoord_index_6c - 2
	.LOBYTES oamcoord_index_6d - 2
	.LOBYTES oamcoord_index_6e - 2
	.LOBYTES oamcoord_index_6f - 2
	.LOBYTES oamcoord_index_70 - 2
	.LOBYTES oamcoord_index_71 - 2
	.LOBYTES oamcoord_index_72 - 2
	.LOBYTES oamcoord_index_73 - 2
	.LOBYTES oamcoord_index_74 - 2
	.LOBYTES oamcoord_index_75 - 2
	.LOBYTES oamcoord_index_76 - 2
	.LOBYTES oamcoord_index_77 - 2
	.LOBYTES oamcoord_index_78 - 2
	.LOBYTES oamcoord_index_79 - 2
	.LOBYTES oamcoord_index_7a - 2
	.LOBYTES oamcoord_index_7b - 2
	.LOBYTES oamcoord_index_7c - 2
	.LOBYTES oamcoord_index_7d - 2
	.LOBYTES oamcoord_index_7e - 2
	.LOBYTES oamcoord_index_7f - 2
	.LOBYTES oamcoord_index_80 - 2
	.LOBYTES oamcoord_index_81 - 2
	.LOBYTES oamcoord_index_82 - 2
	.LOBYTES oamcoord_index_83 - 2
	.LOBYTES oamcoord_index_84 - 2
	.LOBYTES oamcoord_index_85 - 2
	.LOBYTES oamcoord_index_86 - 2
	.LOBYTES oamcoord_index_87 - 2
	.LOBYTES oamcoord_index_88 - 2
	.LOBYTES oamcoord_index_89 - 2
	.LOBYTES oamcoord_index_8a - 2
	.LOBYTES oamcoord_index_8b - 2
	.LOBYTES oamcoord_index_8c - 2
	.LOBYTES oamcoord_index_8d - 2
	.LOBYTES oamcoord_index_8e - 2
	.LOBYTES oamcoord_index_8f - 2
	.LOBYTES oamcoord_index_90 - 2
	.LOBYTES oamcoord_index_91 - 2
	.LOBYTES oamcoord_index_92 - 2
	.LOBYTES oamcoord_index_93 - 2
	.LOBYTES oamcoord_index_94 - 2
	.LOBYTES oamcoord_index_95 - 2
	.LOBYTES oamcoord_index_96 - 2
	.LOBYTES oamcoord_index_97 - 2
	.LOBYTES oamcoord_index_98 - 2
	.LOBYTES oamcoord_index_99 - 2
	.LOBYTES oamcoord_index_9a - 2
	.LOBYTES oamcoord_index_9b - 2
	.LOBYTES oamcoord_index_9c - 2
	.LOBYTES oamcoord_index_9d - 2
	.LOBYTES oamcoord_index_9e - 2
	.LOBYTES oamcoord_index_9f - 2
	.LOBYTES oamcoord_index_a0 - 2
	.LOBYTES oamcoord_index_a1 - 2
	.LOBYTES oamcoord_index_a2 - 2
	.LOBYTES oamcoord_index_a3 - 2

;unused
	.BYTE $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	.BYTE $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	.BYTE $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	.BYTE $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	.BYTE $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	.BYTE $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	.BYTE $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	.BYTE $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	.BYTE $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	.BYTE $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	.BYTE $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	.BYTE $FF, $FF, $FF, $FF

;hi
	.HIBYTES oamcoord_index_00 - 2
	.HIBYTES oamcoord_index_01 - 2
	.HIBYTES oamcoord_index_02 - 2
	.HIBYTES oamcoord_index_03 - 2
	.HIBYTES oamcoord_index_04 - 2
	.HIBYTES oamcoord_index_05 - 2
	.HIBYTES oamcoord_index_06 - 2
	.HIBYTES oamcoord_index_07 - 2
	.HIBYTES oamcoord_index_08 - 2
	.HIBYTES oamcoord_index_09 - 2
	.HIBYTES oamcoord_index_0a - 2
	.HIBYTES oamcoord_index_0b - 2
	.HIBYTES oamcoord_index_0c - 2
	.HIBYTES oamcoord_index_0d - 2
	.HIBYTES oamcoord_index_0e - 2
	.HIBYTES oamcoord_index_0f - 2
	.HIBYTES oamcoord_index_10 - 2
	.HIBYTES oamcoord_index_11 - 2
	.HIBYTES oamcoord_index_12 - 2
	.HIBYTES oamcoord_index_13 - 2
	.HIBYTES oamcoord_index_14 - 2
	.HIBYTES oamcoord_index_15 - 2
	.HIBYTES oamcoord_index_16 - 2
	.HIBYTES oamcoord_index_17 - 2
	.HIBYTES oamcoord_index_18 - 2
	.HIBYTES oamcoord_index_19 - 2
	.HIBYTES oamcoord_index_1a - 2
	.HIBYTES oamcoord_index_1b - 2
	.HIBYTES oamcoord_index_1c - 2
	.HIBYTES oamcoord_index_1d - 2
	.HIBYTES oamcoord_index_1e - 2
	.HIBYTES oamcoord_index_1f - 2
	.HIBYTES oamcoord_index_20 - 2
	.HIBYTES oamcoord_index_21 - 2
	.HIBYTES oamcoord_index_22 - 2
	.HIBYTES oamcoord_index_23 - 2
	.HIBYTES oamcoord_index_24 - 2
	.HIBYTES oamcoord_index_25 - 2
	.HIBYTES oamcoord_index_26 - 2
	.HIBYTES oamcoord_index_27 - 2
	.HIBYTES oamcoord_index_28 - 2
	.HIBYTES oamcoord_index_29 - 2
	.HIBYTES oamcoord_index_2a - 2
	.HIBYTES oamcoord_index_2b - 2
	.HIBYTES oamcoord_index_2c - 2
	.HIBYTES oamcoord_index_2d - 2
	.HIBYTES oamcoord_index_2e - 2
	.HIBYTES oamcoord_index_2f - 2
	.HIBYTES oamcoord_index_30 - 2
	.HIBYTES oamcoord_index_31 - 2
	.HIBYTES oamcoord_index_32 - 2
	.HIBYTES oamcoord_index_33 - 2
	.HIBYTES oamcoord_index_34 - 2
	.HIBYTES oamcoord_index_35 - 2
	.HIBYTES oamcoord_index_36 - 2
	.HIBYTES oamcoord_index_37 - 2
	.HIBYTES oamcoord_index_38 - 2
	.HIBYTES oamcoord_index_39 - 2
	.HIBYTES oamcoord_index_3a - 2
	.HIBYTES oamcoord_index_3b - 2
	.HIBYTES oamcoord_index_3c - 2
	.HIBYTES oamcoord_index_3d - 2
	.HIBYTES oamcoord_index_3e - 2
	.HIBYTES oamcoord_index_3f - 2
	.HIBYTES oamcoord_index_40 - 2
	.HIBYTES oamcoord_index_41 - 2
	.HIBYTES oamcoord_index_42 - 2
	.HIBYTES oamcoord_index_43 - 2
	.HIBYTES oamcoord_index_44 - 2
	.HIBYTES oamcoord_index_45 - 2
	.HIBYTES oamcoord_index_46 - 2
	.HIBYTES oamcoord_index_47 - 2
	.HIBYTES oamcoord_index_48 - 2
	.HIBYTES oamcoord_index_49 - 2
	.HIBYTES oamcoord_index_4a - 2
	.HIBYTES oamcoord_index_4b - 2
	.HIBYTES oamcoord_index_4c - 2
	.HIBYTES oamcoord_index_4d - 2
	.HIBYTES oamcoord_index_4e - 2
	.HIBYTES oamcoord_index_4f - 2
	.HIBYTES oamcoord_index_50 - 2
	.HIBYTES oamcoord_index_51 - 2
	.HIBYTES oamcoord_index_52 - 2
	.HIBYTES oamcoord_index_53 - 2
	.HIBYTES oamcoord_index_54 - 2
	.HIBYTES oamcoord_index_55 - 2
	.HIBYTES oamcoord_index_56 - 2
	.HIBYTES oamcoord_index_57 - 2
	.HIBYTES oamcoord_index_58 - 2
	.HIBYTES oamcoord_index_59 - 2
	.HIBYTES oamcoord_index_5a - 2
	.HIBYTES oamcoord_index_5b - 2
	.HIBYTES oamcoord_index_5c - 2
	.HIBYTES oamcoord_index_5d - 2
	.HIBYTES oamcoord_index_5e - 2
	.HIBYTES oamcoord_index_5f - 2
	.HIBYTES oamcoord_index_60 - 2
	.HIBYTES oamcoord_index_61 - 2
	.HIBYTES oamcoord_index_62 - 2
	.HIBYTES oamcoord_index_63 - 2
	.HIBYTES oamcoord_index_64 - 2
	.HIBYTES oamcoord_index_65 - 2
	.HIBYTES oamcoord_index_66 - 2
	.HIBYTES oamcoord_index_67 - 2
	.HIBYTES oamcoord_index_68 - 2
	.HIBYTES oamcoord_index_69 - 2
	.HIBYTES oamcoord_index_6a - 2
	.HIBYTES oamcoord_index_6b - 2
	.HIBYTES oamcoord_index_6c - 2
	.HIBYTES oamcoord_index_6d - 2
	.HIBYTES oamcoord_index_6e - 2
	.HIBYTES oamcoord_index_6f - 2
	.HIBYTES oamcoord_index_70 - 2
	.HIBYTES oamcoord_index_71 - 2
	.HIBYTES oamcoord_index_72 - 2
	.HIBYTES oamcoord_index_73 - 2
	.HIBYTES oamcoord_index_74 - 2
	.HIBYTES oamcoord_index_75 - 2
	.HIBYTES oamcoord_index_76 - 2
	.HIBYTES oamcoord_index_77 - 2
	.HIBYTES oamcoord_index_78 - 2
	.HIBYTES oamcoord_index_79 - 2
	.HIBYTES oamcoord_index_7a - 2
	.HIBYTES oamcoord_index_7b - 2
	.HIBYTES oamcoord_index_7c - 2
	.HIBYTES oamcoord_index_7d - 2
	.HIBYTES oamcoord_index_7e - 2
	.HIBYTES oamcoord_index_7f - 2
	.HIBYTES oamcoord_index_80 - 2
	.HIBYTES oamcoord_index_81 - 2
	.HIBYTES oamcoord_index_82 - 2
	.HIBYTES oamcoord_index_83 - 2
	.HIBYTES oamcoord_index_84 - 2
	.HIBYTES oamcoord_index_85 - 2
	.HIBYTES oamcoord_index_86 - 2
	.HIBYTES oamcoord_index_87 - 2
	.HIBYTES oamcoord_index_88 - 2
	.HIBYTES oamcoord_index_89 - 2
	.HIBYTES oamcoord_index_8a - 2
	.HIBYTES oamcoord_index_8b - 2
	.HIBYTES oamcoord_index_8c - 2
	.HIBYTES oamcoord_index_8d - 2
	.HIBYTES oamcoord_index_8e - 2
	.HIBYTES oamcoord_index_8f - 2
	.HIBYTES oamcoord_index_90 - 2
	.HIBYTES oamcoord_index_91 - 2
	.HIBYTES oamcoord_index_92 - 2
	.HIBYTES oamcoord_index_93 - 2
	.HIBYTES oamcoord_index_94 - 2
	.HIBYTES oamcoord_index_95 - 2
	.HIBYTES oamcoord_index_96 - 2
	.HIBYTES oamcoord_index_97 - 2
	.HIBYTES oamcoord_index_98 - 2
	.HIBYTES oamcoord_index_99 - 2
	.HIBYTES oamcoord_index_9a - 2
	.HIBYTES oamcoord_index_9b - 2
	.HIBYTES oamcoord_index_9c - 2
	.HIBYTES oamcoord_index_9d - 2
	.HIBYTES oamcoord_index_9e - 2
	.HIBYTES oamcoord_index_9f - 2
	.HIBYTES oamcoord_index_a0 - 2
	.HIBYTES oamcoord_index_a1 - 2
	.HIBYTES oamcoord_index_a2 - 2
	.HIBYTES oamcoord_index_a3 - 2

;unused
	.BYTE $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	.BYTE $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	.BYTE $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	.BYTE $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	.BYTE $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	.BYTE $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	.BYTE $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	.BYTE $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	.BYTE $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	.BYTE $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	.BYTE $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	.BYTE $FF, $FF, $FF, $FF
