oamcoord_lo_pointers:
	.LOBYTES oamcoord_00 - 2
	.LOBYTES oamcoord_01 - 2
	.LOBYTES oamcoord_02 - 2
	.LOBYTES oamcoord_03 - 2
	.LOBYTES oamcoord_04 - 2
	.LOBYTES oamcoord_05 - 2
	.LOBYTES oamcoord_06 - 2
	.LOBYTES oamcoord_07 - 2
	.LOBYTES oamcoord_08 - 2
	.LOBYTES oamcoord_09 - 2
	.LOBYTES oamcoord_0a - 2
	.LOBYTES oamcoord_0b - 2
	.LOBYTES oamcoord_0c - 2
	.LOBYTES oamcoord_0d - 2
	.LOBYTES oamcoord_0e - 2
	.LOBYTES oamcoord_0f - 2
	.LOBYTES oamcoord_10 - 2
	.LOBYTES oamcoord_11 - 2
	.LOBYTES oamcoord_12 - 2
	.LOBYTES oamcoord_13 - 2
	.LOBYTES oamcoord_14 - 2
	.LOBYTES oamcoord_15 - 2
	.LOBYTES oamcoord_16 - 2
	.LOBYTES oamcoord_17 - 2
	.LOBYTES oamcoord_18 - 2
	.LOBYTES oamcoord_19 - 2
	.LOBYTES oamcoord_1a - 2
	.LOBYTES oamcoord_1b - 2
	.LOBYTES oamcoord_1c - 2
	.LOBYTES oamcoord_1d - 2
	.LOBYTES oamcoord_1e - 2
	.LOBYTES oamcoord_1f - 2
	.LOBYTES oamcoord_20 - 2
	.LOBYTES oamcoord_21 - 2
	.LOBYTES oamcoord_22 - 2
	.LOBYTES oamcoord_23 - 2
	.LOBYTES oamcoord_24 - 2
	.LOBYTES oamcoord_25 - 2
	.LOBYTES oamcoord_26 - 2
	.LOBYTES oamcoord_27 - 2
	.LOBYTES oamcoord_28 - 2
	.LOBYTES oamcoord_29 - 2
	.LOBYTES oamcoord_2a - 2
	.LOBYTES oamcoord_2b - 2
	.LOBYTES oamcoord_2c - 2
	.LOBYTES oamcoord_2d - 2
	.LOBYTES oamcoord_2e - 2
	.LOBYTES oamcoord_2f - 2
	.LOBYTES oamcoord_30 - 2
	.LOBYTES oamcoord_31 - 2
	.LOBYTES oamcoord_32 - 2
	.LOBYTES oamcoord_33 - 2
	.LOBYTES oamcoord_34 - 2
	.LOBYTES oamcoord_35 - 2
	.LOBYTES oamcoord_36 - 2
	.LOBYTES oamcoord_37 - 2
	.LOBYTES oamcoord_38 - 2
	.LOBYTES oamcoord_39 - 2
	.LOBYTES oamcoord_3a - 2
	.LOBYTES oamcoord_3b - 2
	.LOBYTES oamcoord_3c - 2
	.LOBYTES oamcoord_3d - 2
	.LOBYTES oamcoord_3e - 2
	.LOBYTES oamcoord_3f - 2
	.LOBYTES oamcoord_40 - 2
	.LOBYTES oamcoord_41 - 2
	.LOBYTES oamcoord_42 - 2
	.LOBYTES oamcoord_43 - 2
	.LOBYTES oamcoord_44 - 2
	.LOBYTES oamcoord_45 - 2
	.LOBYTES oamcoord_46 - 2
	.LOBYTES oamcoord_47 - 2
	.LOBYTES oamcoord_48 - 2
	.LOBYTES oamcoord_49 - 2
	.LOBYTES oamcoord_4a - 2
	.LOBYTES oamcoord_4b - 2
	.LOBYTES oamcoord_4c - 2
	.LOBYTES oamcoord_4d - 2
	.LOBYTES oamcoord_4e - 2
	.LOBYTES oamcoord_4f - 2
	.LOBYTES oamcoord_50 - 2
	.LOBYTES oamcoord_51 - 2
	.LOBYTES oamcoord_52 - 2
	.LOBYTES oamcoord_53 - 2
	.LOBYTES oamcoord_54 - 2
	.LOBYTES oamcoord_55 - 2
	.LOBYTES oamcoord_56 - 2
	.LOBYTES oamcoord_57 - 2
	.LOBYTES oamcoord_58 - 2
	.LOBYTES oamcoord_59 - 2
	.LOBYTES oamcoord_5a - 2
	.LOBYTES oamcoord_5b - 2
	.LOBYTES oamcoord_5c - 2
	.LOBYTES oamcoord_5d - 2
	.LOBYTES oamcoord_5e - 2
	.LOBYTES oamcoord_5f - 2
	.LOBYTES oamcoord_60 - 2
	.LOBYTES oamcoord_61 - 2
	.LOBYTES oamcoord_62 - 2
	.LOBYTES oamcoord_63 - 2
	.LOBYTES oamcoord_64 - 2
	.LOBYTES oamcoord_65 - 2
	.LOBYTES oamcoord_66 - 2
	.LOBYTES oamcoord_67 - 2
	.LOBYTES oamcoord_68 - 2
	.LOBYTES oamcoord_69 - 2
	.LOBYTES oamcoord_6a - 2
	.LOBYTES oamcoord_6b - 2
	.LOBYTES oamcoord_6c - 2
	.LOBYTES oamcoord_6d - 2
	.LOBYTES oamcoord_6e - 2
	.LOBYTES oamcoord_6f - 2
	.LOBYTES oamcoord_70 - 2
	.LOBYTES oamcoord_71 - 2
	.LOBYTES oamcoord_72 - 2
	.LOBYTES oamcoord_73 - 2
	.LOBYTES oamcoord_74 - 2
	.LOBYTES oamcoord_75 - 2
	.LOBYTES oamcoord_76 - 2
	.LOBYTES oamcoord_77 - 2
	.LOBYTES oamcoord_78 - 2
	.LOBYTES oamcoord_79 - 2
	.LOBYTES oamcoord_7a - 2
	.LOBYTES oamcoord_7b - 2
	.LOBYTES oamcoord_7c - 2
	.LOBYTES oamcoord_7d - 2
	.LOBYTES oamcoord_7e - 2
	.LOBYTES oamcoord_7f - 2
	.LOBYTES oamcoord_80 - 2
	.LOBYTES oamcoord_81 - 2
	.LOBYTES oamcoord_82 - 2
	.LOBYTES oamcoord_83 - 2
	.LOBYTES oamcoord_84 - 2
	.LOBYTES oamcoord_85 - 2
	.LOBYTES oamcoord_86 - 2
	.LOBYTES oamcoord_87 - 2
	.LOBYTES oamcoord_88 - 2
	.LOBYTES oamcoord_89 - 2
	.LOBYTES oamcoord_8a - 2
	.LOBYTES oamcoord_8b - 2
	.LOBYTES oamcoord_8c - 2
	.LOBYTES oamcoord_8d - 2
	.LOBYTES oamcoord_8e - 2
	.LOBYTES oamcoord_8f - 2
	.LOBYTES oamcoord_90 - 2
	.LOBYTES oamcoord_91 - 2
	.LOBYTES oamcoord_92 - 2
	.LOBYTES oamcoord_93 - 2
	.LOBYTES oamcoord_94 - 2
	.LOBYTES oamcoord_95 - 2
	.LOBYTES oamcoord_96 - 2
	.LOBYTES oamcoord_97 - 2
	.LOBYTES oamcoord_98 - 2
	.LOBYTES oamcoord_99 - 2
	.LOBYTES oamcoord_9a - 2
	.LOBYTES oamcoord_9b - 2
	.LOBYTES oamcoord_9c - 2
	.LOBYTES oamcoord_9d - 2
	.LOBYTES oamcoord_9e - 2
	.LOBYTES oamcoord_9f - 2
	.LOBYTES oamcoord_a0 - 2
	.LOBYTES oamcoord_a1 - 2
	.LOBYTES oamcoord_a2 - 2
	.LOBYTES oamcoord_a3 - 2

;unused
	.BYTE $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	.BYTE $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	.BYTE $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	.BYTE $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	.BYTE $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	.BYTE $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	.BYTE $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	.BYTE $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	.BYTE $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	.BYTE $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	.BYTE $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	.BYTE $FF, $FF, $FF, $FF

oamcoord_hi_pointers:
	.HIBYTES oamcoord_00 - 2
	.HIBYTES oamcoord_01 - 2
	.HIBYTES oamcoord_02 - 2
	.HIBYTES oamcoord_03 - 2
	.HIBYTES oamcoord_04 - 2
	.HIBYTES oamcoord_05 - 2
	.HIBYTES oamcoord_06 - 2
	.HIBYTES oamcoord_07 - 2
	.HIBYTES oamcoord_08 - 2
	.HIBYTES oamcoord_09 - 2
	.HIBYTES oamcoord_0a - 2
	.HIBYTES oamcoord_0b - 2
	.HIBYTES oamcoord_0c - 2
	.HIBYTES oamcoord_0d - 2
	.HIBYTES oamcoord_0e - 2
	.HIBYTES oamcoord_0f - 2
	.HIBYTES oamcoord_10 - 2
	.HIBYTES oamcoord_11 - 2
	.HIBYTES oamcoord_12 - 2
	.HIBYTES oamcoord_13 - 2
	.HIBYTES oamcoord_14 - 2
	.HIBYTES oamcoord_15 - 2
	.HIBYTES oamcoord_16 - 2
	.HIBYTES oamcoord_17 - 2
	.HIBYTES oamcoord_18 - 2
	.HIBYTES oamcoord_19 - 2
	.HIBYTES oamcoord_1a - 2
	.HIBYTES oamcoord_1b - 2
	.HIBYTES oamcoord_1c - 2
	.HIBYTES oamcoord_1d - 2
	.HIBYTES oamcoord_1e - 2
	.HIBYTES oamcoord_1f - 2
	.HIBYTES oamcoord_20 - 2
	.HIBYTES oamcoord_21 - 2
	.HIBYTES oamcoord_22 - 2
	.HIBYTES oamcoord_23 - 2
	.HIBYTES oamcoord_24 - 2
	.HIBYTES oamcoord_25 - 2
	.HIBYTES oamcoord_26 - 2
	.HIBYTES oamcoord_27 - 2
	.HIBYTES oamcoord_28 - 2
	.HIBYTES oamcoord_29 - 2
	.HIBYTES oamcoord_2a - 2
	.HIBYTES oamcoord_2b - 2
	.HIBYTES oamcoord_2c - 2
	.HIBYTES oamcoord_2d - 2
	.HIBYTES oamcoord_2e - 2
	.HIBYTES oamcoord_2f - 2
	.HIBYTES oamcoord_30 - 2
	.HIBYTES oamcoord_31 - 2
	.HIBYTES oamcoord_32 - 2
	.HIBYTES oamcoord_33 - 2
	.HIBYTES oamcoord_34 - 2
	.HIBYTES oamcoord_35 - 2
	.HIBYTES oamcoord_36 - 2
	.HIBYTES oamcoord_37 - 2
	.HIBYTES oamcoord_38 - 2
	.HIBYTES oamcoord_39 - 2
	.HIBYTES oamcoord_3a - 2
	.HIBYTES oamcoord_3b - 2
	.HIBYTES oamcoord_3c - 2
	.HIBYTES oamcoord_3d - 2
	.HIBYTES oamcoord_3e - 2
	.HIBYTES oamcoord_3f - 2
	.HIBYTES oamcoord_40 - 2
	.HIBYTES oamcoord_41 - 2
	.HIBYTES oamcoord_42 - 2
	.HIBYTES oamcoord_43 - 2
	.HIBYTES oamcoord_44 - 2
	.HIBYTES oamcoord_45 - 2
	.HIBYTES oamcoord_46 - 2
	.HIBYTES oamcoord_47 - 2
	.HIBYTES oamcoord_48 - 2
	.HIBYTES oamcoord_49 - 2
	.HIBYTES oamcoord_4a - 2
	.HIBYTES oamcoord_4b - 2
	.HIBYTES oamcoord_4c - 2
	.HIBYTES oamcoord_4d - 2
	.HIBYTES oamcoord_4e - 2
	.HIBYTES oamcoord_4f - 2
	.HIBYTES oamcoord_50 - 2
	.HIBYTES oamcoord_51 - 2
	.HIBYTES oamcoord_52 - 2
	.HIBYTES oamcoord_53 - 2
	.HIBYTES oamcoord_54 - 2
	.HIBYTES oamcoord_55 - 2
	.HIBYTES oamcoord_56 - 2
	.HIBYTES oamcoord_57 - 2
	.HIBYTES oamcoord_58 - 2
	.HIBYTES oamcoord_59 - 2
	.HIBYTES oamcoord_5a - 2
	.HIBYTES oamcoord_5b - 2
	.HIBYTES oamcoord_5c - 2
	.HIBYTES oamcoord_5d - 2
	.HIBYTES oamcoord_5e - 2
	.HIBYTES oamcoord_5f - 2
	.HIBYTES oamcoord_60 - 2
	.HIBYTES oamcoord_61 - 2
	.HIBYTES oamcoord_62 - 2
	.HIBYTES oamcoord_63 - 2
	.HIBYTES oamcoord_64 - 2
	.HIBYTES oamcoord_65 - 2
	.HIBYTES oamcoord_66 - 2
	.HIBYTES oamcoord_67 - 2
	.HIBYTES oamcoord_68 - 2
	.HIBYTES oamcoord_69 - 2
	.HIBYTES oamcoord_6a - 2
	.HIBYTES oamcoord_6b - 2
	.HIBYTES oamcoord_6c - 2
	.HIBYTES oamcoord_6d - 2
	.HIBYTES oamcoord_6e - 2
	.HIBYTES oamcoord_6f - 2
	.HIBYTES oamcoord_70 - 2
	.HIBYTES oamcoord_71 - 2
	.HIBYTES oamcoord_72 - 2
	.HIBYTES oamcoord_73 - 2
	.HIBYTES oamcoord_74 - 2
	.HIBYTES oamcoord_75 - 2
	.HIBYTES oamcoord_76 - 2
	.HIBYTES oamcoord_77 - 2
	.HIBYTES oamcoord_78 - 2
	.HIBYTES oamcoord_79 - 2
	.HIBYTES oamcoord_7a - 2
	.HIBYTES oamcoord_7b - 2
	.HIBYTES oamcoord_7c - 2
	.HIBYTES oamcoord_7d - 2
	.HIBYTES oamcoord_7e - 2
	.HIBYTES oamcoord_7f - 2
	.HIBYTES oamcoord_80 - 2
	.HIBYTES oamcoord_81 - 2
	.HIBYTES oamcoord_82 - 2
	.HIBYTES oamcoord_83 - 2
	.HIBYTES oamcoord_84 - 2
	.HIBYTES oamcoord_85 - 2
	.HIBYTES oamcoord_86 - 2
	.HIBYTES oamcoord_87 - 2
	.HIBYTES oamcoord_88 - 2
	.HIBYTES oamcoord_89 - 2
	.HIBYTES oamcoord_8a - 2
	.HIBYTES oamcoord_8b - 2
	.HIBYTES oamcoord_8c - 2
	.HIBYTES oamcoord_8d - 2
	.HIBYTES oamcoord_8e - 2
	.HIBYTES oamcoord_8f - 2
	.HIBYTES oamcoord_90 - 2
	.HIBYTES oamcoord_91 - 2
	.HIBYTES oamcoord_92 - 2
	.HIBYTES oamcoord_93 - 2
	.HIBYTES oamcoord_94 - 2
	.HIBYTES oamcoord_95 - 2
	.HIBYTES oamcoord_96 - 2
	.HIBYTES oamcoord_97 - 2
	.HIBYTES oamcoord_98 - 2
	.HIBYTES oamcoord_99 - 2
	.HIBYTES oamcoord_9a - 2
	.HIBYTES oamcoord_9b - 2
	.HIBYTES oamcoord_9c - 2
	.HIBYTES oamcoord_9d - 2
	.HIBYTES oamcoord_9e - 2
	.HIBYTES oamcoord_9f - 2
	.HIBYTES oamcoord_a0 - 2
	.HIBYTES oamcoord_a1 - 2
	.HIBYTES oamcoord_a2 - 2
	.HIBYTES oamcoord_a3 - 2

;unused
	.BYTE $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	.BYTE $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	.BYTE $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	.BYTE $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	.BYTE $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	.BYTE $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	.BYTE $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	.BYTE $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	.BYTE $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	.BYTE $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	.BYTE $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	.BYTE $FF, $FF, $FF, $FF
